# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
"""Keep native shader configuration on the automatically encoded schema API.

This source check complements C++ constructor/signature checks. It does not prove
arbitrary C++ helper purity; generators must not depend on mutable global state.
"""

import argparse
import re
import sys
from pathlib import Path

_COMMENTS_AND_LITERALS = re.compile(
    r'//[^\n]*|/\*[\s\S]*?\*/|R"([^ ()\\\t\r\n]*)\([\s\S]*?\)\1"'
    r'|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\''
)


def mask_source(source: str) -> str:
    return _COMMENTS_AND_LITERALS.sub(lambda match: "".join("\n" if c == "\n" else " " for c in match[0]), source)


def matching_brace(source: str, start: int) -> int:
    depth = 1
    for index in range(start + 1, len(source)):
        depth += (source[index] == "{") - (source[index] == "}")
        if depth == 0:
            return index
    raise ValueError("Unmatched C++ brace")


def check_source(source: str, framework: bool = False, pipeline_owner: bool = False) -> list[str]:
    masked = mask_source(source)
    errors = []
    if not pipeline_owner and re.search(
        r"\b(?:wgpuDevice)?Create(?:ShaderModule|ComputePipeline(?:Async)?)\s*\(", masked
    ):
        errors.append("Route shader and compute pipeline creation through ProgramManager")
    if not framework:
        for pattern, message in (
            (
                r"\b(?:class|struct)\s+\w+[^;{]*:\s*public\s+(?:Program|ProgramBase|details::ProgramWrapper)\b",
                "Use ConfiguredProgram; direct program inheritance bypasses automatic identity",
            ),
            (r"\bCacheHint\s*\(", "Manual cache hints are not supported"),
            (
                r"\b(?:AppendTo|AppendSpecializationKey|StructuredKeyType)\s*\(",
                "Configuration encoding must be generated by the schema API",
            ),
            (r"\bShaderConfigSchema\b", "Do not handwrite the schema marker"),
        ):
            if re.search(pattern, masked):
                errors.append(message)

    # Inspect schema-bearing classes after masking nested function bodies. A data
    # member outside WEBGPU_CONFIG_MEMBERS would silently escape automatic encoding.
    for match in re.finditer(r"\b(?:struct|class)\s+\w+(?:\s+final)?\s*\{", masked):
        end = matching_brace(masked, match.end() - 1)
        body = masked[match.end() : end]
        flat = []
        depth = 0
        for char in body:
            flat.append(char if depth == 0 or char == "\n" else " ")
            depth += (char == "{") - (char == "}")
        flat = "".join(flat)
        if "WEBGPU_CONFIG_MEMBERS(" not in flat:
            continue
        for field in re.finditer(r"^[ \t]*([^\n;(){}]+?)\s+(\w+)\s*(?:[={][^;\n]*)?;", flat, re.MULTILINE):
            declaration = field[0].strip()
            if ")" in declaration:
                continue
            if not declaration.startswith(("using ", "static constexpr ")):
                errors.append(f"Unencoded configuration member: {declaration}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[3])
    args = parser.parse_args()
    count = 0
    failures = []
    for directory in ("onnxruntime/core/providers/webgpu", "onnxruntime/contrib_ops/webgpu"):
        for path in sorted((args.root / directory).rglob("*")):
            if path.suffix not in (".h", ".cc"):
                continue
            relative = path.relative_to(args.root).as_posix()
            framework = relative in {
                "onnxruntime/core/providers/webgpu/program.h",
                "onnxruntime/core/providers/webgpu/configured_program.h",
                "onnxruntime/core/providers/webgpu/shader_config.h",
                "onnxruntime/core/providers/webgpu/program_cache_key.cc",
                "onnxruntime/core/providers/webgpu/shader_helper.cc",
            }
            failures.extend(
                f"{relative}: {error}"
                for error in check_source(
                    path.read_text(encoding="utf-8"),
                    framework,
                    relative == "onnxruntime/core/providers/webgpu/program_manager.cc",
                )
            )
            count += 1
    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    print(f"Shader configuration policy passed ({count} native source files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
