parameters:
- name: CudaVersion
  type: string
  default: '12.2'

variables:
  - template: templates/common-variables.yml
  - name: ReleaseVersionSuffix
    value: ''
  - name: win_cuda_home
    ${{ if eq(parameters.CudaVersion, '11.8') }}:
      value: $(Agent.TempDirectory)\v11.8
    ${{ if eq(parameters.CudaVersion, '12.2') }}:
      value: $(Agent.TempDirectory)\v12.2

stages:
  - template: ../templates/win-ci.yml
    parameters:
      ort_build_pool_name: 'onnxruntime-Win2022-GPU-A10'
      DoCompliance: true
      DoEsrp: true
      stage_name_suffix: CUDA
      buildArch: x64
      msbuildPlatform: x64
      packageName: x64-cuda
      CudaVersion: ${{ parameters.CudaVersion }}
      buildparameter: --use_cuda --cuda_home=${{ parameters.win_cuda_home }} --enable_onnx_tests --enable_wcos --use_webgpu --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=52-real;61-real;75-real;86-real;89-real;90-virtual"
      runTests: false
      buildJava: false
      java_artifact_id: onnxruntime_gpu
      UseIncreasedTimeoutForTests: false
      SpecificArtifact: false
      BuildId: '0'
