parameters:
- name: CudaVersion
  type: string
  default: '12.2'

- name: QnnSdk
  displayName: QNN SDK Version
  type: string
  default: 2.31.0.250130

- name: IsReleaseBuild
  displayName: Is a release build? Set it to true if you are doing an Onnx Runtime release.
  type: boolean
  default: false

variables:
  - template: templates/common-variables.yml
  - name: ReleaseVersionSuffix
    value: ''
  - name: win_cuda_home
    ${{ if eq(parameters.CudaVersion, '11.8') }}:
      value: $(Agent.TempDirectory)\v11.8
    ${{ if eq(parameters.CudaVersion, '12.2') }}:
      value: $(Agent.TempDirectory)\v12.2

stages:
  - template: templates/win-ci.yml
    parameters:
      ort_build_pool_name: 'onnxruntime-Win2022-GPU-A10'
      DoCompliance: true
      DoEsrp: true
      stage_name_suffix: CUDA
      buildArch: x64
      msbuildPlatform: x64
      packageName: x64-cuda
      CudaVersion: ${{ parameters.CudaVersion }}
      buildparameter: --use_cuda --cuda_home=${{ variables.win_cuda_home }} --enable_onnx_tests --enable_wcos --use_webgpu --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=52-real;61-real;75-real;86-real;89-real;90-virtual"
      runTests: false
      buildJava: false
      java_artifact_id: onnxruntime_gpu
      UseIncreasedTimeoutForTests: false
      SpecificArtifact: false
      BuildId: '0'

  - template: templates/qnn-ep-win.yml
    parameters:
      qnn_ep_build_pool_name: 'Onnxruntime-QNNEP-Windows-2022-CPU'
      QnnSdk: ${{ parameters.QnnSdk }}
      IsReleaseBuild: ${{ parameters.IsReleaseBuild }}
      DoEsrp: true
      ArtifactName: 'drop-nuget-qnn-arm64'
      buildParameter: '--arm64 --use_webgpu'
      buildPlatform: 'ARM64'
      buildArch: 'ARM64'
      StageName: 'OnnxRuntime_QNN_Nuget_Win_Arm64'
      build_config: 'RelWithDebInfo'
