
parameters:
- name: image_list
  displayName: 'Images to validate'
  type: stringList
  values:
  - 'onnxruntime-azlinux3-arm64'

stages:
- ${{ each image in parameters.image_list }}:
  - template: stages/${{ image }}-validation.yml
