
trigger: none

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
- name: image_list
  displayName: 'Images to validate'
  type: stringList
  values:
  - 'onnxruntime-azlinux3-arm64'
  # - 'onnxruntime-qnn-windows22-arm64'
  # - 'onnxruntime-qnnep-ubuntu2204-managed2'
  # - 'onnxruntime-ubuntu2204-cuda'
  # - 'onnxruntime-win-cpu-vs2022-latest-nvme-x64'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    settings:
      networkIsolationPolicy: Permissive
    featureFlags:
      binskimScanAllExtensions: true
    sdl:
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true
      sourceAnalysisPool:
        name: onnxruntime-Win-CPU-VS2022-Latest
        os: windows
      componentgovernance:
        ignoreDirectories: '$(Build.Repository.LocalPath)/cmake/external/emsdk/upstream/emscripten/tests,$(Build.Repository.LocalPath)/cmake/external/onnx/third_party/benchmark,$(Build.Repository.LocalPath)/cmake/external/onnx/third_party/pybind11,$(Build.Repository.LocalPath)/cmake/external/onnx/third_party/pybind11/tests,$(Build.Repository.LocalPath)/cmake/external/onnxruntime-extensions,$(Build.Repository.LocalPath)/js/react_native/e2e/node_modules,$(Build.Repository.LocalPath)/js/node_modules,$(Build.Repository.LocalPath)/onnxruntime-inference-examples,$(Build.SourcesDirectory)/cmake/external/emsdk/upstream/emscripten/tests,$(Build.SourcesDirectory)/cmake/external/onnx/third_party/benchmark,$(Build.SourcesDirectory)/cmake/external/onnx/third_party/pybind11,$(Build.SourcesDirectory)/cmake/external/onnx/third_party/pybind11/tests,$(Build.SourcesDirectory)/cmake/external/onnxruntime-extensions,$(Build.SourcesDirectory)/js/react_native/e2e/node_modules,$(Build.SourcesDirectory)/js/node_modules,$(Build.SourcesDirectory)/onnxruntime-inference-examples,$(Build.BinariesDirectory)'
      spotBugs:
        enabled: false
        justificationForDisabling: "Getting ##[error]1. SpotBugs Error gdn.unknownFormatResult - File: spotbugs.xml, which indicates that SpotBugs found one or more errors, which are not handled by the Guardian right now."
      codeql:
        compiled:
          enabled: false
          justificationForDisabling: 'CodeQL is taking nearly 6 hours resulting in timeouts in our production pipelines'
      tsa:
        enabled: true
      codeSignValidation:
        enabled: true
        break: true
      policheck:
        enabled: true
        exclusionsFile: '$(Build.SourcesDirectory)\tools\ci_build\policheck_exclusions.xml'

    stages:
    - ${{ each image in parameters.image_list }}:
      - template: stages/${{ image }}-validation.yml
