// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// This file is generated by compile_sparse_attention.py using triton AoT compiler

#pragma once
#include "contrib_ops/cuda/sparse/sparse_attention_trition/sparse_attention_common.h"

namespace onnxruntime {
namespace contrib {
namespace cuda {

// launcher for: sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2
Status sparse_attention_bf16_sm80_a99edeed(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_a99edeed(params);
}

// load for: sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2
void load_sparse_attention_bf16_sm80_a99edeed();
void load_sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2() {
  load_sparse_attention_bf16_sm80_a99edeed();
}

// unload for: sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2
void unload_sparse_attention_bf16_sm80_a99edeed();
void unload_sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2() {
  unload_sparse_attention_bf16_sm80_a99edeed();
}

// launcher for: sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2
Status sparse_attention_bf16_sm80_5df6b0e9(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_5df6b0e9(params);
}

// load for: sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2
void load_sparse_attention_bf16_sm80_5df6b0e9();
void load_sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2() {
  load_sparse_attention_bf16_sm80_5df6b0e9();
}

// unload for: sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2
void unload_sparse_attention_bf16_sm80_5df6b0e9();
void unload_sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2() {
  unload_sparse_attention_bf16_sm80_5df6b0e9();
}

// launcher for: sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2
Status sparse_attention_bf16_sm80_316fde50(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_316fde50(params);
}

// load for: sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2
void load_sparse_attention_bf16_sm80_316fde50();
void load_sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2() {
  load_sparse_attention_bf16_sm80_316fde50();
}

// unload for: sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2
void unload_sparse_attention_bf16_sm80_316fde50();
void unload_sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2() {
  unload_sparse_attention_bf16_sm80_316fde50();
}

// launcher for: sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2
Status sparse_attention_bf16_sm80_f703b29e(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_f703b29e(params);
}

// load for: sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2
void load_sparse_attention_bf16_sm80_f703b29e();
void load_sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2() {
  load_sparse_attention_bf16_sm80_f703b29e();
}

// unload for: sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2
void unload_sparse_attention_bf16_sm80_f703b29e();
void unload_sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2() {
  unload_sparse_attention_bf16_sm80_f703b29e();
}

// launcher for: sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2
Status sparse_attention_bf16_sm80_076ece68(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_076ece68(params);
}

// load for: sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2
void load_sparse_attention_bf16_sm80_076ece68();
void load_sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2() {
  load_sparse_attention_bf16_sm80_076ece68();
}

// unload for: sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2
void unload_sparse_attention_bf16_sm80_076ece68();
void unload_sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2() {
  unload_sparse_attention_bf16_sm80_076ece68();
}

// launcher for: sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2
Status sparse_attention_bf16_sm80_1e29d359(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_1e29d359(params);
}

// load for: sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2
void load_sparse_attention_bf16_sm80_1e29d359();
void load_sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2() {
  load_sparse_attention_bf16_sm80_1e29d359();
}

// unload for: sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2
void unload_sparse_attention_bf16_sm80_1e29d359();
void unload_sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2() {
  unload_sparse_attention_bf16_sm80_1e29d359();
}

// launcher for: sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2
Status sparse_attention_bf16_sm80_af80c5f1(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_af80c5f1(params);
}

// load for: sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2
void load_sparse_attention_bf16_sm80_af80c5f1();
void load_sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2() {
  load_sparse_attention_bf16_sm80_af80c5f1();
}

// unload for: sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2
void unload_sparse_attention_bf16_sm80_af80c5f1();
void unload_sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2() {
  unload_sparse_attention_bf16_sm80_af80c5f1();
}

// launcher for: sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2
Status sparse_attention_bf16_sm80_22af2291(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_22af2291(params);
}

// load for: sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2
void load_sparse_attention_bf16_sm80_22af2291();
void load_sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2() {
  load_sparse_attention_bf16_sm80_22af2291();
}

// unload for: sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2
void unload_sparse_attention_bf16_sm80_22af2291();
void unload_sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2() {
  unload_sparse_attention_bf16_sm80_22af2291();
}

typedef Status (*kernel_func_t)(SparseAttentionParams& params);
kernel_func_t sparse_attention_bf16_sm80_kernels[] = {
    sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2,
    sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2,
    sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2,
    sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2,
    sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2,
    sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2,
    sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2,
    sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2,
};

int sparse_attention_bf16_sm80_get_num_algos(void) {
  return (int)sizeof(sparse_attention_bf16_sm80_kernels);
}

Status sparse_attention_bf16_sm80(SparseAttentionParams& params, int algo_id) {
  assert(algo_id < (int)sizeof(sparse_attention_bf16_sm80_kernels));
  return sparse_attention_bf16_sm80_kernels[algo_id](params);
}

void load_sparse_attention_bf16_sm80(void) {
  load_sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2();
  load_sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2();
  load_sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2();
  load_sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2();
  load_sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2();
  load_sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2();
  load_sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2();
  load_sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2();
}

void unload_sparse_attention_bf16_sm80(void) {
  unload_sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2();
  unload_sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2();
  unload_sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2();
  unload_sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2();
  unload_sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2();
  unload_sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2();
  unload_sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2();
  unload_sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2();
}

Status sparse_attention_bf16_sm80_default(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80(params, 0);
}

}  // namespace cuda
}  // namespace contrib
}  // namespace onnxruntime
