// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// This file is generated by compile_sparse_attention.py using triton AoT compiler

#pragma once
#include "contrib_ops/cuda/sparse/sparse_attention_trition/sparse_attention_common.h"

namespace onnxruntime {
namespace contrib {
namespace cuda {

// launcher for: sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2
Status sparse_attention_bf16_sm80_35f85a76(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_35f85a76(params);
}

// load for: sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2
void load_sparse_attention_bf16_sm80_35f85a76();
void load_sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2() {
  load_sparse_attention_bf16_sm80_35f85a76();
}

// unload for: sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2
void unload_sparse_attention_bf16_sm80_35f85a76();
void unload_sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2() {
  unload_sparse_attention_bf16_sm80_35f85a76();
}

// launcher for: sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2
Status sparse_attention_bf16_sm80_cde3259a(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_cde3259a(params);
}

// load for: sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2
void load_sparse_attention_bf16_sm80_cde3259a();
void load_sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2() {
  load_sparse_attention_bf16_sm80_cde3259a();
}

// unload for: sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2
void unload_sparse_attention_bf16_sm80_cde3259a();
void unload_sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2() {
  unload_sparse_attention_bf16_sm80_cde3259a();
}

// launcher for: sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2
Status sparse_attention_bf16_sm80_33a08455(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_33a08455(params);
}

// load for: sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2
void load_sparse_attention_bf16_sm80_33a08455();
void load_sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2() {
  load_sparse_attention_bf16_sm80_33a08455();
}

// unload for: sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2
void unload_sparse_attention_bf16_sm80_33a08455();
void unload_sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2() {
  unload_sparse_attention_bf16_sm80_33a08455();
}

// launcher for: sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2
Status sparse_attention_bf16_sm80_54e91e4a(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_54e91e4a(params);
}

// load for: sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2
void load_sparse_attention_bf16_sm80_54e91e4a();
void load_sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2() {
  load_sparse_attention_bf16_sm80_54e91e4a();
}

// unload for: sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2
void unload_sparse_attention_bf16_sm80_54e91e4a();
void unload_sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2() {
  unload_sparse_attention_bf16_sm80_54e91e4a();
}

// launcher for: sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2
Status sparse_attention_bf16_sm80_739b267e(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_739b267e(params);
}

// load for: sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2
void load_sparse_attention_bf16_sm80_739b267e();
void load_sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2() {
  load_sparse_attention_bf16_sm80_739b267e();
}

// unload for: sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2
void unload_sparse_attention_bf16_sm80_739b267e();
void unload_sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2() {
  unload_sparse_attention_bf16_sm80_739b267e();
}

// launcher for: sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2
Status sparse_attention_bf16_sm80_3cb4e426(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_3cb4e426(params);
}

// load for: sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2
void load_sparse_attention_bf16_sm80_3cb4e426();
void load_sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2() {
  load_sparse_attention_bf16_sm80_3cb4e426();
}

// unload for: sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2
void unload_sparse_attention_bf16_sm80_3cb4e426();
void unload_sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2() {
  unload_sparse_attention_bf16_sm80_3cb4e426();
}

// launcher for: sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2
Status sparse_attention_bf16_sm80_428a5f18(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_428a5f18(params);
}

// load for: sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2
void load_sparse_attention_bf16_sm80_428a5f18();
void load_sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2() {
  load_sparse_attention_bf16_sm80_428a5f18();
}

// unload for: sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2
void unload_sparse_attention_bf16_sm80_428a5f18();
void unload_sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2() {
  unload_sparse_attention_bf16_sm80_428a5f18();
}

// launcher for: sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2
Status sparse_attention_bf16_sm80_ff7fa830(SparseAttentionParams& params);

Status sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80_ff7fa830(params);
}

// load for: sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2
void load_sparse_attention_bf16_sm80_ff7fa830();
void load_sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2() {
  load_sparse_attention_bf16_sm80_ff7fa830();
}

// unload for: sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2
void unload_sparse_attention_bf16_sm80_ff7fa830();
void unload_sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2() {
  unload_sparse_attention_bf16_sm80_ff7fa830();
}

typedef Status (*kernel_func_t)(SparseAttentionParams& params);
kernel_func_t sparse_attention_bf16_sm80_kernels[] = {
    sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2,
    sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2,
    sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2,
    sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2,
    sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2,
    sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2,
    sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2,
    sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2,
};

int sparse_attention_bf16_sm80_get_num_algos(void) {
  return (int)sizeof(sparse_attention_bf16_sm80_kernels);
}

Status sparse_attention_bf16_sm80(SparseAttentionParams& params, int algo_id) {
  assert(algo_id < (int)sizeof(sparse_attention_bf16_sm80_kernels));
  return sparse_attention_bf16_sm80_kernels[algo_id](params);
}

void load_sparse_attention_bf16_sm80(void) {
  load_sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2();
  load_sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2();
  load_sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2();
  load_sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2();
  load_sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2();
  load_sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2();
  load_sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2();
  load_sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2();
}

void unload_sparse_attention_bf16_sm80(void) {
  unload_sparse_attention_bf16_sm80_16x0x64x0x64x2_warps1xstages2();
  unload_sparse_attention_bf16_sm80_16x0x64x1x64x2_warps1xstages2();
  unload_sparse_attention_bf16_sm80_16x1x64x0x64x2_warps1xstages2();
  unload_sparse_attention_bf16_sm80_16x1x64x1x64x2_warps1xstages2();
  unload_sparse_attention_bf16_sm80_64x0x64x0x64x2_warps4xstages2();
  unload_sparse_attention_bf16_sm80_64x0x64x1x64x2_warps4xstages2();
  unload_sparse_attention_bf16_sm80_64x1x64x0x64x2_warps4xstages2();
  unload_sparse_attention_bf16_sm80_64x1x64x1x64x2_warps4xstages2();
}

Status sparse_attention_bf16_sm80_default(SparseAttentionParams& params) {
  return sparse_attention_bf16_sm80(params, 0);
}

}  // namespace cuda
}  // namespace contrib
}  // namespace onnxruntime
