set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set (CMAKE_SYSTEM_VERSION 1)
set(tools "$ENV{HOME}/toolchain/gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabi")
set(CMAKE_C_COMPILER ${tools}/bin/arm-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/arm-linux-gnueabi-g++)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
set (CMAKE_C_LINKER "${tools}/arm-linux-gnueabi/bin/ld")
set (CMAKE_CXX_LINKER "${tools}/arm-linux-gnueabi/bin/ld")
SET(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -mfloat-abi=softfp -mfpu=vfp")
SET(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -mfloat-abi=softfp -mfpu=vfp")

set(CMAKE_FIND_ROOT_PATH "${tools}/arm-linux-gnueabi")
set (CMAKE_LIBRARY_PATH "${tools}")
set (CMAKE_PREFIX_PATH "${tools}")
set(CMAKE_INSTALL_RPATH "${tools}/arm-linux-gnueabi/lib")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

