python $PSScriptRoot\tools\ci_build\build.py `
    --build_dir $PSScriptRoot\build\Windows `
    --config Debug `
    --build_shared_lib `
    --parallel `
    --skip_tests `
    --skip_submodule_sync `
    --target install `
    --gdk `
    --gdk_edition 210602 `
    --cmake_extra_defines CMAKE_INSTALL_PREFIX=$PSScriptRoot/build/install `
