
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#pragma once

#include <string>
#include <atomic>
#include "core/framework/onnx_object.h"

/**
 * Configuration information for a single Run.
 */
struct ONNXRuntimeRunOptions {
  const ONNXObject* const cls;
  std::atomic_int ref_count;
  unsigned run_log_verbosity_level = 0;  ///< applies to a particular Run() invocation
  std::string run_tag;                   ///< to identify logs generated by a particular Run() invocation
  ONNXRuntimeRunOptions();
  ~ONNXRuntimeRunOptions() = default;
  ONNXRuntimeRunOptions(const ONNXRuntimeRunOptions& other);
  ONNXRuntimeRunOptions& operator=(const ONNXRuntimeRunOptions& other);
};

namespace onnxruntime {
using RunOptions = ONNXRuntimeRunOptions;
}