// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Custom GridSample tests not generated by grid_sample_test_gen.py.
// These cover edge cases (extreme coordinates, NaN/Inf, dim==1, border, 3D)
// that exercise the float->int64 cast hardening in
// onnxruntime/core/providers/cpu/tensor/grid_sample.cc.

#include <limits>
#include <memory>
#include <utility>
#include <vector>

#include "gtest/gtest.h"

#include "core/framework/execution_provider.h"
#include "test/providers/provider_test_utils.h"
#include "test/util/include/default_providers.h"

namespace onnxruntime {
namespace test {
namespace {

std::vector<std::unique_ptr<IExecutionProvider>> GetCpuExecutionProviders() {
  std::vector<std::unique_ptr<IExecutionProvider>> execution_providers;
  execution_providers.emplace_back(DefaultCpuExecutionProvider());
  return execution_providers;
}

std::vector<std::unique_ptr<IExecutionProvider>> GetExecutionProviders() {
  std::vector<std::unique_ptr<IExecutionProvider>> execution_providers;

  execution_providers.emplace_back(DefaultCpuExecutionProvider());

#ifdef USE_CUDA
  execution_providers.emplace_back(DefaultCudaExecutionProvider());
#ifdef ENABLE_CUDA_NHWC_OPS
  execution_providers.push_back(DefaultCudaNHWCExecutionProvider());
#endif
#endif

#if defined(USE_COREML)
  execution_providers.push_back(DefaultCoreMLExecutionProvider(/*use_mlprogram*/ true));
#endif

#ifdef USE_WEBGPU
  execution_providers.push_back(DefaultWebGpuExecutionProvider());
#endif

  return execution_providers;
}

template <typename T>
void RunTests(T& test, std::vector<std::unique_ptr<IExecutionProvider>>&& execution_providers) {
  for (size_t idx = 0; idx < execution_providers.size(); ++idx) {
    test.ConfigEp(std::move(execution_providers[idx])).RunWithConfig();
  }
  execution_providers.clear();
}

template <typename T>
void RunCpuOnly(T& test) {
  RunTests(test, GetCpuExecutionProviders());
}

template <typename T>
void RunTestsExpectFailure(T& test, const std::string& error_msg,
                           std::vector<std::unique_ptr<IExecutionProvider>>&& execution_providers) {
  for (size_t idx = 0; idx < execution_providers.size(); ++idx) {
    test.Config(BaseTester::ExpectResult::kExpectFailure, error_msg)
        .ConfigEp(std::move(execution_providers[idx]))
        .RunWithConfig();
  }
  execution_providers.clear();
}

// Execution providers targeted by the float->int64 cast hardening in the CUDA GridSample
// kernels (onnxruntime/core/providers/cuda/tensor/grid_sample_impl.cu). CoreML and WebGPU
// are intentionally excluded here: their integer-conversion semantics differ from the
// CPU/CUDA "substitute the in-range border" behavior on NaN/Inf/extreme coordinates, so
// their outputs for these adversarial inputs are not expected to match.
std::vector<std::unique_ptr<IExecutionProvider>> GetCpuAndCudaExecutionProviders() {
  std::vector<std::unique_ptr<IExecutionProvider>> execution_providers;
  execution_providers.emplace_back(DefaultCpuExecutionProvider());

#ifdef USE_CUDA
  execution_providers.emplace_back(DefaultCudaExecutionProvider());
#ifdef ENABLE_CUDA_NHWC_OPS
  execution_providers.push_back(DefaultCudaNHWCExecutionProvider());
#endif
#endif

  return execution_providers;
}

template <typename T>
void RunCpuAndCuda(T& test) {
  RunTests(test, GetCpuAndCudaExecutionProviders());
}

}  // namespace

template <typename T>
class GridSampleCustomTest : public ::testing::Test {
};

using GridSampleCustomTestTypes = ::testing::Types<float, MLFloat16>;
TYPED_TEST_SUITE(GridSampleCustomTest, GridSampleCustomTestTypes);

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_linear_zeros_mixed_bounds_right_bottom) {
  // Crafts grid points that mix fully in-bounds sampling with cases where either the right, bottom,
  // or both neighbors fall outside the source image so zero padding must be applied. This ensures
  // the optimized bilinear fast path matches the generic implementation for boundary handling.
  OpTester test("GridSample", 20);
  std::string mode = "linear";
  std::string padding_mode = "zeros";
  int64_t align_corners = 0;
  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> X_data{TypeParam(1.0f), TypeParam(2.0f), TypeParam(3.0f), TypeParam(4.0f)};
  std::initializer_list<int64_t> Grid_shape{1, 2, 2, 2};
  // (nx, ny) pairs: center (in-bounds), right edge (x out), bottom edge (y out), corner (both out)
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f),   // center (all neighbors in bounds)
      TypeParam(0.9f), TypeParam(0.0f),   // near right edge (right neighbors out of bounds)
      TypeParam(0.0f), TypeParam(0.9f),   // near bottom edge (bottom neighbors out)
      TypeParam(0.9f), TypeParam(0.9f)};  // near bottom-right corner (both right and bottom neighbors out)
  std::initializer_list<int64_t> Y_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> Y_data{
      TypeParam(2.5f),    // all neighbors in bounds
      TypeParam(1.8f),    // right neighbors partially out-of-bounds
      TypeParam(2.1f),    // bottom neighbors partially out-of-bounds
      TypeParam(1.44f)};  // both right and bottom neighbors out-of-bounds
  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddAttribute("mode", mode);
  test.AddAttribute("padding_mode", padding_mode);
  test.AddAttribute("align_corners", align_corners);
  test.AddOutput<TypeParam>("Y", Y_shape, Y_data);
  RunTests(test, GetExecutionProviders());
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_linear_zeros_mixed_bounds_left_top) {
  // Similar to test_grid_sample_20_4D_linear_zeros_mixed_bounds_right_bottom but focuses on left/top boundary cases,
  // where the left and/or top neighbors fall outside the source image and zero padding must be applied.
  // This ensures the optimized bilinear fast path correctly handles left/top boundary conditions.
  OpTester test("GridSample", 20);
  std::string mode = "linear";
  std::string padding_mode = "zeros";
  int64_t align_corners = 0;
  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> X_data{TypeParam(1.0f), TypeParam(2.0f), TypeParam(3.0f), TypeParam(4.0f)};
  std::initializer_list<int64_t> Grid_shape{1, 2, 2, 2};
  // (nx, ny) pairs: center (in-bounds), left edge (x out), top edge (y out), corner (both out)
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f),     // center (all neighbors in bounds)
      TypeParam(-0.9f), TypeParam(0.0f),    // near left edge (left neighbors out of bounds)
      TypeParam(0.0f), TypeParam(-0.9f),    // near top edge (top neighbors out of bounds)
      TypeParam(-0.9f), TypeParam(-0.9f)};  // near top-left corner (both left and top neighbors out of bounds)
  std::initializer_list<int64_t> Y_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> Y_data{
      TypeParam(2.5f),    // all neighbors in bounds
      TypeParam(1.2f),    // left neighbors partially out-of-bounds
      TypeParam(0.9f),    // top neighbors partially out-of-bounds
      TypeParam(0.36f)};  // both left and top neighbors out-of-bounds
  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddAttribute("mode", mode);
  test.AddAttribute("padding_mode", padding_mode);
  test.AddAttribute("align_corners", align_corners);
  test.AddOutput<TypeParam>("Y", Y_shape, Y_data);
  RunTests(test, GetExecutionProviders());
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_reflection_extreme_coords) {
  // Regression test: large grid coordinates previously produced wild indices in the
  // reflection branch of PixelAtGrid. The internal division-and-int-cast inside
  // GsReflect now uses int64_t, and PixelAtGrid clamps the resulting index back into
  // the image range, so sampling stays in bounds. Using "nearest" mode keeps the test
  // focused on the reflection index path (no bilinear weight arithmetic), and using a
  // constant-valued input makes the expected output deterministic regardless of which
  // in-range pixel is hit.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> X_data{TypeParam(1.0f), TypeParam(1.0f),
                                          TypeParam(1.0f), TypeParam(1.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  // 1e+10 exceeds INT_MAX, so the pre-fix `int n = static_cast<int>(dx / range)`
  // inside GsReflect would invoke undefined behavior; 1e+10 still fits comfortably
  // in int64_t. For MLFloat16 the value overflows to +/-Inf, exercising the same
  // safety-clamp fallback in PixelAtGrid.
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(1.0e+10f), TypeParam(1.0e+10f),
      TypeParam(-1.0e+10f), TypeParam(-1.0e+10f)};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_reflection_nan_coords) {
  // Regression test: NaN grid coordinates would otherwise propagate into
  // static_cast<int64_t>(std::nearbyint(NaN)), which is undefined behavior.
  // The Compute loop now sanitizes such coordinates to the in-range border
  // before performing the cast, producing defined sampling.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> X_data{TypeParam(1.0f), TypeParam(1.0f),
                                          TypeParam(1.0f), TypeParam(1.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  const float nan_val = std::numeric_limits<float>::quiet_NaN();
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(nan_val), TypeParam(nan_val),
      TypeParam(0.0f), TypeParam(nan_val)};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  // With a constant-valued image any reflected pixel returns 1.0.
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_bilinear_reflection_infinity_coords) {
  // Regression test: Inf grid coordinates would otherwise reach
  // static_cast<int64_t>(std::floor(Inf)), which is undefined behavior.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> X_data{TypeParam(1.0f), TypeParam(1.0f),
                                          TypeParam(1.0f), TypeParam(1.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  const float inf_val = std::numeric_limits<float>::infinity();
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(inf_val), TypeParam(-inf_val),
      TypeParam(-inf_val), TypeParam(inf_val)};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  // Constant-valued image: any reflected sample returns 1.0.
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_bilinear_reflection_extreme_coords) {
  // Bilinear interpolation path: the four corner indices are computed via
  // static_cast<int64_t>(std::floor(x)). With a constant-valued image the
  // expected output is 1.0 regardless of which reflected pixel is hit.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> X_data{TypeParam(1.0f), TypeParam(1.0f),
                                          TypeParam(1.0f), TypeParam(1.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(1.0e+20f), TypeParam(1.0e+20f),
      TypeParam(-1.0e+20f), TypeParam(-1.0e+20f)};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  // With a constant-valued image any sampled pixel is 1.0.
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TEST(GridSampleCustomTestFloatOnly, test_grid_sample_20_4D_cubic_reflection_extreme_coords) {
  // Cubic interpolation path: the 4x4 neighborhood is computed via
  // static_cast<int64_t>(std::floor(x)) - 1, exercising the same UB-prone cast.
  // Cubic only supports float (T1 type constraint), so this test is float-only.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("cubic"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 4, 4};
  std::initializer_list<float> X_data{
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 1, 2};
  std::initializer_list<float> Grid_data{1.0e+10f, -1.0e+10f};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 1};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  // Constant-valued image: cubic interpolation of all-1.0 neighborhood is 1.0.
  test.AddOutput<float>("Y", Y_shape, {1.0f});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_5D_nearest_reflection_extreme_coords) {
  // 3D / 5-D input: the reflection branch in PixelAtGrid3D received the same
  // safety clamp as PixelAtGrid; this test exercises that path.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2, 2};
  std::initializer_list<TypeParam> X_data{
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 1, 2, 3};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(1.0e+10f), TypeParam(1.0e+10f), TypeParam(1.0e+10f),
      TypeParam(-1.0e+10f), TypeParam(-1.0e+10f), TypeParam(-1.0e+10f)};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_reflection_dim1_align_corners) {
  // With a 1x1 image and align_corners=true, x_min == x_max so the reflection
  // range is zero. GsReflect must not divide by zero on any out-of-range coord.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{1});

  std::initializer_list<int64_t> X_shape{1, 1, 1, 1};
  std::initializer_list<TypeParam> X_data{TypeParam(7.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.5f), TypeParam(0.5f),
      TypeParam(-0.5f), TypeParam(-0.5f)};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  // The single input pixel is the only valid sample for any reflected coordinate.
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(7.0f), TypeParam(7.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_bilinear_border_extreme_coords) {
  // Border padding mode is independently safe via std::clamp; this regression
  // test ensures it stays safe with extreme grid coordinates.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("border"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> X_data{TypeParam(1.0f), TypeParam(1.0f),
                                          TypeParam(1.0f), TypeParam(1.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(1.0e+20f), TypeParam(1.0e+20f),
      TypeParam(-1.0e+20f), TypeParam(-1.0e+20f)};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  // Constant-valued image: any clamped border sample is 1.0.
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_linear_zeros_extreme_nan_inf_coords) {
  // Zeros padding is safe by design, but the IsSafeForInt64Conversion sanitization
  // (in PrecomputeBilinearSamplePlan2D) replaces NaN/Inf/extreme values with the
  // lower border (-0.5) before the floor cast. Verify the optimized bilinear
  // zeros-padding fast path still produces a deterministic, well-defined output
  // for those inputs.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("zeros"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> X_data{TypeParam(1.0f), TypeParam(1.0f),
                                          TypeParam(1.0f), TypeParam(1.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 3, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(std::numeric_limits<float>::quiet_NaN()),
      TypeParam(std::numeric_limits<float>::quiet_NaN()),
      TypeParam(std::numeric_limits<float>::infinity()),
      TypeParam(-std::numeric_limits<float>::infinity()),
      TypeParam(1.0e+20f), TypeParam(-1.0e+20f)};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 3};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  // Each unsafe coord is sanitized to (-0.5, -0.5); only the bottom-right neighbor
  // (pixel(0, 0) = 1.0) is in-bounds with weight 0.5*0.5 = 0.25, others are zeros.
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(0.25f), TypeParam(0.25f), TypeParam(0.25f)});
  RunCpuOnly(test);
}

TEST(GridSampleCustomTestFloatOnly, test_grid_sample_20_4D_cubic_reflection_nan_inf_coords) {
  // Cubic interpolation also goes through static_cast<int64_t>(std::floor(x)) - 1.
  // Cover the NaN / +Inf / -Inf paths through the cubic kernel; constant-valued
  // image makes the output trivially 1.0 regardless of which 4x4 neighborhood is
  // selected after sanitization.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("cubic"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 4, 4};
  std::initializer_list<float> X_data{
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 3, 2};
  std::initializer_list<float> Grid_data{
      std::numeric_limits<float>::quiet_NaN(),
      std::numeric_limits<float>::quiet_NaN(),
      std::numeric_limits<float>::infinity(),
      -std::numeric_limits<float>::infinity(),
      -std::numeric_limits<float>::infinity(),
      std::numeric_limits<float>::infinity()};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 3};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  test.AddOutput<float>("Y", Y_shape, {1.0f, 1.0f, 1.0f});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_5D_linear_reflection_extreme_coords) {
  // 3D trilinear path: exercises std::floor cast for x, y, and z with extreme
  // finite coordinates. Sanitization replaces the unsafe components with the
  // lower borders before any int64 cast.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2, 2};
  std::initializer_list<TypeParam> X_data{
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 1, 2, 3};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(1.0e+20f), TypeParam(1.0e+20f), TypeParam(1.0e+20f),
      TypeParam(-1.0e+20f), TypeParam(-1.0e+20f), TypeParam(-1.0e+20f)};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  // Constant-valued image: trilinear interpolation of all-1.0 neighborhood is 1.0.
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_5D_nearest_reflection_nan_inf_coords) {
  // 3D path with NaN / Inf / -Inf in different spatial dimensions. Verifies
  // that the 3D sanitization branch handles non-finite values along any axis.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2, 2};
  std::initializer_list<TypeParam> X_data{
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 1, 2, 3};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(std::numeric_limits<float>::quiet_NaN()),
      TypeParam(std::numeric_limits<float>::infinity()),
      TypeParam(-std::numeric_limits<float>::infinity()),
      TypeParam(std::numeric_limits<float>::infinity()),
      TypeParam(std::numeric_limits<float>::quiet_NaN()),
      TypeParam(-std::numeric_limits<float>::infinity())};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_reflection_align_corners_extreme) {
  // align_corners=1 on a non-degenerate (3x3) image. With align_corners=1 the
  // lower border becomes 0 (not -0.5), so unsafe coords are sanitized to (0, 0)
  // and resolve to the top-left pixel of the image.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{1});

  std::initializer_list<int64_t> X_shape{1, 1, 3, 3};
  std::initializer_list<TypeParam> X_data{
      TypeParam(1.0f), TypeParam(2.0f), TypeParam(3.0f),
      TypeParam(4.0f), TypeParam(5.0f), TypeParam(6.0f),
      TypeParam(7.0f), TypeParam(8.0f), TypeParam(9.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(1.0e+20f), TypeParam(1.0e+20f),
      TypeParam(std::numeric_limits<float>::quiet_NaN()),
      TypeParam(-std::numeric_limits<float>::infinity())};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  // Both unsafe coords sanitize to (0, 0) -> pixel(0, 0) = 1.0.
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_reflection_negative_only_extreme) {
  // Asymmetry: all extreme coordinates are negative. Sanitization replaces them
  // with x_min/y_min = -0.5, and nearbyint(-0.5) rounds to 0 (banker's rounding),
  // so each output samples pixel(0, 0) of a non-constant image.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 3, 3};
  std::initializer_list<TypeParam> X_data{
      TypeParam(1.0f), TypeParam(2.0f), TypeParam(3.0f),
      TypeParam(4.0f), TypeParam(5.0f), TypeParam(6.0f),
      TypeParam(7.0f), TypeParam(8.0f), TypeParam(9.0f)};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(-1.0e+20f), TypeParam(-1.0e+20f),
      TypeParam(-std::numeric_limits<float>::infinity()),
      TypeParam(-std::numeric_limits<float>::infinity())};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  // Sanitized to (-0.5, -0.5); nearbyint -> (0, 0); pixel(0, 0) = 1.0.
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_reflection_mixed_normal_pathological) {
  // Mixed normal and pathological grid coordinates in the same call. Validates
  // that the sanitization only replaces unsafe values and leaves normal grid
  // points untouched, sampling them correctly from a non-constant image.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{1});

  std::initializer_list<int64_t> X_shape{1, 1, 3, 3};
  std::initializer_list<TypeParam> X_data{
      TypeParam(1.0f), TypeParam(2.0f), TypeParam(3.0f),
      TypeParam(4.0f), TypeParam(5.0f), TypeParam(6.0f),
      TypeParam(7.0f), TypeParam(8.0f), TypeParam(9.0f)};

  // align_corners=1 on a 3x3 image maps normalized [-1, 1] -> pixel coords [0, 2].
  // Mix four points: center, top-left, NaN (sanitized -> (0,0)), and asymmetric
  // extreme (sanitized -> (0,0)).
  std::initializer_list<int64_t> Grid_shape{1, 1, 4, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f),    // -> pixel(1, 1) = 5
      TypeParam(-1.0f), TypeParam(-1.0f),  // -> pixel(0, 0) = 1
      TypeParam(std::numeric_limits<float>::quiet_NaN()),
      TypeParam(std::numeric_limits<float>::quiet_NaN()),  // sanitized -> pixel(0, 0) = 1
      TypeParam(1.0e+20f), TypeParam(-1.0e+20f)};          // sanitized -> pixel(0, 0) = 1

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 4};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape,
                            {TypeParam(5.0f), TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f)});
  RunCpuOnly(test);
}

// -----------------------------------------------------------------------------------------
// Non-empty input spatial-dimension validation tests: a zero-size spatial dim must be
// rejected before sampling (guard fires host-side across CPU/CUDA/WebGPU).
// -----------------------------------------------------------------------------------------
TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_border_empty_spatial_rejected) {
  // An input with a zero-size spatial dimension is rejected: the output is sized by the grid,
  // so a non-empty grid skips the empty-output early return, and spatial dimensions must be
  // non-empty for sampling to produce valid sample indices.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("border"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 0, 5};
  std::initializer_list<TypeParam> X_data{};
  std::initializer_list<int64_t> Grid_shape{1, 2, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f), TypeParam(-1.0f), TypeParam(-1.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(0.5f), TypeParam(-0.5f)};
  std::initializer_list<int64_t> Y_shape{1, 1, 2, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape,
                            {TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f)});
  // The zero-spatial-dim guard currently covers the CPU and CUDA kernels; other EPs (WebGPU/CoreML)
  // are out of scope for this test, so restrict the expect-failure run to CPU + CUDA only.
  RunTestsExpectFailure(test, "Input spatial dimensions must be non-empty for sampling",
                        GetCpuAndCudaExecutionProviders());
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_5D_nearest_border_empty_spatial_rejected) {
  // Same rejection as the 4-D case, but for a 5-D input with a zero-size spatial dimension. This keeps
  // the 5-D branch of the guard (and the CUDA NCHW/NHWC layouts) covered: the output is sized by the
  // grid, so a non-empty grid skips the empty-output early return, and spatial dimensions must be
  // non-empty for sampling to produce valid sample indices.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("border"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 0, 2, 2};
  std::initializer_list<TypeParam> X_data{};
  std::initializer_list<int64_t> Grid_shape{1, 1, 1, 2, 3};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f)};
  std::initializer_list<int64_t> Y_shape{1, 1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(0.0f), TypeParam(0.0f)});
  // Restrict the expect-failure run to CPU + CUDA only, matching the 4-D case above.
  RunTestsExpectFailure(test, "Input spatial dimensions must be non-empty for sampling",
                        GetCpuAndCudaExecutionProviders());
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_border_empty_last_spatial_rejected) {
  // Zero-size trailing spatial dimension (W = 0), confirming the guard loop catches a non-first
  // spatial dimension, not just the leading one. This runs on the CUDA NHWC provider as well: for a
  // logical NCHW {1, 1, 5, 0} input the internal NHWC layout transform places the zero at a spatial
  // index in the (N, H, W, C) layout, so it exercises the layout-aware spatial range on both kernels.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("border"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 5, 0};
  std::initializer_list<TypeParam> X_data{};
  std::initializer_list<int64_t> Grid_shape{1, 2, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f), TypeParam(-1.0f), TypeParam(-1.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(0.5f), TypeParam(-0.5f)};
  std::initializer_list<int64_t> Y_shape{1, 1, 2, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape,
                            {TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f)});
  RunTestsExpectFailure(test, "Input spatial dimensions must be non-empty for sampling",
                        GetCpuAndCudaExecutionProviders());
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_border_all_spatial_zero_rejected) {
  // Both spatial dimensions are zero ({1, 1, 0, 0}); the guard must reject on the first zero dimension
  // without double-reporting or crashing.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("border"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 0, 0};
  std::initializer_list<TypeParam> X_data{};
  std::initializer_list<int64_t> Grid_shape{1, 2, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f), TypeParam(-1.0f), TypeParam(-1.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(0.5f), TypeParam(-0.5f)};
  std::initializer_list<int64_t> Y_shape{1, 1, 2, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape,
                            {TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f)});
  RunTestsExpectFailure(test, "Input spatial dimensions must be non-empty for sampling",
                        GetCpuAndCudaExecutionProviders());
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_5D_nearest_border_middle_spatial_zero_rejected) {
  // 5-D input with a zero in a non-first spatial dimension ({1, 1, 2, 0, 3}), confirming the guard
  // spans the full spatial range of a 5-D tensor rather than only checking the first spatial index.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("border"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 0, 3};
  std::initializer_list<TypeParam> X_data{};
  std::initializer_list<int64_t> Grid_shape{1, 1, 1, 2, 3};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(1.0f)};
  std::initializer_list<int64_t> Y_shape{1, 1, 1, 1, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape, {TypeParam(0.0f), TypeParam(0.0f)});
  RunTestsExpectFailure(test, "Input spatial dimensions must be non-empty for sampling",
                        GetCpuAndCudaExecutionProviders());
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_linear_zeros_empty_spatial_rejected) {
  // The guard must fire before interpolation regardless of padding mode. This covers padding_mode
  // "zeros" (the mode where reads outside the image are otherwise silently treated as 0).
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("zeros"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 0, 5};
  std::initializer_list<TypeParam> X_data{};
  std::initializer_list<int64_t> Grid_shape{1, 2, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f), TypeParam(-1.0f), TypeParam(-1.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(0.5f), TypeParam(-0.5f)};
  std::initializer_list<int64_t> Y_shape{1, 1, 2, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape,
                            {TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f)});
  RunTestsExpectFailure(test, "Input spatial dimensions must be non-empty for sampling",
                        GetCpuAndCudaExecutionProviders());
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_linear_reflection_empty_spatial_rejected) {
  // Padding mode "reflection" is the most sensitive to a zero-size spatial dimension because the
  // reflect logic divides by (length - 1); the guard must reject the input before that computation.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 0, 5};
  std::initializer_list<TypeParam> X_data{};
  std::initializer_list<int64_t> Grid_shape{1, 2, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f), TypeParam(-1.0f), TypeParam(-1.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(0.5f), TypeParam(-0.5f)};
  std::initializer_list<int64_t> Y_shape{1, 1, 2, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape,
                            {TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f)});
  RunTestsExpectFailure(test, "Input spatial dimensions must be non-empty for sampling",
                        GetCpuAndCudaExecutionProviders());
}

TYPED_TEST(GridSampleCustomTest, test_grid_sample_20_4D_nearest_border_nonzero_spatial_accepted) {
  // Sanity check that the guard does not reject valid, non-empty spatial dimensions: a normal 2x2
  // input with align_corners=1 samples its four corners exactly and must succeed on both kernels.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("border"));
  test.AddAttribute("align_corners", int64_t{1});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<TypeParam> X_data{TypeParam(1.0f), TypeParam(2.0f), TypeParam(3.0f), TypeParam(4.0f)};
  std::initializer_list<int64_t> Grid_shape{1, 1, 4, 2};
  // align_corners=1 on a 2x2 image maps normalized [-1, 1] -> pixel coords [0, 1]; sample all corners.
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(-1.0f), TypeParam(-1.0f),  // -> pixel(row 0, col 0) = 1
      TypeParam(1.0f), TypeParam(-1.0f),   // -> pixel(row 0, col 1) = 2
      TypeParam(-1.0f), TypeParam(1.0f),   // -> pixel(row 1, col 0) = 3
      TypeParam(1.0f), TypeParam(1.0f)};   // -> pixel(row 1, col 1) = 4
  std::initializer_list<int64_t> Y_shape{1, 1, 1, 4};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape,
                            {TypeParam(1.0f), TypeParam(2.0f), TypeParam(3.0f), TypeParam(4.0f)});
  RunTests(test, GetCpuAndCudaExecutionProviders());
}

#ifdef USE_WEBGPU
TYPED_TEST(GridSampleCustomTest, test_grid_sample_16_4D_webgpu_empty_spatial_rejected) {
  // The WebGPU GridSample kernel is registered for opset 16-19 (NCHW, 4-D only) and now carries the
  // same non-empty spatial-dimension guard as the CPU and CUDA kernels. Exercise it directly on the
  // WebGPU provider with a zero-size spatial dimension; the guard rejects host-side before any shader
  // dispatch, so this validates the WebGPU path without depending on a particular GPU adapter.
  OpTester test("GridSample", 16);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("border"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 0, 5};
  std::initializer_list<TypeParam> X_data{};
  std::initializer_list<int64_t> Grid_shape{1, 2, 2, 2};
  std::initializer_list<TypeParam> Grid_data{
      TypeParam(0.0f), TypeParam(0.0f), TypeParam(-1.0f), TypeParam(-1.0f),
      TypeParam(1.0f), TypeParam(1.0f), TypeParam(0.5f), TypeParam(-0.5f)};
  std::initializer_list<int64_t> Y_shape{1, 1, 2, 2};

  test.AddInput<TypeParam>("X", X_shape, X_data);
  test.AddInput<TypeParam>("Grid", Grid_shape, Grid_data);
  test.AddOutput<TypeParam>("Y", Y_shape,
                            {TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f), TypeParam(0.0f)});

  std::vector<std::unique_ptr<IExecutionProvider>> execution_providers;
  execution_providers.push_back(DefaultWebGpuExecutionProvider());
  RunTestsExpectFailure(test, "Input spatial dimensions must be non-empty for sampling",
                        std::move(execution_providers));
}
#endif

// -----------------------------------------------------------------------------------------
// CUDA hardening regression tests.
//
// These mirror the coordinate-hardening cases above but also run on the CUDA execution provider (when
// built) to cover the equivalent float->int64 cast hardening in
// onnxruntime/core/providers/cuda/tensor/grid_sample_impl.cu. They are float-only because
// the CUDA GridSample kernel is registered for float only, and they use constant-valued
// images so the expected output is well-defined regardless of which in-range pixel each
// (now clamped) index resolves to.
// -----------------------------------------------------------------------------------------

TEST(GridSampleCudaHardeningTest, nearest_reflection_extreme_and_nan_coords) {
  // Exercises the CUDA _GridSampleKernel reflection path: GsReflect now guards NaN/Inf and
  // uses int64_t for the wrap count (1e10 exceeds INT_MAX), and PixelAtGrid clamps the
  // reflected index back into range.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<float> X_data{1.0f, 1.0f, 1.0f, 1.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  std::initializer_list<float> Grid_data{
      1.0e+10f, 1.0e+10f,
      std::numeric_limits<float>::quiet_NaN(), std::numeric_limits<float>::quiet_NaN()};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  test.AddOutput<float>("Y", Y_shape, {1.0f, 1.0f});
  RunCpuAndCuda(test);
}

TEST(GridSampleCudaHardeningTest, bilinear_reflection_infinity_coords) {
  // CUDA bilinear reflection path: the GsReflect finite guard and coordinate sanitization
  // keep the floor(...) cast well-defined for +/-Inf inputs.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<float> X_data{1.0f, 1.0f, 1.0f, 1.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  const float inf_val = std::numeric_limits<float>::infinity();
  std::initializer_list<float> Grid_data{
      inf_val, -inf_val,
      -inf_val, inf_val};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  test.AddOutput<float>("Y", Y_shape, {1.0f, 1.0f});
  RunCpuAndCuda(test);
}

TEST(GridSampleCudaHardeningTest, bilinear_border_nan_inf_extreme_coords) {
  // CUDA bilinear border path: coordinate sanitization keeps the floor(...) cast
  // well-defined before PixelAtGrid clamps border-padding samples into range.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("border"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<float> X_data{1.0f, 1.0f, 1.0f, 1.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 3, 2};
  std::initializer_list<float> Grid_data{
      std::numeric_limits<float>::quiet_NaN(), std::numeric_limits<float>::quiet_NaN(),
      std::numeric_limits<float>::infinity(), -std::numeric_limits<float>::infinity(),
      1.0e+20f, -1.0e+20f};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 3};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  test.AddOutput<float>("Y", Y_shape, {1.0f, 1.0f, 1.0f});
  RunCpuAndCuda(test);
}

TEST(GridSampleCudaHardeningTest, bilinear_zeros_nan_inf_extreme_coords) {
  // Zeros padding: the CUDA kernel's IsSafeForInt64Conversion sanitization substitutes the
  // lower border (-0.5) for NaN/Inf/extreme coordinates before the floor cast. Only the
  // bottom-right neighbor (pixel(0, 0) = 1.0) is in bounds with weight 0.5 * 0.5 = 0.25.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("zeros"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2};
  std::initializer_list<float> X_data{1.0f, 1.0f, 1.0f, 1.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 3, 2};
  std::initializer_list<float> Grid_data{
      std::numeric_limits<float>::quiet_NaN(), std::numeric_limits<float>::quiet_NaN(),
      std::numeric_limits<float>::infinity(), -std::numeric_limits<float>::infinity(),
      1.0e+20f, -1.0e+20f};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 3};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  test.AddOutput<float>("Y", Y_shape, {0.25f, 0.25f, 0.25f});
  RunCpuAndCuda(test);
}

TEST(GridSampleCudaHardeningTest, cubic_reflection_extreme_coords) {
  // CUDA bicubic path (4-D only): static_cast<int64_t>(std::floor(...)) - 1 is now
  // protected by the coordinate sanitization. Constant-valued image => 1.0.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("cubic"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 4, 4};
  std::initializer_list<float> X_data{
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 1, 2};
  std::initializer_list<float> Grid_data{1.0e+10f, -1.0e+10f};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 1};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  test.AddOutput<float>("Y", Y_shape, {1.0f});
  RunCpuAndCuda(test);
}

TEST(GridSampleCudaHardeningTest, nearest_reflection_dim1_align_corners) {
  // 1x1 image with align_corners=1 makes the reflection range zero (x_min == x_max), so
  // GsReflect must not divide by zero. The single input pixel is the only valid sample.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{1});

  std::initializer_list<int64_t> X_shape{1, 1, 1, 1};
  std::initializer_list<float> X_data{7.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 2, 2};
  std::initializer_list<float> Grid_data{
      0.5f, 0.5f,
      -0.5f, -0.5f};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 2};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  test.AddOutput<float>("Y", Y_shape, {7.0f, 7.0f});
  RunCpuAndCuda(test);
}

TEST(GridSampleCudaHardeningTest, nearest_reflection_5D_extreme_coords) {
  // CUDA _GridSampleKernel3D reflection path: PixelAtGrid3D received the same safety clamp
  // as PixelAtGrid. Constant-valued volume => 1.0.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("nearest"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2, 2};
  std::initializer_list<float> X_data{
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 1, 2, 3};
  std::initializer_list<float> Grid_data{
      1.0e+10f, 1.0e+10f, 1.0e+10f,
      -1.0e+10f, -1.0e+10f, -1.0e+10f};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 1, 2};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  test.AddOutput<float>("Y", Y_shape, {1.0f, 1.0f});
  RunCpuAndCuda(test);
}

TEST(GridSampleCudaHardeningTest, bilinear_reflection_5D_extreme_coords) {
  // CUDA 3D trilinear path: the x/y/z indices are computed via int64_t floor casts after
  // sanitization. Constant-valued volume => 1.0.
  OpTester test("GridSample", 20);
  test.AddAttribute("mode", std::string("linear"));
  test.AddAttribute("padding_mode", std::string("reflection"));
  test.AddAttribute("align_corners", int64_t{0});

  std::initializer_list<int64_t> X_shape{1, 1, 2, 2, 2};
  std::initializer_list<float> X_data{
      1.0f, 1.0f, 1.0f, 1.0f,
      1.0f, 1.0f, 1.0f, 1.0f};

  std::initializer_list<int64_t> Grid_shape{1, 1, 1, 2, 3};
  std::initializer_list<float> Grid_data{
      1.0e+20f, 1.0e+20f, 1.0e+20f,
      -1.0e+20f, -1.0e+20f, -1.0e+20f};

  std::initializer_list<int64_t> Y_shape{1, 1, 1, 1, 2};

  test.AddInput<float>("X", X_shape, X_data);
  test.AddInput<float>("Grid", Grid_shape, Grid_data);
  test.AddOutput<float>("Y", Y_shape, {1.0f, 1.0f});
  RunCpuAndCuda(test);
}

}  // namespace test
}  // namespace onnxruntime
