// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include "core/platform/posix/telemetry.h"
#include "core/platform/posix/device_id.h"
#include "core/platform/telemetry_environment.h"
#include "core/platform/telemetry_guid.h"
#include "core/platform/telemetry_redaction.h"

#ifdef __APPLE__
#include <TargetConditionals.h>
#endif

// 1DS SDK
#include <LogManagerProvider.hpp>
#include <ILogConfiguration.hpp>

#include <unistd.h>
#include <sys/resource.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <sys/types.h>
#endif

#if defined(__linux__) || defined(__ANDROID__)
#include <fstream>
#endif

#include <cctype>
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <iomanip>
#include <random>
#include <sstream>
#include <thread>

#include "core/common/common.h"
#include "core/common/logging/logging.h"
#include "core/common/status.h"
#include "onnxruntime_config.h"
// Optional compile-time tenant-token override, generated by CMake into the build tree (keeps an
// injected token off the compiler command line). See the tenant-token handling below.
#include "onnxruntime_telemetry_tenant_token.h"

// Optional caller-framework label provided at build time via -Donnxruntime_CALLER_FRAMEWORK
// (empty by default). Redistributors that embed ORT set it to attribute their telemetry, matching
// the Windows provider's frameworkName field.
#ifndef ORT_CALLER_FRAMEWORK
#define ORT_CALLER_FRAMEWORK ""
#endif

using namespace Microsoft::Applications::Events;

namespace onnxruntime {

// PosixTelemetry can be constructed during early Env initialization (before logging registers a
// default logger) and destroyed late at process exit, so only emit warnings when a default logger
// exists, to avoid touching a missing/destroyed LoggingManager.
#define ORT_TELEMETRY_WARN(stream_expr)                               \
  do {                                                                \
    if (::onnxruntime::logging::LoggingManager::HasDefaultLogger()) { \
      LOGS_DEFAULT(WARNING) << stream_expr;                           \
    }                                                                 \
  } while (0)

// Static member initialization
std::atomic<uint32_t> PosixTelemetry::global_register_count_{0};
std::mutex PosixTelemetry::global_mutex_;
std::shared_mutex PosixTelemetry::mutex_;
::Microsoft::Applications::Events::ILogManager* PosixTelemetry::log_manager_ = nullptr;
std::atomic<::Microsoft::Applications::Events::ILogger*> PosixTelemetry::logger_{nullptr};
std::unique_ptr<::Microsoft::Applications::Events::ILogConfiguration> PosixTelemetry::config_;
std::atomic<bool> PosixTelemetry::enabled_{true};
std::atomic<uint32_t> PosixTelemetry::projection_{0};
std::atomic<bool> PosixTelemetry::process_info_logged_{false};
std::atomic<uint32_t> PosixTelemetry::system_metrics_sample_counter_{0};

// Tenant token for 1DS telemetry ingestion. Official builds override it via the
// onnxruntime_TELEMETRY_TENANT_TOKEN CMake variable, written into the generated
// onnxruntime_telemetry_tenant_token.h (included above) — in the build tree, not on the compiler command
// line — so a production token never lands in source, compile_commands.json, or build logs. Otherwise the
// in-repo default below is used; the token is resolved at the point of use in Initialize().
#if !defined(ORT_TELEMETRY_TENANT_TOKEN)
namespace {

// Decode a base64-encoded string at runtime.
std::string DecodeBase64(const std::string& encoded) {
  auto DecodeChar = [](char c) -> int {
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a' + 26;
    if (c >= '0' && c <= '9') return c - '0' + 52;
    if (c == '+') return 62;
    if (c == '/') return 63;
    return -1;
  };

  std::string result;
  result.reserve(encoded.size() * 3 / 4);
  uint32_t accum = 0;
  int bits = 0;
  for (char c : encoded) {
    int val = DecodeChar(c);
    if (val < 0) continue;
    accum = (accum << 6) | static_cast<uint32_t>(val);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      result.push_back(static_cast<char>((accum >> bits) & 0xFF));
    }
  }
  return result;
}

// In-repo default 1DS ingestion token so anyone building ONNX Runtime themselves gets working telemetry
// by default. The token bytes are XOR'd with a fixed repeating key, then base64-encoded, so the raw token
// does not appear in a plain `strings` scan. To regenerate: XOR the token bytes with the repeating ASCII
// key below, then base64.
std::string GetToken() {
  static constexpr char kXorKey[] = "OnnxRuntime";
  constexpr size_t klen = sizeof(kXorKey) - 1;
  std::string decoded = DecodeBase64(
      "eg8KQWRGDBBdD1YuWl9JahRaTFhZVX4NDUhgRF9MXlhIegxYHGpFXxJEXVd/V0NMa0FXWVEOA3hDCxw3RFhCUF8Edl0NVWRMWEM=");
  for (size_t i = 0; i < decoded.size(); ++i) {
    decoded[i] = static_cast<char>(decoded[i] ^ kXorKey[i % klen]);
  }
  return decoded;
}

}  // namespace
#endif  // !defined(ORT_TELEMETRY_TENANT_TOKEN)

// Event priority mapping (1DS priorities)
enum class EventPriority {
  NORMAL = EventLatency_Normal,     // Most events
  HIGH = EventLatency_RealTime,     // RuntimeError
  CRITICAL = EventLatency_RealTime  // ProcessInfo, SessionCreation
};

// SystemMetrics is emitted from LogEvaluationStop, i.e. once per inference Run(), which is a hot
// path for small/high-frequency models. Sample it to bound the per-run getrusage() + event cost:
// the event is emitted on the first run and then once every kSystemMetricsSampleInterval runs.
constexpr uint32_t kSystemMetricsSampleInterval = 100;

// Helper class to build events with common properties
class EventBuilder {
 private:
  EventProperties props_;

 public:
  explicit EventBuilder(std::string event_name, EventPriority priority)
      : props_(std::move(event_name)) {
    // Set latency/priority
    props_.SetLatency(static_cast<EventLatency>(priority));

    // All ORT telemetry is required system metadata (no PII)
    props_.SetLevel(DIAG_LEVEL_REQUIRED);
  }

  EventBuilder& AddString(const char* key, const std::string& value) {
    if (!value.empty()) {
      props_.SetProperty(key, value);
    }
    return *this;
  }

  EventBuilder& AddInt32(const char* key, int32_t value) {
    props_.SetProperty(key, static_cast<int64_t>(value));
    return *this;
  }

  EventBuilder& AddInt64(const char* key, int64_t value) {
    props_.SetProperty(key, value);
    return *this;
  }

  EventBuilder& AddBool(const char* key, bool value) {
    props_.SetProperty(key, value);
    return *this;
  }

  EventBuilder& AddUInt32(const char* key, uint32_t value) {
    props_.SetProperty(key, static_cast<int64_t>(value));
    return *this;
  }

  EventBuilder& AddDouble(const char* key, double value) {
    props_.SetProperty(key, value);
    return *this;
  }

  // Helper for vector to comma-separated string
  EventBuilder& AddStringList(const char* key, const std::vector<std::string>& vec) {
    if (!vec.empty()) {
      std::string result;
      for (size_t i = 0; i < vec.size(); ++i) {
        if (i > 0) result += ',';
        result += vec[i];
      }
      props_.SetProperty(key, result);
    }
    return *this;
  }

  // Helper for map to key=value,key=value format
  EventBuilder& AddIntMap(const char* key, const std::unordered_map<std::string, int>& map) {
    if (!map.empty()) {
      std::string result;
      bool first = true;
      for (const auto& [k, v] : map) {
        if (!first) result += ',';
        result += k + '=' + std::to_string(v);
        first = false;
      }
      props_.SetProperty(key, result);
    }
    return *this;
  }

  // Helper for string map
  EventBuilder& AddStringMap(const char* key, const std::unordered_map<std::string, std::string>& map) {
    if (!map.empty()) {
      std::string result;
      bool first = true;
      for (const auto& [k, v] : map) {
        if (!first) result += ',';
        result += k + '=' + v;
        first = false;
      }
      props_.SetProperty(key, result);
    }
    return *this;
  }

  // Helper for batch size duration map
  EventBuilder& AddBatchSizeDurations(const std::unordered_map<int64_t, long long>& durations) {
    for (const auto& [batch_size, duration] : durations) {
      std::string key = "batchSize_" + std::to_string(batch_size);
      props_.SetProperty(key, static_cast<int64_t>(duration));
    }
    return *this;
  }

  EventProperties Build() { return std::move(props_); }
};

// Hash a device ID with a stable, platform-independent algorithm (FNV-1a 64-bit) and format as
// fixed-width hex, so the same device maps to the same anonymized id across runs and platforms.
// std::hash is implementation-defined (and may be process-salted), so it is unsuitable here.
// Ensures raw device identifiers are never sent over the wire.
[[maybe_unused]] static std::string HashDeviceId(const std::string& id) {
  uint64_t hash = 14695981039346656037ULL;  // FNV-1a offset basis
  for (unsigned char c : id) {
    hash ^= static_cast<uint64_t>(c);
    hash *= 1099511628211ULL;  // FNV-1a prime
  }
  std::ostringstream oss;
  oss << std::hex << std::setfill('0') << std::setw(16) << hash;
  return oss.str();
}

namespace {

const std::string& GetAppSessionGuid() {
  static const std::string guid = GenerateGuidV4();
  return guid;
}

int64_t GetProcessorCount() {
  auto n = sysconf(_SC_NPROCESSORS_ONLN);
  return n > 0 ? static_cast<int64_t>(n) : 0;
}

}  // namespace

PosixTelemetry::PosixTelemetry() {
  std::lock_guard<std::mutex> lock(global_mutex_);

  // Always increment so destructor pairing is symmetric
  global_register_count_++;

  if (global_register_count_ == 1) {
    ORT_TRY {
      Initialize();
    }
    ORT_CATCH(const std::exception& ex) {
      // Telemetry failures should not break application functionality.
      ORT_HANDLE_EXCEPTION([&]() {
        ORT_TELEMETRY_WARN("Failed to initialize telemetry: " << ex.what());
      });
    }
  }
}

PosixTelemetry::~PosixTelemetry() {
  std::lock_guard<std::mutex> lock(global_mutex_);

  global_register_count_--;
  if (global_register_count_ == 0) {
    ORT_TRY {
      Shutdown();
    }
    ORT_CATCH(const std::exception& ex) {
      // Don't throw from a destructor.
      ORT_HANDLE_EXCEPTION([&]() {
        ORT_TELEMETRY_WARN("Error during telemetry shutdown: " << ex.what());
      });
    }
  }
}

void PosixTelemetry::LogEventAsync(Microsoft::Applications::Events::EventProperties&& props) const {
  // Hold a shared (reader) lock for the duration of the LogEvent call so the logger and its owning
  // log manager cannot be torn down underneath us: Initialize()/Shutdown() take this lock
  // exclusively. The shared lock still allows multiple threads to log concurrently.
  std::shared_lock<std::shared_mutex> lock(mutex_);
  auto* logger = logger_.load(std::memory_order_acquire);
  if (logger == nullptr) {
    return;
  }
  ORT_TRY {
    logger->LogEvent(std::move(props));
  }
  ORT_CATCH(const std::exception& ex) {
    ORT_HANDLE_EXCEPTION([&]() {
      ORT_TELEMETRY_WARN("[Telemetry] Failed to log event: " << ex.what());
    });
  }
}

void PosixTelemetry::Initialize() {
  std::unique_lock<std::shared_mutex> lock(mutex_);

  // In a CI / build-pipeline environment, or inside ORT's own unit-test binaries, collect nothing at
  // all: skip creating the 1DS uploader entirely so no events (not even ProcessInfo) are emitted and
  // no device id is written.
  if (IsRunningInCI() || IsRunningUnitTests()) {
    enabled_.store(false, std::memory_order_release);
    return;
  }

  // ORT_TELEMETRY_DISABLED suppresses the usage events but still creates the uploader, so the one-shot
  // ProcessInfo event is still emitted. DisableTelemetryEvents() behaves the same way at runtime.
  if (IsTelemetryDisabledByEnvVar()) {
    enabled_.store(false, std::memory_order_release);
  }

  // NOTE: On Android, the Java layer must be initialized before calling this:
  //   System.loadLibrary("maesdk");
  //   new HttpClient(getApplicationContext());
  //   OfflineRoom.connectContext(getApplicationContext());  // if using Room DB
  // See cpp_client_telemetry/docs/cpp-start-android.md for details.

  // Create SDK configuration — stored as member because LogManagerImpl holds a reference
  // and the configuration must remain valid for the lifetime of the log manager.
  config_ = std::make_unique<ILogConfiguration>();
  auto& config = *config_;

  config[CFG_STR_COLLECTOR_URL] = "https://mobile.events.data.microsoft.com/OneCollector/1.0";
  config[CFG_INT_TRACE_LEVEL_MASK] = 0;                      // Disable SDK internal logging
  config[CFG_INT_SDK_MODE] = SdkModeTypes::SdkModeTypes_CS;  // Common Schema 4.0 mode
  // Do not block process teardown to upload; persisted events are sent on the next run. 0 keeps
  // Shutdown non-blocking and avoids adding exit latency to host apps.
  config[CFG_INT_MAX_TEARDOWN_TIME] = 0;

  // Configure cache for offline scenarios — use same directory as device ID storage
  {
    std::string cache_dir = DeviceId::EnsureStorageDirectory();
    if (!cache_dir.empty()) {
      std::string cache_path = cache_dir + "/onnxruntime.db";
      config[CFG_STR_CACHE_FILE_PATH] = cache_path;
    }
  }

  // Configure RAM queue for async batching
  config[CFG_INT_RAM_QUEUE_SIZE] = 512 * 1024;  // 512KB RAM queue

  // Create log manager via LogManagerProvider (recommended for production use,
  // per LogManager_Creation_and_Lifecycle_Management.md).
  status_t status;
  log_manager_ = LogManagerProvider::CreateLogManager("OnnxRuntime", true, *config_, status);
  if (status != STATUS_SUCCESS || !log_manager_) {
    ORT_TELEMETRY_WARN("Failed to create telemetry LogManager, status: " << status);
    // CreateLogManager can return a live manager alongside a non-success status; release it (and
    // drop our reference) before destroying config_, which the manager holds a reference to.
    if (log_manager_ != nullptr) {
      LogManagerProvider::Release(*config_);
      log_manager_ = nullptr;
    }
    config_.reset();
    return;
  }

  // Get logger for our tenant: an official build's override from the generated header
  // (ORT_TELEMETRY_TENANT_TOKEN) if present, otherwise the in-repo default.
#if defined(ORT_TELEMETRY_TENANT_TOKEN)
  const std::string tenant_token = ORT_TELEMETRY_TENANT_TOKEN;
#else
  const std::string tenant_token = GetToken();
#endif
  auto* logger = log_manager_->GetLogger(tenant_token.c_str());
  if (logger == nullptr) {
    ORT_TELEMETRY_WARN("Failed to get telemetry logger");
    LogManagerProvider::Release(*config_);
    log_manager_ = nullptr;
    config_.reset();
    return;
  }

  // Use BEST_EFFORT transmit profile to minimize battery and network impact.
  // Events are batched and uploaded at a lower cadence.
  log_manager_->SetTransmitProfile(TransmitProfile_BestEffort);

  // Device ID.
#if defined(__ANDROID__) || (defined(__APPLE__) && TARGET_OS_IOS)
  // Mobile (Android/iOS): leave the device ID to the 1DS SDK, which uses the platform's own
  // identifier (identifierForVendor on iOS, ANDROID_ID on Android). Do not override it.
#else
  // Desktop: send a hashed version of our persistent UUID (the "c:" prefix marks it as a
  // caller-supplied identifier); the raw UUID itself is never transmitted.
  std::string raw_device_id = DeviceId::Instance().GetValue();
  if (!raw_device_id.empty()) {
    log_manager_->GetSemanticContext().SetDeviceId("c:" + HashDeviceId(raw_device_id));
  }
#endif

  // Set application information as logger context (attached to all events)
  logger->SetContext("AppName", "ONNXRuntime");
  logger->SetContext("AppVersion", ORT_VERSION);
  logger->SetContext("Platform", GetPlatformInfo());
  logger->SetContext("AppSessionGuid", GetAppSessionGuid());
  logger->SetContext("cpuModel", GetCpuModel());
  logger->SetContext("processorCount", GetProcessorCount());
  logger->SetContext("totalMemoryMB", GetTotalMemoryMB());

  // Caller-framework label from the build-time ORT_CALLER_FRAMEWORK option; only stamped when a
  // redistributor sets it, so standard builds add nothing. Matches the Windows provider's field.
  if (std::string framework = ORT_CALLER_FRAMEWORK; !framework.empty()) {
    logger->SetContext("frameworkName", framework);
  }

  // Publish the fully-configured logger atomically; concurrent readers observe it only now.
  // enabled_ is left to its default / the runtime EnableTelemetryEvents()/DisableTelemetryEvents()
  // opt-in state rather than being force-set here.
  logger_.store(logger, std::memory_order_release);
}

void PosixTelemetry::Shutdown() {
  std::unique_lock<std::shared_mutex> lock(mutex_);

  // Clear the logger so concurrent LogEventAsync() readers (which take the shared lock) observe
  // nullptr and skip. enabled_ is intentionally left untouched: it reflects the user's
  // EnableTelemetryEvents()/DisableTelemetryEvents() opt-in state, so a later Initialize() (e.g. in
  // tests or dynamic load/unload of the last instance) can resume telemetry without a forced re-enable.
  logger_ = nullptr;  // Owned by log_manager_, will be destroyed with it

  if (log_manager_ && config_) {
    // Per SDK use-after-free docs (use-after-free.md):
    // Flush() must be called before FlushAndTeardown() to ensure all pending
    // events are persisted to offline storage. FlushAndTeardown() internally
    // calls PauseActivity() + WaitPause() to quiesce the SDK.
    log_manager_->Flush();
    log_manager_->FlushAndTeardown();

    // Release the log manager instance via LogManagerProvider
    LogManagerProvider::Release(*config_);
    log_manager_ = nullptr;
    config_.reset();
  }
}

std::string PosixTelemetry::GetPlatformInfo() const {
#if defined(__APPLE__)
#if TARGET_OS_IOS
  return "iOS";
#elif TARGET_OS_MAC
  return "macOS";
#else
  return "Apple";
#endif
#elif defined(__ANDROID__)
  return "Android";
#elif defined(__linux__)
  return "Linux";
#else
  return "Unknown";
#endif
}

// ---------------------------------------------------------------------------
// Process / system info helpers for LogProcessInfo
// ---------------------------------------------------------------------------

// Get detailed OS version string (e.g., "macOS 15.2", "Ubuntu 22.04 LTS")
std::string PosixTelemetry::GetOsDescription() const {
#if defined(__APPLE__)
  char version[64] = {};
  size_t len = sizeof(version);
  if (sysctlbyname("kern.osproductversion", version, &len, nullptr, 0) == 0) {
#if TARGET_OS_IOS
    return std::string("iOS ") + version;
#else
    return std::string("macOS ") + version;
#endif
  }
  return GetPlatformInfo();

#elif defined(__ANDROID__)
  // Read Android system properties via /system/build.prop
  std::string release, sdk;
  std::ifstream prop("/system/build.prop");
  if (prop.is_open()) {
    std::string line;
    while (std::getline(prop, line)) {
      if (line.rfind("ro.build.version.release=", 0) == 0)
        release = line.substr(25);
      else if (line.rfind("ro.build.version.sdk=", 0) == 0)
        sdk = line.substr(21);
    }
  }
  if (!release.empty()) {
    std::string result = "Android " + release;
    if (!sdk.empty()) result += " (API " + sdk + ")";
    return result;
  }
  return "Android";

#elif defined(__linux__)
  // Parse /etc/os-release for PRETTY_NAME (e.g., "Ubuntu 22.04.3 LTS")
  std::ifstream os_release("/etc/os-release");
  if (os_release.is_open()) {
    std::string line;
    while (std::getline(os_release, line)) {
      if (line.rfind("PRETTY_NAME=", 0) == 0) {
        std::string value = line.substr(12);
        if (value.size() >= 2 && value.front() == '"' && value.back() == '"') {
          value = value.substr(1, value.size() - 2);
        }
        return value;
      }
    }
  }
  return "Linux";

#else
  return "Unknown";
#endif
}

// Get the name of the current process
std::string PosixTelemetry::GetProcessName() const {
#if defined(__APPLE__) || defined(__FreeBSD__)
  const char* name = getprogname();
  return name ? name : "";

#elif defined(__linux__) || defined(__ANDROID__)
  // /proc/self/cmdline holds the full null-separated argv; argv[0]'s basename is the executable
  // name and is not truncated (unlike /proc/self/comm, which caps the name at 15 characters).
  {
    std::ifstream cmdline("/proc/self/cmdline", std::ios::binary);
    if (cmdline.is_open()) {
      std::string arg0;
      std::getline(cmdline, arg0, '\0');
      if (!arg0.empty()) {
        const size_t slash = arg0.find_last_of('/');
        return slash == std::string::npos ? arg0 : arg0.substr(slash + 1);
      }
    }
  }
  // Fallback to /proc/self/comm (process name, capped at 15 characters).
  {
    std::ifstream comm("/proc/self/comm");
    if (comm.is_open()) {
      std::string name;
      std::getline(comm, name);
      while (!name.empty() && (name.back() == '\n' || name.back() == '\r'))
        name.pop_back();
      return name;
    }
  }
  return "";

#else
  return "";
#endif
}

// Get the CPU brand string (e.g. "Intel(R) Core(TM) i7-10700K"). Empty when unavailable.
std::string PosixTelemetry::GetCpuModel() const {
#if defined(__APPLE__)
  // macOS/iOS expose the CPU brand string via sysctl.
  char buf[256] = {0};
  size_t size = sizeof(buf);
  if (sysctlbyname("machdep.cpu.brand_string", buf, &size, nullptr, 0) == 0) {
    return std::string(buf);
  }
  return "";

#elif defined(__linux__) || defined(__ANDROID__)
  // /proc/cpuinfo exposes the CPU brand as "model name" (x86) or "Hardware" (ARM).
  std::ifstream cpuinfo("/proc/cpuinfo");
  std::string line;
  std::string hardware;
  while (std::getline(cpuinfo, line)) {
    const size_t colon = line.find(':');
    if (colon == std::string::npos) {
      continue;
    }
    std::string key = line.substr(0, colon);
    while (!key.empty() && std::isspace(static_cast<unsigned char>(key.back()))) {
      key.pop_back();
    }
    std::string value = line.substr(colon + 1);
    const size_t start = value.find_first_not_of(" \t");
    value = (start == std::string::npos) ? std::string() : value.substr(start);
    if (key == "model name") {
      return value;
    }
    if (hardware.empty() && key == "Hardware") {
      hardware = value;
    }
  }
  return hardware;

#else
  return "";
#endif
}

// Coarse device class for the host: "Mobile" on Android/iOS, "Desktop" elsewhere.
std::string PosixTelemetry::GetDeviceClass() const {
#if defined(__ANDROID__) || (defined(__APPLE__) && TARGET_OS_IOS)
  return "Mobile";
#else
  return "Desktop";
#endif
}

// Get the CPU architecture the binary was compiled for
std::string PosixTelemetry::GetArchitecture() {
#if defined(__x86_64__)
  return "x86_64";
#elif defined(__i386__)
  return "x86";
#elif defined(__aarch64__)
  return "arm64";
#elif defined(__arm__)
  return "arm";
#elif defined(__riscv)
  return "riscv";
#elif defined(__wasm__)
  return "wasm";
#else
  return "unknown";
#endif
}

// Get total physical memory in MB
int64_t PosixTelemetry::GetTotalMemoryMB() {
#if defined(__APPLE__)
  int64_t mem = 0;
  size_t len = sizeof(mem);
  if (sysctlbyname("hw.memsize", &mem, &len, nullptr, 0) == 0) {
    return mem / (1024 * 1024);
  }
  return -1;

#elif defined(__linux__) || defined(__ANDROID__)
  long pages = sysconf(_SC_PHYS_PAGES);
  long page_size = sysconf(_SC_PAGE_SIZE);
  if (pages > 0 && page_size > 0) {
    return static_cast<int64_t>(pages) * page_size / (1024 * 1024);
  }
  return -1;

#else
  return -1;
#endif
}

void PosixTelemetry::EnableTelemetryEvents() const {
  enabled_ = true;
}

void PosixTelemetry::DisableTelemetryEvents() const {
  enabled_ = false;
}

void PosixTelemetry::SetLanguageProjection(uint32_t projection) const {
  projection_ = projection;
}

bool PosixTelemetry::IsEnabled() const {
  // Reflect actual readiness: the opt-out flag AND a successfully-initialized logger.
  return enabled_.load(std::memory_order_acquire) && logger_.load(std::memory_order_acquire) != nullptr;
}

unsigned char PosixTelemetry::Level() const {
  // POSIX telemetry has no ETW-style level/keyword control plane; report zero.
  return 0;
}

uint64_t PosixTelemetry::Keyword() const {
  return 0;
}

void PosixTelemetry::LogProcessInfo() const {
  // ProcessInfo fires whenever telemetry is initialized (i.e. not in a CI build), even when the usage
  // events are disabled via ORT_TELEMETRY_DISABLED or DisableTelemetryEvents(). It only needs a live
  // logger; CI suppression already prevents one from being created.
  if (logger_.load(std::memory_order_acquire) == nullptr) {
    return;
  }

  // Log process info only once
  if (process_info_logged_.exchange(true)) {
    return;
  }

  auto builder = EventBuilder("ProcessInfo", EventPriority::CRITICAL)
                     .AddString("runtimeVersion", ORT_VERSION)
#if defined(__ANDROID__) || (defined(__APPLE__) && TARGET_OS_IOS)
                     .AddString("DeviceInfo.Status", "Mobile")
#else
                     .AddString("DeviceInfo.Status", DeviceId::Instance().GetStatusString())
#endif
                     .AddString("osDescription", GetOsDescription())
                     .AddString("processName", GetProcessName())
                     .AddString("architecture", GetArchitecture())
                     .AddString("cpuModel", GetCpuModel())
                     .AddString("deviceClass", GetDeviceClass())
                     .AddInt32("cpuCount", static_cast<int32_t>(std::thread::hardware_concurrency()))
                     .AddInt64("totalMemoryMB", GetTotalMemoryMB());

  LogEventAsync(builder.Build());
}

void PosixTelemetry::LogSessionCreationStart(uint32_t session_id) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("SessionCreationStart", EventPriority::CRITICAL)
                   .AddUInt32("sessionId", session_id)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogEvaluationStop(uint32_t session_id) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("EvaluationStop", EventPriority::NORMAL)
                   .AddUInt32("sessionId", session_id)
                   .Build();

  LogEventAsync(std::move(event));

  // Capture system metrics after each inference run to observe impact
  LogSystemMetrics(session_id);
}

void PosixTelemetry::LogEvaluationStart(uint32_t session_id) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("EvaluationStart", EventPriority::NORMAL)
                   .AddUInt32("sessionId", session_id)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogSessionCreation(
    uint32_t session_id, int64_t ir_version,
    const std::string& model_producer_name,
    const std::string& model_producer_version,
    const std::string& model_domain,
    const std::unordered_map<std::string, int>& domain_to_version_map,
    const std::string& model_file_name,
    const std::string& model_graph_name,
    const std::string& model_weight_type,
    const std::string& model_graph_hash,
    const std::string& model_weight_hash,
    const std::unordered_map<std::string, std::string>& model_metadata,
    const std::string& loadedFrom,
    const std::vector<std::string>& execution_provider_ids,
    const std::string& hardware_device_types,
    const std::string& hardware_vendor_ids,
    const std::string& ep_versions,
    bool use_fp16, bool captureState) const {
  if (!IsEnabled()) {
    return;
  }

  // captureState is currently only triggered on Windows via ETW's EVENT_CONTROL_CODE_CAPTURE_STATE callback
  // (LogAllSessions). Kept here for future compatibility if a similar mechanism is added for POSIX.
  std::string event_name = captureState ? "SessionCreation_CaptureState" : "SessionCreation";

  auto builder = EventBuilder(std::move(event_name), EventPriority::CRITICAL)
                     .AddUInt32("sessionId", session_id)
                     .AddInt64("irVersion", ir_version)
                     .AddUInt32("OrtProgrammingProjection", projection_.load())
                     .AddString("modelProducerName", model_producer_name)
                     .AddString("modelProducerVersion", model_producer_version)
                     .AddString("modelDomain", model_domain)
                     .AddIntMap("domainToVersionMap", domain_to_version_map)
                     .AddString("modelFileName", model_file_name)
                     .AddString("modelGraphName", model_graph_name)
                     .AddString("modelWeightType", model_weight_type)
                     .AddString("modelGraphHash", model_graph_hash)
                     .AddString("modelWeightHash", model_weight_hash)
                     .AddStringMap("modelMetaData", model_metadata)
                     .AddString("loadedFrom", loadedFrom)
                     .AddStringList("executionProviderIds", execution_provider_ids)
                     .AddString("hardwareDeviceTypes", hardware_device_types)
                     .AddString("hardwareVendorIds", hardware_vendor_ids)
                     .AddString("executionProviderVersions", ep_versions)
                     .AddBool("usefp16", use_fp16);

  LogEventAsync(builder.Build());
}

void PosixTelemetry::LogCompileModelStart(
    uint32_t session_id,
    const std::string& input_source,
    const std::string& output_target,
    uint32_t flags,
    int graph_optimization_level,
    bool embed_ep_context,
    bool has_external_initializers_file,
    const std::vector<std::string>& execution_provider_ids) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("CompileModelStart", EventPriority::NORMAL)
                   .AddUInt32("sessionId", session_id)
                   .AddString("inputSource", input_source)
                   .AddString("outputTarget", output_target)
                   .AddUInt32("flags", flags)
                   .AddInt32("graphOptimizationLevel", graph_optimization_level)
                   .AddBool("embedEpContext", embed_ep_context)
                   .AddBool("hasExternalInitializersFile", has_external_initializers_file)
                   .AddStringList("executionProviderIds", execution_provider_ids)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogCompileModelComplete(
    uint32_t session_id,
    bool success,
    uint32_t error_code,
    uint32_t error_category,
    const std::string& error_message) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("CompileModelComplete", EventPriority::NORMAL)
                   .AddUInt32("sessionId", session_id)
                   .AddBool("success", success)
                   .AddUInt32("errorCode", error_code)
                   .AddUInt32("errorCategory", error_category)
                   .AddString("errorMessage", ScrubStringForTelemetry(error_message))
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogRuntimeError(
    uint32_t session_id, const common::Status& status,
    const char* file, const char* function, uint32_t line) const {
  if (!IsEnabled()) {
    return;
  }

  // __FILE__ may be an absolute build path that embeds developer/build directory names; emit only
  // the basename so remote telemetry doesn't leak usernames or local paths.
  std::string_view file_view = file ? std::string_view{file} : std::string_view{};
  if (const size_t slash = file_view.find_last_of('/'); slash != std::string_view::npos) {
    file_view.remove_prefix(slash + 1);
  }

  auto event = EventBuilder("RuntimeError", EventPriority::HIGH)
                   .AddUInt32("sessionId", session_id)
                   .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                   .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                   .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                   .AddString("file", std::string(file_view))
                   .AddString("function", function ? function : "")
                   .AddUInt32("line", line)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogRuntimeInferenceError(uint32_t session_id, const common::Status& status,
                                              const std::string& ep_versions,
                                              const std::string& ep_device_types) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("RuntimeInferenceError", EventPriority::HIGH)
                   .AddUInt32("sessionId", session_id)
                   .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                   .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                   .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                   .AddString("executionProviderVersions", ep_versions)
                   .AddString("executionProviderDeviceTypes", ep_device_types)
                   .AddString("runtimeVersion", ORT_VERSION)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogRuntimePerf(
    uint32_t session_id, uint32_t total_runs_since_last,
    int64_t total_run_duration_since_last,
    const std::unordered_map<int64_t, long long>& duration_per_batch_size) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("RuntimePerf", EventPriority::NORMAL)
                   .AddUInt32("sessionId", session_id)
                   .AddUInt32("totalRuns", total_runs_since_last)
                   .AddInt64("totalRunDuration", total_run_duration_since_last)
                   .AddBatchSizeDurations(duration_per_batch_size)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogExecutionProviderEvent(LUID* adapterLuid) const {
  // Not applicable for non-Windows platforms (LUID is Windows-specific)
  (void)adapterLuid;
}

void PosixTelemetry::LogDriverInfoEvent(
    const std::string_view device_class,
    const std::wstring_view& driver_names,
    const std::wstring_view& driver_versions) const {
  // Not applicable for non-Windows platforms
  (void)device_class;
  (void)driver_names;
  (void)driver_versions;
}

void PosixTelemetry::LogAutoEpSelection(
    uint32_t session_id, const std::string& selection_policy,
    const std::vector<std::string>& requested_execution_provider_ids,
    const std::vector<std::string>& available_execution_provider_ids) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("EpAutoSelection", EventPriority::NORMAL)
                   .AddUInt32("sessionId", session_id)
                   .AddString("selectionPolicy", selection_policy)
                   .AddStringList("requestedExecutionProviderIds", requested_execution_provider_ids)
                   .AddStringList("availableExecutionProviderIds", available_execution_provider_ids)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogProviderOptions(
    const std::string& provider_id,
    const std::string& provider_options_string,
    bool captureState) const {
  if (!IsEnabled()) {
    return;
  }

  std::string event_name = captureState ? "ProviderOptions_CaptureState" : "ProviderOptions";

  auto event = EventBuilder(std::move(event_name), EventPriority::NORMAL)
                   .AddString("providerId", provider_id)
                   .AddString("providerOptions", provider_options_string)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogModelLoadStart(uint32_t session_id) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("ModelLoadStart", EventPriority::NORMAL)
                   .AddUInt32("sessionId", session_id)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogModelLoadEnd(uint32_t session_id, const common::Status& status) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("ModelLoadEnd", EventPriority::NORMAL)
                   .AddUInt32("sessionId", session_id)
                   .AddBool("isSuccess", status.IsOK())
                   .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                   .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                   .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogSessionCreationEnd(uint32_t session_id, const common::Status& status) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("SessionCreationEnd", EventPriority::CRITICAL)
                   .AddUInt32("sessionId", session_id)
                   .AddBool("isSuccess", status.IsOK())
                   .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                   .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                   .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogEpDeviceUsage(
    uint32_t session_id,
    const std::string& ep_type,
    const std::string& hardware_device_type,
    uint32_t hardware_vendor_id,
    uint32_t hardware_device_id,
    const std::string& hardware_vendor,
    const std::string& ep_vendor,
    const std::string& ep_version,
    int assigned_node_count,
    uint32_t total_runs_since_last,
    int64_t total_run_duration_since_last) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("EpDeviceUsage", EventPriority::NORMAL)
                   .AddUInt32("sessionId", session_id)
                   .AddString("executionProviderType", ep_type)
                   .AddString("hardwareDeviceType", hardware_device_type)
                   .AddUInt32("hardwareVendorId", hardware_vendor_id)
                   .AddUInt32("hardwareDeviceId", hardware_device_id)
                   .AddString("hardwareVendor", hardware_vendor)
                   .AddString("epVendor", ep_vendor)
                   .AddString("epVersion", ep_version)
                   .AddInt32("assignedNodeCount", assigned_node_count)
                   .AddUInt32("totalRunsSinceLast", total_runs_since_last)
                   .AddInt64("totalRunDurationSinceLast", total_run_duration_since_last)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogRegisterEpLibraryStart(const std::string& registration_name) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("RegisterEpLibraryStart", EventPriority::NORMAL)
                   .AddString("registrationName", registration_name)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogRegisterEpLibraryEnd(const std::string& registration_name,
                                             const common::Status& status) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("RegisterEpLibraryEnd", EventPriority::NORMAL)
                   .AddString("registrationName", registration_name)
                   .AddBool("isSuccess", status.IsOK())
                   .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                   .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                   .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogRegisterEpLibraryWithLibPath(const std::string& registration_name,
                                                     const std::string& lib_path) const {
  if (!IsEnabled()) {
    return;
  }

  auto event = EventBuilder("RegisterEpLibraryWithLibPath", EventPriority::NORMAL)
                   .AddString("registrationName", registration_name)
                   .AddString("libPath", lib_path)
                   .Build();

  LogEventAsync(std::move(event));
}

void PosixTelemetry::LogSystemMetrics(uint32_t session_id) const {
  if (!IsEnabled()) {
    return;
  }

  // Sample to bound per-inference overhead: emit on the first run and every
  // kSystemMetricsSampleInterval-th run thereafter. fetch_add returns the previous value, so the
  // first call (0) passes and the getrusage() syscall below is skipped on non-sampled runs.
  if ((system_metrics_sample_counter_.fetch_add(1, std::memory_order_relaxed) % kSystemMetricsSampleInterval) != 0) {
    return;
  }

  struct rusage usage;
  if (getrusage(RUSAGE_SELF, &usage) == 0) {
    // ru_maxrss is in KB on Linux, bytes on macOS
#ifdef __APPLE__
    int64_t max_rss_kb = usage.ru_maxrss / 1024;
#else
    int64_t max_rss_kb = usage.ru_maxrss;
#endif

    auto event = EventBuilder("SystemMetrics", EventPriority::NORMAL)
                     .AddUInt32("sessionId", session_id)
                     .AddInt64("maxRssKb", max_rss_kb)
                     .AddInt64("userCpuTimeSec", usage.ru_utime.tv_sec)
                     .AddInt64("userCpuTimeUsec", usage.ru_utime.tv_usec)
                     .AddInt64("systemCpuTimeSec", usage.ru_stime.tv_sec)
                     .AddInt64("systemCpuTimeUsec", usage.ru_stime.tv_usec)
                     .AddInt64("minorPageFaults", usage.ru_minflt)
                     .AddInt64("majorPageFaults", usage.ru_majflt)
                     .AddInt64("voluntaryContextSwitches", usage.ru_nvcsw)
                     .AddInt64("involuntaryContextSwitches", usage.ru_nivcsw)
                     .Build();

    LogEventAsync(std::move(event));
  }
}

}  // namespace onnxruntime
