// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include "core/platform/posix/telemetry.h"
#include "core/platform/posix/device_id.h"
#include "core/platform/posix/telemetry_no_throw.h"
#include "core/platform/posix/telemetry_sampling.h"
#include "core/platform/telemetry_environment.h"
#include "core/platform/telemetry_guid.h"
#include "core/platform/telemetry_redaction.h"

#ifdef __APPLE__
#include <TargetConditionals.h>
#endif

// 1DS SDK
#include <LogManagerProvider.hpp>
#include <ILogConfiguration.hpp>
#if defined(__ANDROID__)
#include "http/HttpClient_Android.hpp"
#endif

#include <unistd.h>
#include <sys/resource.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <sys/types.h>
#endif

#if defined(__linux__) || defined(__ANDROID__)
#include <fstream>
#endif

#include <cctype>
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <iomanip>
#include <limits>
#include <random>
#include <sstream>
#include <string_view>
#include <utility>

#include "core/common/common.h"
#include "core/common/logging/logging.h"
#include "core/common/status.h"
#include "onnxruntime_config.h"
// Optional compile-time tenant-token override, generated by CMake into the build tree (keeps an
// injected token off the compiler command line). See the tenant-token handling below.
#include "onnxruntime_telemetry_tenant_token.h"

// Optional caller-framework label provided at build time via -Donnxruntime_CALLER_FRAMEWORK
// (empty by default). Redistributors that embed ORT set it to attribute their telemetry, matching
// the Windows provider's frameworkName field.
#ifndef ORT_CALLER_FRAMEWORK
#define ORT_CALLER_FRAMEWORK ""
#endif

using namespace Microsoft::Applications::Events;

namespace onnxruntime {

// PosixTelemetry can be constructed during early Env initialization (before logging registers a
// default logger) and destroyed late at process exit, so only emit warnings when a default logger
// exists, to avoid touching a missing/destroyed LoggingManager.
#define ORT_TELEMETRY_WARN(stream_expr)                               \
  do {                                                                \
    if (::onnxruntime::logging::LoggingManager::HasDefaultLogger()) { \
      LOGS_DEFAULT(WARNING) << stream_expr;                           \
    }                                                                 \
  } while (0)

// Static member initialization
std::atomic<uint32_t> PosixTelemetry::global_register_count_{0};
std::mutex PosixTelemetry::global_mutex_;
std::shared_mutex PosixTelemetry::mutex_;
::Microsoft::Applications::Events::ILogManager* PosixTelemetry::log_manager_ = nullptr;
std::atomic<::Microsoft::Applications::Events::ILogger*> PosixTelemetry::logger_{nullptr};
std::unique_ptr<::Microsoft::Applications::Events::ILogConfiguration> PosixTelemetry::config_;
std::atomic<bool> PosixTelemetry::enabled_{true};
std::atomic<bool> PosixTelemetry::env_disabled_{false};
std::atomic<uint32_t> PosixTelemetry::projection_{0};
std::atomic<bool> PosixTelemetry::process_info_logged_{false};

#if !defined(ORT_TELEMETRY_TENANT_TOKEN)
namespace {

// Decode a base64-encoded string at runtime.
std::string DecodeBase64(const std::string& encoded) {
  auto DecodeChar = [](char c) -> int {
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a' + 26;
    if (c >= '0' && c <= '9') return c - '0' + 52;
    if (c == '+') return 62;
    if (c == '/') return 63;
    return -1;
  };

  std::string result;
  result.reserve(encoded.size() * 3 / 4);
  uint32_t accum = 0;
  int bits = 0;
  for (char c : encoded) {
    int val = DecodeChar(c);
    if (val < 0) continue;
    accum = (accum << 6) | static_cast<uint32_t>(val);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      result.push_back(static_cast<char>((accum >> bits) & 0xFF));
    }
  }
  return result;
}

// In-repo default 1DS ingestion token used when no build-time override is provided.
std::string GetToken() {
  static constexpr char kXorKey[] = "OnnxRuntime";
  constexpr size_t klen = sizeof(kXorKey) - 1;
  std::string decoded = DecodeBase64(
      "eg8KQWRGDBBdD1YuWl9JahRaTFhZVX4NDUhgRF9MXlhIegxYHGpFXxJEXVd/V0NMa0FXWVEOA3hDCxw3RFhCUF8Edl0NVWRMWEM=");
  for (size_t i = 0; i < decoded.size(); ++i) {
    decoded[i] = static_cast<char>(decoded[i] ^ kXorKey[i % klen]);
  }
  return decoded;
}

}  // namespace
#endif  // !defined(ORT_TELEMETRY_TENANT_TOKEN)

// Event priority mapping (1DS priorities)
enum class EventPriority {
  NORMAL = EventLatency_Normal,     // Most events
  HIGH = EventLatency_RealTime,     // RuntimeError
  CRITICAL = EventLatency_RealTime  // ProcessInfo, SessionCreation
};

// Helper class to build events with common properties
class EventBuilder {
 private:
  EventProperties props_;

 public:
  explicit EventBuilder(std::string event_name, EventPriority priority)
      : props_(std::move(event_name)) {
    // Set latency/priority
    props_.SetLatency(static_cast<EventLatency>(priority));
    props_.SetPopsample(100.0);

    // All ORT telemetry is required system metadata (no PII)
    props_.SetLevel(DIAG_LEVEL_REQUIRED);
  }

  EventBuilder& SetPopsample(double sample_rate_percent) {
    props_.SetPopsample(sample_rate_percent);
    return *this;
  }

  EventBuilder& AddString(const char* key, const std::string& value) {
    if (!value.empty()) {
      props_.SetProperty(key, value);
    }
    return *this;
  }

  EventBuilder& AddInt32(const char* key, int32_t value) {
    props_.SetProperty(key, static_cast<int64_t>(value));
    return *this;
  }

  EventBuilder& AddInt64(const char* key, int64_t value) {
    props_.SetProperty(key, value);
    return *this;
  }

  EventBuilder& AddBool(const char* key, bool value) {
    props_.SetProperty(key, value);
    return *this;
  }

  EventBuilder& AddUInt32(const char* key, uint32_t value) {
    props_.SetProperty(key, static_cast<int64_t>(value));
    return *this;
  }

  EventBuilder& AddDouble(const char* key, double value) {
    props_.SetProperty(key, value);
    return *this;
  }

  // Helper for vector to comma-separated string
  EventBuilder& AddStringList(const char* key, const std::vector<std::string>& vec) {
    if (!vec.empty()) {
      std::string result;
      for (size_t i = 0; i < vec.size(); ++i) {
        if (i > 0) result += ',';
        result += vec[i];
      }
      props_.SetProperty(key, result);
    }
    return *this;
  }

  // Helper for map to key=value,key=value format
  EventBuilder& AddIntMap(const char* key, const std::unordered_map<std::string, int>& map) {
    if (!map.empty()) {
      std::string result;
      bool first = true;
      for (const auto& [k, v] : map) {
        if (!first) result += ',';
        result += k + '=' + std::to_string(v);
        first = false;
      }
      props_.SetProperty(key, result);
    }
    return *this;
  }

  // Helper for string map
  EventBuilder& AddStringMap(const char* key, const std::unordered_map<std::string, std::string>& map) {
    if (!map.empty()) {
      std::string result;
      bool first = true;
      for (const auto& [k, v] : map) {
        if (!first) result += ',';
        result += k + '=' + v;
        first = false;
      }
      props_.SetProperty(key, result);
    }
    return *this;
  }

  // Helper for batch size duration map
  EventBuilder& AddBatchSizeDurations(const std::unordered_map<int64_t, long long>& durations) {
    std::string result;
    for (const auto& [batch_size, duration] : durations) {
      if (!result.empty()) {
        result += ", ";
      }
      result += std::to_string(batch_size);
      result += ": ";
      result += std::to_string(duration);
    }
    props_.SetProperty("totalRunDurationPerBatchSize", result);
    return *this;
  }

  EventProperties Build() { return std::move(props_); }
};

// Hash a device ID with a stable, platform-independent algorithm (FNV-1a 64-bit) and format as
// fixed-width hex, so the same device maps to the same product-specific id across runs and platforms.
// std::hash is implementation-defined (and may be process-salted), so it is unsuitable here.
// Ensures raw device identifiers are never sent over the wire.
[[maybe_unused]] static std::string HashDeviceId(const std::string& id) {
  static constexpr std::string_view kDeviceIdHashSalt = "onnxruntime:";
  uint64_t hash = 14695981039346656037ULL;  // FNV-1a offset basis
  for (unsigned char c : kDeviceIdHashSalt) {
    hash ^= static_cast<uint64_t>(c);
    hash *= 1099511628211ULL;
  }
  for (unsigned char c : id) {
    hash ^= static_cast<uint64_t>(c);
    hash *= 1099511628211ULL;  // FNV-1a prime
  }
  std::ostringstream oss;
  oss << std::hex << std::setfill('0') << std::setw(16) << hash;
  return oss.str();
}

namespace {

const std::string& GetAppSessionGuid() {
  static const std::string guid = GenerateGuidV4();
  return guid;
}

template <typename Operation>
void RunTelemetryOperation(const char* operation_name, Operation&& operation) noexcept {
  auto warning = [operation_name](const char* message) {
    if (message != nullptr) {
      ORT_TELEMETRY_WARN("[Telemetry] " << operation_name << " failed: " << message);
    } else {
      ORT_TELEMETRY_WARN("[Telemetry] " << operation_name << " failed with an unknown exception");
    }
  };

  telemetry_internal::RunTelemetryOperationNoThrow(
      std::forward<Operation>(operation), warning);
}

bool PrepareSampledEvent(EventBuilder& event, uint32_t session_id) {
  if (!telemetry_internal::ShouldSampleSession(GetAppSessionGuid(), session_id)) {
    return false;
  }

  event.SetPopsample(telemetry_internal::kModelSessionSampleRatePercent);
  return true;
}

int32_t GetProcessorCount() {
  auto n = sysconf(_SC_NPROCESSORS_ONLN);
  if (n <= 0) {
    return 0;
  }
  if (n > static_cast<long>(std::numeric_limits<int32_t>::max())) {
    return std::numeric_limits<int32_t>::max();
  }
  return static_cast<int32_t>(n);
}

}  // namespace

PosixTelemetry::PosixTelemetry() {
  std::lock_guard<std::mutex> lock(global_mutex_);

  // Always increment so destructor pairing is symmetric
  global_register_count_++;

  if (global_register_count_ == 1) {
    RunTelemetryOperation("Initialize", [&]() {
      Initialize();
    });
  }
}

PosixTelemetry::~PosixTelemetry() {
  std::lock_guard<std::mutex> lock(global_mutex_);

  global_register_count_--;
  if (global_register_count_ == 0) {
    ORT_TRY {
      Shutdown();
    }
    ORT_CATCH(...) {
      // Don't throw from a destructor. This can run during process teardown after logging and/or
      // 1DS static state has started shutting down, so avoid touching any other infrastructure here.
    }
  }
}

void PosixTelemetry::LogEventAsync(Microsoft::Applications::Events::EventProperties&& props) const {
  // Hold a shared (reader) lock for the duration of the LogEvent call so the logger and its owning
  // log manager cannot be torn down underneath us: Initialize()/Shutdown() take this lock
  // exclusively. The shared lock still allows multiple threads to log concurrently.
  std::shared_lock<std::shared_mutex> lock(mutex_);
  auto* logger = logger_.load(std::memory_order_acquire);
  if (logger == nullptr) {
    return;
  }
  logger->LogEvent(std::move(props));
}

void PosixTelemetry::Initialize() {
  std::unique_lock<std::shared_mutex> lock(mutex_);

  // In a CI / build-pipeline environment, or inside ORT's own unit-test binaries, collect nothing at
  // all: skip creating the 1DS uploader entirely so no events (not even ProcessInfo) are emitted and
  // no device id is written.
  if (IsRunningInCI() || IsRunningUnitTests()) {
    enabled_.store(false, std::memory_order_release);
    return;
  }

  // ORT_TELEMETRY_DISABLED suppresses usage events for the lifetime of the process but still creates
  // the uploader, so the one-shot ProcessInfo event is emitted. Runtime disable behaves the same way
  // for ProcessInfo but remains reversible when there was no environment opt-out.
  if (IsTelemetryDisabledByEnvVar()) {
    env_disabled_.store(true, std::memory_order_release);
    enabled_.store(false, std::memory_order_release);
  }

  // The official Android AAR initializes the SDK's Java HttpClient before ORT is loaded. Native-only
  // integrators must provide the same application-context initialization before creating an OrtEnv.
#if defined(__ANDROID__)
  if (!HttpClient_Android::GetClientInstance()) {
    ORT_TELEMETRY_WARN("Android telemetry is unavailable because the 1DS Java HttpClient was not initialized");
    return;
  }
#endif

  // Create SDK configuration — stored as member because LogManagerImpl holds a reference
  // and the configuration must remain valid for the lifetime of the log manager.
  config_ = std::make_unique<ILogConfiguration>();
  auto& config = *config_;

  config[CFG_STR_COLLECTOR_URL] = "https://mobile.events.data.microsoft.com/OneCollector/1.0";
  config[CFG_INT_TRACE_LEVEL_MASK] = 0;                      // Disable SDK internal logging
  config[CFG_INT_SDK_MODE] = SdkModeTypes::SdkModeTypes_CS;  // Common Schema 4.0 mode
  // Do not block process teardown to upload; persisted events are sent on the next run. 0 keeps
  // Shutdown non-blocking and avoids adding exit latency to host apps.
  config[CFG_INT_MAX_TEARDOWN_TIME] = 0;

#if !defined(__ANDROID__)
  // Configure the desktop cache in the same directory as device ID storage. Android's Java
  // HttpClient supplies the app-private cache directory to 1DS.
  {
    std::string cache_dir = DeviceId::EnsureStorageDirectory();
    if (!cache_dir.empty()) {
      std::string cache_path = cache_dir + "/onnxruntime.db";
      config[CFG_STR_CACHE_FILE_PATH] = cache_path;
    }
  }
#endif

  // Configure RAM queue for async batching
  config[CFG_INT_RAM_QUEUE_SIZE] = 512 * 1024;  // 512KB RAM queue

  // Create log manager via LogManagerProvider (recommended for production use,
  // per LogManager_Creation_and_Lifecycle_Management.md).
  status_t status;
  log_manager_ = LogManagerProvider::CreateLogManager("OnnxRuntime", true, *config_, status);
  if (status != STATUS_SUCCESS || !log_manager_) {
    ORT_TELEMETRY_WARN("Failed to create telemetry LogManager, status: " << status);
    // CreateLogManager can return a live manager alongside a non-success status; release it (and
    // drop our reference) before destroying config_, which the manager holds a reference to.
    if (log_manager_ != nullptr) {
      LogManagerProvider::Release(*config_);
      log_manager_ = nullptr;
    }
    config_.reset();
    return;
  }

  // Get logger for our tenant: an official build's override from the generated header
  // (ORT_TELEMETRY_TENANT_TOKEN) if present, otherwise the in-repo default.
#if defined(ORT_TELEMETRY_TENANT_TOKEN)
  const std::string tenant_token = ORT_TELEMETRY_TENANT_TOKEN;
#else
  const std::string tenant_token = GetToken();
#endif
  auto* logger = log_manager_->GetLogger(tenant_token.c_str());
  if (logger == nullptr) {
    ORT_TELEMETRY_WARN("Failed to get telemetry logger");
    LogManagerProvider::Release(*config_);
    log_manager_ = nullptr;
    config_.reset();
    return;
  }

  // Use BEST_EFFORT transmit profile to minimize battery and network impact.
  // Events are batched and uploaded at a lower cadence.
  log_manager_->SetTransmitProfile(TransmitProfile_BestEffort);

  // Device ID.
#if defined(__ANDROID__) || (defined(__APPLE__) && TARGET_OS_IOS)
  // Mobile (Android/iOS): leave the device ID to the 1DS SDK, which uses the platform's own
  // identifier (identifierForVendor on iOS, ANDROID_ID on Android). Do not override it.
#else
  // Desktop: send a hashed version of our persistent UUID (the "c:" prefix marks it as a
  // caller-supplied identifier); the raw UUID itself is never transmitted.
  auto& device_id = DeviceId::Instance();
  std::string raw_device_id = device_id.GetValue();
  if (!raw_device_id.empty()) {
    logger->GetSemanticContext()->SetDeviceId("c:" + HashDeviceId(raw_device_id));
  }
#endif

  // 1DS supplies host application, OS, and device context. Add only ORT library identity and
  // process-wide correlation context.
  logger->SetContext("AppSessionGuid", GetAppSessionGuid());
  logger->SetContext("LibraryName", "ONNXRuntime");
  logger->SetContext("LibraryVersion", ORT_VERSION);

  // Caller-framework label from the build-time ORT_CALLER_FRAMEWORK option; only stamped when a
  // redistributor sets it, so standard builds add nothing. Matches the Windows provider's field.
  if (std::string framework = ORT_CALLER_FRAMEWORK; !framework.empty()) {
    logger->SetContext("frameworkName", framework);
  }

  // Publish the fully-configured logger atomically; concurrent readers observe it only now.
  // enabled_ is left to its default / the runtime EnableTelemetryEvents()/DisableTelemetryEvents()
  // opt-in state rather than being force-set here.
  logger_.store(logger, std::memory_order_release);
}

void PosixTelemetry::Shutdown() {
  std::unique_lock<std::shared_mutex> lock(mutex_);

  // Clear the logger so concurrent LogEventAsync() readers (which take the shared lock) observe
  // nullptr and skip. enabled_ is intentionally left untouched: it reflects the user's
  // EnableTelemetryEvents()/DisableTelemetryEvents() opt-in state, so a later Initialize() (e.g. in
  // tests or dynamic load/unload of the last instance) can resume telemetry without a forced re-enable.
  logger_ = nullptr;  // Owned by log_manager_, will be destroyed with it

  if (log_manager_ && config_) {
    // Per SDK use-after-free docs (use-after-free.md):
    // Flush() must be called before FlushAndTeardown() to ensure all pending
    // events are persisted to offline storage. FlushAndTeardown() internally
    // calls PauseActivity() + WaitPause() to quiesce the SDK.
    log_manager_->Flush();
    log_manager_->FlushAndTeardown();

    // Release the log manager instance via LogManagerProvider
    LogManagerProvider::Release(*config_);
    log_manager_ = nullptr;
    config_.reset();
  }
}

std::string PosixTelemetry::GetPlatformInfo() const {
#if defined(__APPLE__)
#if TARGET_OS_IOS
  return "iOS";
#elif TARGET_OS_MAC
  return "macOS";
#else
  return "Apple";
#endif
#elif defined(__ANDROID__)
  return "Android";
#elif defined(__linux__)
  return "Linux";
#else
  return "Unknown";
#endif
}

// ---------------------------------------------------------------------------
// Process / system info helpers for LogProcessInfo
// ---------------------------------------------------------------------------

// Get detailed OS version string (e.g., "macOS 15.2", "Ubuntu 22.04 LTS")
std::string PosixTelemetry::GetOsDescription() const {
#if defined(__APPLE__)
  char version[64] = {};
  size_t len = sizeof(version);
  if (sysctlbyname("kern.osproductversion", version, &len, nullptr, 0) == 0) {
#if TARGET_OS_IOS
    return std::string("iOS ") + version;
#else
    return std::string("macOS ") + version;
#endif
  }
  return GetPlatformInfo();

#elif defined(__ANDROID__)
  // Read Android system properties via /system/build.prop
  std::string release, sdk;
  std::ifstream prop("/system/build.prop");
  if (prop.is_open()) {
    std::string line;
    while (std::getline(prop, line)) {
      if (line.rfind("ro.build.version.release=", 0) == 0)
        release = line.substr(25);
      else if (line.rfind("ro.build.version.sdk=", 0) == 0)
        sdk = line.substr(21);
    }
  }
  if (!release.empty()) {
    std::string result = "Android " + release;
    if (!sdk.empty()) result += " (API " + sdk + ")";
    return result;
  }
  return "Android";

#elif defined(__linux__)
  // Parse /etc/os-release for PRETTY_NAME (e.g., "Ubuntu 22.04.3 LTS")
  std::ifstream os_release("/etc/os-release");
  if (os_release.is_open()) {
    std::string line;
    while (std::getline(os_release, line)) {
      if (line.rfind("PRETTY_NAME=", 0) == 0) {
        std::string value = line.substr(12);
        if (value.size() >= 2 && value.front() == '"' && value.back() == '"') {
          value = value.substr(1, value.size() - 2);
        }
        return value;
      }
    }
  }
  return "Linux";

#else
  return "Unknown";
#endif
}

// Get the name of the current process
std::string PosixTelemetry::GetProcessName() const {
#if defined(__APPLE__) || defined(__FreeBSD__)
  const char* name = getprogname();
  return name ? name : "";

#elif defined(__linux__) || defined(__ANDROID__)
  // /proc/self/cmdline holds the full null-separated argv; argv[0]'s basename is the executable
  // name and is not truncated (unlike /proc/self/comm, which caps the name at 15 characters).
  {
    std::ifstream cmdline("/proc/self/cmdline", std::ios::binary);
    if (cmdline.is_open()) {
      std::string arg0;
      std::getline(cmdline, arg0, '\0');
      if (!arg0.empty()) {
        const size_t slash = arg0.find_last_of('/');
        return slash == std::string::npos ? arg0 : arg0.substr(slash + 1);
      }
    }
  }
  // Fallback to /proc/self/comm (process name, capped at 15 characters).
  {
    std::ifstream comm("/proc/self/comm");
    if (comm.is_open()) {
      std::string name;
      std::getline(comm, name);
      while (!name.empty() && (name.back() == '\n' || name.back() == '\r'))
        name.pop_back();
      return name;
    }
  }
  return "";

#else
  return "";
#endif
}

// Get the CPU brand string (e.g. "Intel(R) Core(TM) i7-10700K"). Empty when unavailable.
std::string PosixTelemetry::GetCpuModel() const {
#if defined(__APPLE__)
  // macOS/iOS expose the CPU brand string via sysctl.
  char buf[256] = {0};
  size_t size = sizeof(buf);
  if (sysctlbyname("machdep.cpu.brand_string", buf, &size, nullptr, 0) == 0) {
    return std::string(buf);
  }
  return "";

#elif defined(__linux__) || defined(__ANDROID__)
  // /proc/cpuinfo exposes the CPU brand as "model name" (x86) or "Hardware" (ARM).
  std::ifstream cpuinfo("/proc/cpuinfo");
  std::string line;
  std::string hardware;
  while (std::getline(cpuinfo, line)) {
    const size_t colon = line.find(':');
    if (colon == std::string::npos) {
      continue;
    }
    std::string key = line.substr(0, colon);
    while (!key.empty() && std::isspace(static_cast<unsigned char>(key.back()))) {
      key.pop_back();
    }
    std::string value = line.substr(colon + 1);
    const size_t start = value.find_first_not_of(" \t");
    value = (start == std::string::npos) ? std::string() : value.substr(start);
    if (key == "model name") {
      return value;
    }
    if (hardware.empty() && key == "Hardware") {
      hardware = value;
    }
  }
  return hardware;

#else
  return "";
#endif
}

// Coarse device class for the host: "Mobile" on Android/iOS, "Desktop" elsewhere.
std::string PosixTelemetry::GetDeviceClass() const {
#if defined(__ANDROID__) || (defined(__APPLE__) && TARGET_OS_IOS)
  return "Mobile";
#else
  return "Desktop";
#endif
}

// Get the CPU architecture the binary was compiled for
std::string PosixTelemetry::GetArchitecture() {
#if defined(__x86_64__)
  return "x86_64";
#elif defined(__i386__)
  return "x86";
#elif defined(__aarch64__)
  return "arm64";
#elif defined(__arm__)
  return "arm";
#elif defined(__riscv)
  return "riscv";
#elif defined(__wasm__)
  return "wasm";
#else
  return "unknown";
#endif
}

// Get total physical memory in MB
int64_t PosixTelemetry::GetTotalMemoryMB() {
#if defined(__APPLE__)
  int64_t mem = 0;
  size_t len = sizeof(mem);
  if (sysctlbyname("hw.memsize", &mem, &len, nullptr, 0) == 0) {
    return mem / (1024 * 1024);
  }
  return -1;

#elif defined(__linux__) || defined(__ANDROID__)
  long pages = sysconf(_SC_PHYS_PAGES);
  long page_size = sysconf(_SC_PAGE_SIZE);
  if (pages > 0 && page_size > 0) {
    return static_cast<int64_t>(pages) * page_size / (1024 * 1024);
  }
  return -1;

#else
  return -1;
#endif
}

void PosixTelemetry::EnableTelemetryEvents() const {
  enabled_.store(
      CanEnableTelemetryEvents(env_disabled_.load(std::memory_order_acquire)),
      std::memory_order_release);
}

void PosixTelemetry::DisableTelemetryEvents() const {
  enabled_.store(false, std::memory_order_release);
}

void PosixTelemetry::SetLanguageProjection(uint32_t projection) const {
  projection_ = projection;
}

bool PosixTelemetry::IsEnabled() const {
  // Reflect actual readiness: the opt-out flag AND a successfully-initialized logger.
  return enabled_.load(std::memory_order_acquire) && logger_.load(std::memory_order_acquire) != nullptr;
}

unsigned char PosixTelemetry::Level() const {
  // POSIX telemetry has no ETW-style level/keyword control plane; report zero.
  return 0;
}

uint64_t PosixTelemetry::Keyword() const {
  return 0;
}

void PosixTelemetry::LogProcessInfo() const {
  RunTelemetryOperation("LogProcessInfo", [&]() {
    // ProcessInfo fires whenever telemetry is initialized (i.e. not in a CI build), even when the usage
    // events are disabled via ORT_TELEMETRY_DISABLED or DisableTelemetryEvents(). It only needs a live
    // logger; CI suppression already prevents one from being created.
    if (logger_.load(std::memory_order_acquire) == nullptr) {
      return;
    }

    // Log process info only once
    if (process_info_logged_.exchange(true)) {
      return;
    }

#if !defined(__ANDROID__) && !(defined(__APPLE__) && TARGET_OS_IOS)
    if (DeviceId::Instance().GetStatus() == DeviceIdStatus::Failed) {
      ORT_TELEMETRY_WARN("Failed to persist telemetry device ID; using an in-memory identifier");
    }
#endif

    auto builder = EventBuilder("ProcessInfo", EventPriority::CRITICAL)
                       .AddString("runtimeVersion", ORT_VERSION)
#if defined(__ANDROID__) || (defined(__APPLE__) && TARGET_OS_IOS)
                       .AddString("DeviceInfo.Status", "Mobile")
#else
                       .AddString("DeviceInfo.Status", DeviceId::Instance().GetStatusString())
#endif
                       .AddString("osDescription", GetOsDescription())
                       .AddString("processName", GetProcessName())
                       .AddString("architecture", GetArchitecture())
                       .AddString("cpuModel", GetCpuModel())
                       .AddString("deviceClass", GetDeviceClass())
                       .AddInt32("processorCount", GetProcessorCount())
                       .AddInt64("totalMemoryMB", GetTotalMemoryMB());

    LogEventAsync(builder.Build());
  });
}

void PosixTelemetry::LogSessionCreationStart(uint32_t session_id) const {
  RunTelemetryOperation("LogSessionCreationStart", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("SessionCreationStart", EventPriority::CRITICAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id).Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogEvaluationStop(uint32_t session_id) const {
  RunTelemetryOperation("LogEvaluationStop", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("EvaluationStop", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id).Build();

    LogEventAsync(std::move(event));

    // Capture system metrics after each inference run to observe impact
    LogSystemMetrics(session_id);
  });
}

void PosixTelemetry::LogEvaluationStart(uint32_t session_id) const {
  RunTelemetryOperation("LogEvaluationStart", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("EvaluationStart", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id).Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogSessionCreation(
    uint32_t session_id, int64_t ir_version,
    const std::string& model_producer_name,
    const std::string& model_producer_version,
    const std::string& model_domain,
    const std::unordered_map<std::string, int>& domain_to_version_map,
    const std::string& model_file_name,
    const std::string& model_graph_name,
    const std::string& model_weight_type,
    const std::string& model_graph_hash,
    const std::string& model_weight_hash,
    const std::unordered_map<std::string, std::string>& model_metadata,
    const std::string& loadedFrom,
    const std::vector<std::string>& execution_provider_ids,
    const std::string& hardware_device_types,
    const std::string& hardware_vendor_ids,
    const std::string& ep_versions,
    bool use_fp16, bool captureState) const {
  RunTelemetryOperation("LogSessionCreation", [&]() {
    if (!IsEnabled()) {
      return;
    }

    // captureState is currently only triggered on Windows via ETW's EVENT_CONTROL_CODE_CAPTURE_STATE callback
    // (LogAllSessions). Kept here for future compatibility if a similar mechanism is added for POSIX.
    std::string event_name = captureState ? "SessionCreation_CaptureState" : "SessionCreation";

    auto builder = EventBuilder(std::move(event_name), EventPriority::CRITICAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    builder.AddUInt32("sessionId", session_id)
        .AddInt64("irVersion", ir_version)
        .AddUInt32("OrtProgrammingProjection", projection_.load())
        .AddString("modelProducerName", model_producer_name)
        .AddString("modelProducerVersion", model_producer_version)
        .AddString("modelDomain", model_domain)
        .AddIntMap("domainToVersionMap", domain_to_version_map)
        .AddString("modelFileName", model_file_name)
        .AddString("modelGraphName", model_graph_name)
        .AddString("modelWeightType", model_weight_type)
        .AddString("modelGraphHash", model_graph_hash)
        .AddString("modelWeightHash", model_weight_hash)
        .AddStringMap("modelMetaData", model_metadata)
        .AddString("loadedFrom", loadedFrom)
        .AddStringList("executionProviderIds", execution_provider_ids)
        .AddString("hardwareDeviceTypes", hardware_device_types)
        .AddString("hardwareVendorIds", hardware_vendor_ids)
        .AddString("executionProviderVersions", ep_versions)
        .AddBool("usefp16", use_fp16);

    LogEventAsync(builder.Build());
  });
}

void PosixTelemetry::LogCompileModelStart(
    uint32_t session_id,
    const std::string& input_source,
    const std::string& output_target,
    uint32_t flags,
    int graph_optimization_level,
    bool embed_ep_context,
    bool has_external_initializers_file,
    const std::vector<std::string>& execution_provider_ids) const {
  RunTelemetryOperation("LogCompileModelStart", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("CompileModelStart", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id)
                     .AddString("inputSource", input_source)
                     .AddString("outputTarget", output_target)
                     .AddUInt32("flags", flags)
                     .AddInt32("graphOptimizationLevel", graph_optimization_level)
                     .AddBool("embedEpContext", embed_ep_context)
                     .AddBool("hasExternalInitializersFile", has_external_initializers_file)
                     .AddStringList("executionProviderIds", execution_provider_ids)
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogCompileModelComplete(
    uint32_t session_id,
    bool success,
    uint32_t error_code,
    uint32_t error_category,
    const std::string& error_message) const {
  RunTelemetryOperation("LogCompileModelComplete", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("CompileModelComplete", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id)
                     .AddBool("success", success)
                     .AddUInt32("errorCode", error_code)
                     .AddUInt32("errorCategory", error_category)
                     .AddString("errorMessage", ScrubStringForTelemetry(error_message))
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogRuntimeError(
    uint32_t session_id, const common::Status& status,
    const char* file, const char* function, uint32_t line) const {
  RunTelemetryOperation("LogRuntimeError", [&]() {
    if (!IsEnabled()) {
      return;
    }

    // __FILE__ may be an absolute build path that embeds developer/build directory names; emit only
    // the basename so remote telemetry doesn't leak usernames or local paths.
    std::string_view file_view = file ? std::string_view{file} : std::string_view{};
    if (const size_t slash = file_view.find_last_of("/\\"); slash != std::string_view::npos) {
      file_view.remove_prefix(slash + 1);
    }
    const std::string scrubbed_file = ScrubStringForTelemetry(file_view);

    auto builder = EventBuilder("RuntimeError", EventPriority::HIGH);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id)
                     .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                     .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                     .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                     .AddString("file", scrubbed_file)
                     .AddString("function", function ? function : "")
                     .AddUInt32("line", line)
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogRuntimeInferenceError(uint32_t session_id, const common::Status& status,
                                              const std::string& ep_versions,
                                              const std::string& ep_device_types) const {
  RunTelemetryOperation("LogRuntimeInferenceError", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("RuntimeInferenceError", EventPriority::HIGH);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id)
                     .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                     .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                     .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                     .AddString("executionProviderVersions", ep_versions)
                     .AddString("executionProviderDeviceTypes", ep_device_types)
                     .AddString("runtimeVersion", ORT_VERSION)
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogRuntimePerf(
    uint32_t session_id, uint32_t total_runs_since_last,
    int64_t total_run_duration_since_last,
    const std::unordered_map<int64_t, long long>& duration_per_batch_size) const {
  RunTelemetryOperation("LogRuntimePerf", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("RuntimePerf", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id)
                     .AddUInt32("totalRuns", total_runs_since_last)
                     .AddInt64("totalRunDuration", total_run_duration_since_last)
                     .AddBatchSizeDurations(duration_per_batch_size)
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogExecutionProviderEvent(LUID* adapterLuid) const {
  RunTelemetryOperation("LogExecutionProviderEvent", [&]() {
    // Not applicable for non-Windows platforms (LUID is Windows-specific)
    (void)adapterLuid;
  });
}

void PosixTelemetry::LogDriverInfoEvent(
    const std::string_view device_class,
    const std::wstring_view& driver_names,
    const std::wstring_view& driver_versions) const {
  RunTelemetryOperation("LogDriverInfoEvent", [&]() {
    // Not applicable for non-Windows platforms
    (void)device_class;
    (void)driver_names;
    (void)driver_versions;
  });
}

void PosixTelemetry::LogAutoEpSelection(
    uint32_t session_id, const std::string& selection_policy,
    const std::vector<std::string>& requested_execution_provider_ids,
    const std::vector<std::string>& available_execution_provider_ids) const {
  RunTelemetryOperation("LogAutoEpSelection", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("EpAutoSelection", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id)
                     .AddString("selectionPolicy", selection_policy)
                     .AddStringList("requestedExecutionProviderIds", requested_execution_provider_ids)
                     .AddStringList("availableExecutionProviderIds", available_execution_provider_ids)
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogProviderOptions(
    const std::string& provider_id,
    const std::string& provider_options_string,
    bool captureState) const {
  RunTelemetryOperation("LogProviderOptions", [&]() {
    if (!IsEnabled()) {
      return;
    }

    std::string event_name = captureState ? "ProviderOptions_CaptureState" : "ProviderOptions";
    const std::string scrubbed_provider_options = ScrubStringForTelemetry(provider_options_string);

    auto event = EventBuilder(std::move(event_name), EventPriority::NORMAL)
                     .AddString("providerId", provider_id)
                     .AddString("providerOptions", scrubbed_provider_options)
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogModelLoadStart(uint32_t session_id) const {
  RunTelemetryOperation("LogModelLoadStart", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("ModelLoadStart", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id).Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogModelLoadEnd(uint32_t session_id, const common::Status& status) const {
  RunTelemetryOperation("LogModelLoadEnd", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("ModelLoadEnd", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id)
                     .AddBool("isSuccess", status.IsOK())
                     .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                     .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                     .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogSessionCreationEnd(uint32_t session_id, const common::Status& status) const {
  RunTelemetryOperation("LogSessionCreationEnd", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("SessionCreationEnd", EventPriority::CRITICAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id)
                     .AddBool("isSuccess", status.IsOK())
                     .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                     .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                     .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogEpDeviceUsage(
    uint32_t session_id,
    const std::string& ep_type,
    const std::string& hardware_device_type,
    uint32_t hardware_vendor_id,
    uint32_t hardware_device_id,
    const std::string& hardware_vendor,
    const std::string& ep_vendor,
    const std::string& ep_version,
    int assigned_node_count,
    uint32_t total_runs_since_last,
    int64_t total_run_duration_since_last) const {
  RunTelemetryOperation("LogEpDeviceUsage", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("EpDeviceUsage", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }
    auto event = builder.AddUInt32("sessionId", session_id)
                     .AddString("executionProviderType", ep_type)
                     .AddString("hardwareDeviceType", hardware_device_type)
                     .AddUInt32("hardwareVendorId", hardware_vendor_id)
                     .AddUInt32("hardwareDeviceId", hardware_device_id)
                     .AddString("hardwareVendor", hardware_vendor)
                     .AddString("epVendor", ep_vendor)
                     .AddString("epVersion", ep_version)
                     .AddInt32("assignedNodeCount", assigned_node_count)
                     .AddUInt32("totalRunsSinceLast", total_runs_since_last)
                     .AddInt64("totalRunDurationSinceLast", total_run_duration_since_last)
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogRegisterEpLibraryStart(const std::string& registration_name) const {
  RunTelemetryOperation("LogRegisterEpLibraryStart", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto event = EventBuilder("RegisterEpLibraryStart", EventPriority::NORMAL)
                     .AddString("registrationName", registration_name)
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogRegisterEpLibraryEnd(const std::string& registration_name,
                                             const common::Status& status) const {
  RunTelemetryOperation("LogRegisterEpLibraryEnd", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto event = EventBuilder("RegisterEpLibraryEnd", EventPriority::NORMAL)
                     .AddString("registrationName", registration_name)
                     .AddBool("isSuccess", status.IsOK())
                     .AddInt32("errorCode", static_cast<int32_t>(status.Code()))
                     .AddInt32("errorCategory", static_cast<int32_t>(status.Category()))
                     .AddString("errorMessage", ScrubStringForTelemetry(status.ErrorMessage()))
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogRegisterEpLibraryWithLibPath(const std::string& registration_name,
                                                     const std::string& lib_path) const {
  RunTelemetryOperation("LogRegisterEpLibraryWithLibPath", [&]() {
    if (!IsEnabled()) {
      return;
    }

    const std::string scrubbed_lib_path = ScrubStringForTelemetry(lib_path);
    auto event = EventBuilder("RegisterEpLibraryWithLibPath", EventPriority::NORMAL)
                     .AddString("registrationName", registration_name)
                     .AddString("libPath", scrubbed_lib_path)
                     .Build();

    LogEventAsync(std::move(event));
  });
}

void PosixTelemetry::LogSystemMetrics(uint32_t session_id) const {
  RunTelemetryOperation("LogSystemMetrics", [&]() {
    if (!IsEnabled()) {
      return;
    }

    auto builder = EventBuilder("SystemMetrics", EventPriority::NORMAL);
    if (!PrepareSampledEvent(builder, session_id)) {
      return;
    }

    struct rusage usage;
    if (getrusage(RUSAGE_SELF, &usage) == 0) {
      // ru_maxrss is in KB on Linux, bytes on macOS
#ifdef __APPLE__
      int64_t max_rss_kb = usage.ru_maxrss / 1024;
#else
      int64_t max_rss_kb = usage.ru_maxrss;
#endif

      auto event = builder.AddUInt32("sessionId", session_id)
                       .AddInt64("maxRssKb", max_rss_kb)
                       .AddInt64("userCpuTimeSec", usage.ru_utime.tv_sec)
                       .AddInt64("userCpuTimeUsec", usage.ru_utime.tv_usec)
                       .AddInt64("systemCpuTimeSec", usage.ru_stime.tv_sec)
                       .AddInt64("systemCpuTimeUsec", usage.ru_stime.tv_usec)
                       .AddInt64("minorPageFaults", usage.ru_minflt)
                       .AddInt64("majorPageFaults", usage.ru_majflt)
                       .AddInt64("voluntaryContextSwitches", usage.ru_nvcsw)
                       .AddInt64("involuntaryContextSwitches", usage.ru_nivcsw)
                       .Build();

      LogEventAsync(std::move(event));
    }
  });
}

}  // namespace onnxruntime
