// This file is auto-generated by wgsl-gen. Do not edit manually.

"use strict";

globalThis.$templates = {
  "shader/triangle.wgsl.template": function(param, variable, shader_helper) {
    var $emitAdditional = function (code) {
      shader_helper.appendAdditionalImplementation(code);
    };
    var $emitMain = function (code) {
      shader_helper.appendMainFunctionBody(code);
    };
    var emit = $emitAdditional;

    var MainFunctionStart = function () {
      emit = $emitMain;
    };
    var MainFunctionEnd = function () {
      emit = $emitAdditional;
    };

emit("@vertex\n");
emit("fn vs_main(@builtin(vertex_index) vertex_index: u32) -> @builtin(position) vec4f {\n");
emit("    let pos = array<vec2f, 3>(\n");
emit("        vec2f(-0.5, -0.5),\n");
emit("        vec2f( 0.5, -0.5),\n");
emit("        vec2f( 0.0,  0.5)\n");
emit("    );\n");
emit("    return vec4f(pos[vertex_index], 0.0, 1.0);\n");
emit("}\n");
emit("\n");
emit("@fragment\n");
emit("fn fs_main() -> @location(0) vec4f {\n");
emit("    return vec4f(1.0, 0.0, 0.0, 1.0);\n");
emit("}\n");

    },
};
