// This file is auto-generated by wgsl-gen. Do not edit manually.

#pragma once
#ifndef INCLUDED_BY_WGSL_GEN_IMPL
#error "This file is expected to be included by wgsl-gen impl. Do not include it directly."
#endif

// Helper functions or macros

#pragma push_macro("MainFunctionStart")
#undef MainFunctionStart
#define MainFunctionStart() { [[maybe_unused]] auto& ss = shader_helper.MainFunctionBody();
#pragma push_macro("MainFunctionEnd")
#undef MainFunctionEnd
#define MainFunctionEnd() }

// Helper templates

namespace wgsl_detail {
template <typename T, typename = std::enable_if_t<std::is_integral_v<T>>>
std::string pass_as_string(T&& v) {
  return std::to_string(std::forward<T>(v));
}
template <typename...>
std::string_view pass_as_string(std::string_view sv) {
  return sv;
}
template <typename T>
std::string pass_as_string(T&& v) {
  return std::forward<T>(v);
}
}  // namespace wgsl_detail


// Include template implementations

#include "wgsl_template_gen/generated/math/subgroup_matrix_gemm_8x16x16.h"  // ec725d321ae3731505f5d6b1db8d12bb56c0f2801b63a55107ff676690a1629b
#include "wgsl_template_gen/generated/math/subgroup_matrix_matmul_8x16x16.h"  // d43e04ce0f3174057cb3811337a5bb84f9461ece9aef21dc2009768af5e62470
#include "wgsl_template_gen/generated/math/subgroup_matrix_matmul_pad_b.h"  // 8f4e48274de5ab42febd2d062ee1aca30efd78d7fb8c075d08f8d0b28ba7f9b6
#include "wgsl_template_gen/generated/nn/im2col_matmul.h"  // 6d1f1c76ec5e4adcf020ce27a689b30df1d344491ed04458d073c20560a2f088
#include "wgsl_template_gen/generated/tensor/oihw_to_ohwi.h"  // ea6d6ea3ad39540d34a2153b291792f6e419401941c9f1fcbc910a9d0880df54
#include "wgsl_template_gen/generated/tensor/pad.h"  // b346014fa4c18eaead71363209a32fb14af5877eaa999ddcc5da91c65a2d628a

#pragma pop_macro("MainFunctionStart")
#pragma pop_macro("MainFunctionEnd")