// This file is auto-generated by wgsl-gen. Do not edit manually.

#pragma once
#ifndef INCLUDED_BY_WGSL_GEN_IMPL
#error "This file is expected to be included by wgsl-gen impl. Do not include it directly."
#endif

// Helper functions or macros

#pragma push_macro("MainFunctionStart")
#undef MainFunctionStart
#define MainFunctionStart() { [[maybe_unused]] auto& ss = shader_helper.MainFunctionBody();
#pragma push_macro("MainFunctionEnd")
#undef MainFunctionEnd
#define MainFunctionEnd() }

// Helper templates

namespace wgsl_detail {
template <typename T, typename = std::enable_if_t<std::is_integral_v<T>>>
std::string pass_as_string(T&& v) {
  return std::to_string(std::forward<T>(v));
}
template <typename...>
std::string_view pass_as_string(std::string_view sv) {
  return sv;
}
template <typename T>
std::string pass_as_string(T&& v) {
  return std::forward<T>(v);
}
}  // namespace wgsl_detail


// Include template implementations

#include "wgsl_template_gen/generated/math/matmul_gemv.h"  // 9a2dfa487f81c1d879ca7fd1f22f5168a609dd6b0f0e28bde9920d64da3610b9
#include "wgsl_template_gen/generated/math/subgroup_matrix_gemm_8x16x16.h"  // e4d4e632b627e3527f2a8448bdaaa996eb790a03befb030429af34c50400c6fd
#include "wgsl_template_gen/generated/math/subgroup_matrix_matmul_8x16x16.h"  // 42e4f2ce086e2618a213bd6695ece7fb1858c1864396c6a59b4cbe7fff8a3853
#include "wgsl_template_gen/generated/math/subgroup_matrix_matmul_pad_b.h"  // d3f4c3f262840606d0eed6de0550add7e622561448f9517b4a6b2d253cd34867
#include "wgsl_template_gen/generated/nn/im2col_matmul.h"  // c51c36ba8f8b1c624f51daf78450271001177798f00e41d5b58e4cfd382cda6f
#include "wgsl_template_gen/generated/tensor/oihw_to_ohwi.h"  // 778821f611cf95f57bbdc512aac8cff341156a04d649b7fc2c851f16f3d99d38
#include "wgsl_template_gen/generated/tensor/pad.h"  // a08c564e78ff2b4d15647ae29195c31739db9897dde1ae2fe513d4614c4e3795

#pragma pop_macro("MainFunctionStart")
#pragma pop_macro("MainFunctionEnd")