// This file is auto-generated by wgsl-gen. Do not edit manually.

#pragma once
#ifndef INCLUDED_BY_WGSL_GEN_IMPL
#error "This file is expected to be included by wgsl-gen impl. Do not include it directly."
#endif

// Helper functions or macros

#pragma push_macro("MainFunctionStart")
#undef MainFunctionStart
#define MainFunctionStart() { [[maybe_unused]] auto& ss = shader_helper.MainFunctionBody();
#pragma push_macro("MainFunctionEnd")
#undef MainFunctionEnd
#define MainFunctionEnd() }

// Helper templates

namespace wgsl_detail {
template <typename T, typename = std::enable_if_t<std::is_integral_v<T>>>
std::string pass_as_string(T&& v) {
  return std::to_string(std::forward<T>(v));
}
template <typename...>
std::string_view pass_as_string(std::string_view sv) {
  return sv;
}
template <typename T>
std::string pass_as_string(T&& v) {
  return std::forward<T>(v);
}
}  // namespace wgsl_detail


// Include template implementations

#include "wgsl_template_gen/generated/math/subgroup_matrix_gemm_8x16x16.h"  // 0832c4684b2e16b53e10231658da9148f11580987bc26411bf2fc26eec3a88d0
#include "wgsl_template_gen/generated/math/subgroup_matrix_matmul_8x16x16.h"  // 38b22f53c7c9b252c9a144f86e1ee64a347d2e154f861957de6634ef9dc1fdac
#include "wgsl_template_gen/generated/nn/im2col_matmul.h"  // ecb91f64cb9ce39a8754a63ce82b864a98644cb1859acf5565639c1788002c10
#include "wgsl_template_gen/generated/tensor/oihw_to_ohwi.h"  // 35487692058e08b027768dcb1ab30ef93772da9a4a664702c34351a74d2568dc
#include "wgsl_template_gen/generated/tensor/pad.h"  // 43a2d8f5014de2ce571c703d842f2457d7c1762575254bc42ccee437a181cd3f

#pragma pop_macro("MainFunctionStart")
#pragma pop_macro("MainFunctionEnd")