/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * Licensed under the MIT License.
 */
package ai.onnxruntime;

import ai.onnxruntime.OrtSession.SessionOptions;
import java.nio.ByteBuffer;
import java.util.EnumSet;
import java.util.Objects;

/** Configuration options for compiling ONNX models. */
public final class OrtModelCompilationOptions implements AutoCloseable {
  /**
   * Receives external EPContext data during model compilation.
   *
   * <p>Each payload is copied into a new Java array that the application owns and may retain. ONNX
   * Runtime may invoke this callback concurrently from multiple threads, so implementations must
   * synchronize access to shared state. Throwing an exception fails compilation without falling
   * back to filesystem output.
   *
   * <p>Methods that mutate or close the originating {@link OrtModelCompilationOptions} throw {@link
   * IllegalStateException} while compilation is in progress. This also applies when they are called
   * reentrantly from this callback.
   */
  @FunctionalInterface
  public interface EpContextDataWriteCallback {
    /**
     * Writes one complete named EPContext payload.
     *
     * @param name The logical UTF-8 data identifier stored in the EPContext node.
     * @param data The payload, owned by the application.
     * @throws Exception If the payload cannot be written.
     */
    void write(String name, byte[] data) throws Exception;
  }

  /** Flags representing options when compiling a model. */
  public enum OrtCompileApiFlags implements OrtFlags {
    /** Default. Do not enable any additional compilation options. */
    NONE(0),

    /**
     * Force compilation to return an error (ORT_FAIL) if no nodes were compiled. Otherwise, a model
     * with basic optimizations (ORT_ENABLE_BASIC) is still generated by default.
     */
    ERROR_IF_NO_NODES_COMPILED(1),

    /**
     * Force compilation to return an error (ORT_FAIL) if a file with the same filename as the
     * output model exists. Otherwise, compilation will automatically overwrite the output file if
     * it exists.
     */
    ERROR_IF_OUTPUT_FILE_EXISTS(1 << 1);

    /** The native value of the enum. */
    public final int value;

    OrtCompileApiFlags(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }

  private final long nativeHandle;
  private boolean closed = false;

  private final SessionOptions.EpContextDataReadCallbackRegistration
      epContextDataReadCallbackRegistration;
  private long epContextDataWriteCallbackHandle;
  private boolean compilationInProgress;

  // Used to ensure the byte buffer doesn't get GC'd before the model is compiled.
  private ByteBuffer buffer;

  OrtModelCompilationOptions(
      long nativeHandle,
      SessionOptions.EpContextDataReadCallbackRegistration epContextDataReadCallbackRegistration) {
    this.nativeHandle = nativeHandle;
    this.epContextDataReadCallbackRegistration = epContextDataReadCallbackRegistration;
  }

  /**
   * Creates a model compilation options from an existing SessionOptions.
   *
   * <p>An OrtModelCompilationOptions object contains the settings used to generate a compiled ONNX
   * model. The OrtSessionOptions object has the execution providers with which the model will be
   * compiled.
   *
   * @param env The OrtEnvironment.
   * @param sessionOptions The session options to use.
   * @return A constructed model compilation options instance.
   * @throws OrtException If the construction failed.
   */
  public static OrtModelCompilationOptions createFromSessionOptions(
      OrtEnvironment env, OrtSession.SessionOptions sessionOptions) throws OrtException {
    try (SessionOptions.NativeSessionOptionsSnapshot snapshot = sessionOptions.createSnapshot()) {
      long handle =
          createFromSessionOptions(
              OnnxRuntime.ortApiHandle,
              OnnxRuntime.ortCompileApiHandle,
              env.getNativeHandle(),
              snapshot.getNativeHandle());
      boolean wrapped = false;
      try {
        OrtModelCompilationOptions options =
            new OrtModelCompilationOptions(
                handle, snapshot.getEpContextDataReadCallbackRegistration());
        snapshot.transferEpContextDataReadCallbackRegistration();
        wrapped = true;
        return options;
      } finally {
        if (!wrapped) {
          close(OnnxRuntime.ortCompileApiHandle, handle);
        }
      }
    }
  }

  /**
   * Checks if the OrtModelCompilationOptions is closed, if so throws {@link IllegalStateException}.
   */
  private void checkClosed() {
    if (closed) {
      throw new IllegalStateException("Trying to use a closed OrtModelCompilationOptions.");
    }
  }

  private void checkMutable() {
    checkClosed();
    if (compilationInProgress) {
      throw new IllegalStateException(
          "Cannot modify OrtModelCompilationOptions while model compilation is in progress.");
    }
  }

  @Override
  public synchronized void close() {
    if (!closed) {
      checkMutable();
      close(OnnxRuntime.ortCompileApiHandle, nativeHandle);
      closed = true;
      if (epContextDataWriteCallbackHandle != 0) {
        releaseEpContextDataCallback(epContextDataWriteCallbackHandle);
        epContextDataWriteCallbackHandle = 0;
      }
      if (epContextDataReadCallbackRegistration != null) {
        epContextDataReadCallbackRegistration.release();
      }
    } else {
      throw new IllegalStateException("Trying to close a closed OrtModelCompilationOptions.");
    }
  }

  /**
   * Sets the file path to the input ONNX model.
   *
   * <p>The input model's location must be set either to a path on disk with this method, or by
   * supplying an in-memory reference with {@link #setInputModelFromBuffer}.
   *
   * @param inputModelPath The path to the model on disk.
   * @throws OrtException If the set failed.
   */
  public synchronized void setInputModelPath(String inputModelPath) throws OrtException {
    checkMutable();
    setInputModelPath(
        OnnxRuntime.ortApiHandle, OnnxRuntime.ortCompileApiHandle, nativeHandle, inputModelPath);
  }

  /**
   * Uses the supplied buffer as the input ONNX model.
   *
   * <p>The input model's location must be set either to an in-memory reference with this method, or
   * by supplying a path on disk with {@link #setInputModelPath(String)}.
   *
   * <p>If the {@link ByteBuffer} is not direct it is copied into a direct buffer. In either case
   * this object holds a reference to the buffer to prevent it from being GC'd.
   *
   * @param inputModelBuffer The buffer.
   * @throws OrtException If the buffer could not be set.
   */
  public synchronized void setInputModelFromBuffer(ByteBuffer inputModelBuffer)
      throws OrtException {
    checkMutable();
    if (!inputModelBuffer.isDirect()) {
      // if it's not a direct buffer, copy it.
      buffer = ByteBuffer.allocateDirect(inputModelBuffer.remaining());
      int tmpPos = inputModelBuffer.position();
      buffer.put(inputModelBuffer);
      buffer.rewind();
      inputModelBuffer.position(tmpPos);
    } else {
      buffer = inputModelBuffer;
    }
    int bufferPos = buffer.position();
    int bufferRemaining = buffer.remaining();
    setInputModelFromBuffer(
        OnnxRuntime.ortApiHandle,
        OnnxRuntime.ortCompileApiHandle,
        nativeHandle,
        buffer,
        bufferPos,
        bufferRemaining);
  }

  /**
   * Sets the file path for the output compiled ONNX model.
   *
   * <p>If this is unset it will append `_ctx` to the file name, e.g., my_model.onnx becomes
   * my_model_ctx.onnx.
   *
   * @param outputModelPath The output model path.
   * @throws OrtException If the path could not be set.
   */
  public synchronized void setOutputModelPath(String outputModelPath) throws OrtException {
    checkMutable();
    setOutputModelPath(
        OnnxRuntime.ortApiHandle, OnnxRuntime.ortCompileApiHandle, nativeHandle, outputModelPath);
  }

  /**
   * Optionally sets the file that stores initializers for the compiled ONNX model. If unset then
   * initializers are stored inside the model.
   *
   * <p>Only initializers for nodes that were not compiled are stored in the external initializers
   * file. Compiled nodes contain their initializer data within the `ep_cache_context` attribute of
   * EPContext nodes.
   *
   * @see OrtModelCompilationOptions#setEpContextEmbedMode
   * @param outputExternalInitializersPath Path to the file.
   * @param sizeThreshold Initializers larger than this threshold are stored in the file.
   * @throws OrtException If the path could not be set.
   */
  public synchronized void setOutputExternalInitializersPath(
      String outputExternalInitializersPath, long sizeThreshold) throws OrtException {
    checkMutable();
    // check positive
    setOutputExternalInitializersPath(
        OnnxRuntime.ortApiHandle,
        OnnxRuntime.ortCompileApiHandle,
        nativeHandle,
        outputExternalInitializersPath,
        sizeThreshold);
  }

  /**
   * Enables or disables the embedding of EPContext binary data into the ep_cache_context attribute
   * of EPContext nodes.
   *
   * <p>Defaults to false. When enabled, the `ep_cache_context` attribute of EPContext nodes will
   * store the context binary data, which may include weights for compiled subgraphs. When disabled,
   * the `ep_cache_context` attribute of EPContext nodes will contain the path to the file
   * containing the context binary data. The path is set by the execution provider creating the
   * EPContext node.
   *
   * <p>For more details see the <a
   * href="https://onnxruntime.ai/docs/execution-providers/EP-Context-Design.html">EPContext design
   * document.</a>
   *
   * @param embedEpContext True to embed EPContext binary data into the EPContext node's
   *     ep_cache_context attribute.
   * @throws OrtException If the set operation failed.
   */
  public synchronized void setEpContextEmbedMode(boolean embedEpContext) throws OrtException {
    checkMutable();
    setEpContextEmbedMode(
        OnnxRuntime.ortApiHandle, OnnxRuntime.ortCompileApiHandle, nativeHandle, embedEpContext);
  }

  /**
   * Registers a callback that receives external EPContext data when embed mode is disabled.
   *
   * <p>The callback and its captured state are retained until they are replaced, cleared, or these
   * options are closed.
   *
   * @param callback The callback that receives named data.
   * @throws OrtException If native registration fails.
   * @throws NullPointerException If {@code callback} is null.
   */
  public synchronized void setEpContextDataWriteCallback(EpContextDataWriteCallback callback)
      throws OrtException {
    checkMutable();
    Objects.requireNonNull(callback, "callback must not be null");
    long callbackHandle =
        setEpContextDataWriteCallback(
            OnnxRuntime.ortApiHandle, OnnxRuntime.ortCompileApiHandle, nativeHandle, callback);
    long previousHandle = epContextDataWriteCallbackHandle;
    epContextDataWriteCallbackHandle = callbackHandle;
    if (previousHandle != 0) {
      releaseEpContextDataCallback(previousHandle);
    }
  }

  /**
   * Clears the EPContext data write callback.
   *
   * @throws OrtException If native registration fails.
   */
  public synchronized void clearEpContextDataWriteCallback() throws OrtException {
    checkMutable();
    clearEpContextDataWriteCallback(
        OnnxRuntime.ortApiHandle, OnnxRuntime.ortCompileApiHandle, nativeHandle);
    if (epContextDataWriteCallbackHandle != 0) {
      releaseEpContextDataCallback(epContextDataWriteCallbackHandle);
      epContextDataWriteCallbackHandle = 0;
    }
  }

  /**
   * Sets the specified compilation flags.
   *
   * @param flags The compilation flags.
   * @throws OrtException If the set operation failed.
   */
  public synchronized void setCompilationFlags(EnumSet<OrtCompileApiFlags> flags)
      throws OrtException {
    checkMutable();
    setCompilationFlags(
        OnnxRuntime.ortApiHandle,
        OnnxRuntime.ortCompileApiHandle,
        nativeHandle,
        OrtFlags.aggregateToInt(flags));
  }

  /**
   * Compiles the ONNX model with the configuration described by this instance of
   * OrtModelCompilationOptions.
   *
   * @throws OrtException If the compilation failed.
   * @throws IllegalStateException If these options are closed or another compilation is in
   *     progress.
   */
  public void compileModel() throws OrtException {
    synchronized (this) {
      checkClosed();
      if (compilationInProgress) {
        throw new IllegalStateException("Model compilation is already in progress.");
      }
      compilationInProgress = true;
    }

    try {
      // Safe as the environment must exist to create one of these objects.
      OrtEnvironment env = OrtEnvironment.getEnvironment();
      compileModel(
          OnnxRuntime.ortApiHandle,
          OnnxRuntime.ortCompileApiHandle,
          env.getNativeHandle(),
          nativeHandle);
    } finally {
      synchronized (this) {
        compilationInProgress = false;
      }
    }
  }

  private static native long createFromSessionOptions(
      long apiHandle, long compileApiHandle, long envHandle, long nativeHandle) throws OrtException;

  private static native void close(long compileApiHandle, long nativeHandle);

  private static native void setInputModelPath(
      long apiHandle, long compileApiHandle, long nativeHandle, String inputModelPath)
      throws OrtException;

  private static native void setInputModelFromBuffer(
      long apiHandle,
      long compileApiHandle,
      long nativeHandle,
      ByteBuffer inputBuffer,
      long bufferPos,
      long bufferRemaining)
      throws OrtException;

  private static native void setOutputModelPath(
      long apiHandle, long compileApiHandle, long nativeHandle, String outputModelPath)
      throws OrtException;

  private static native void setOutputExternalInitializersPath(
      long apiHandle,
      long compileApiHandle,
      long nativeHandle,
      String externalInitializersPath,
      long sizeThreshold)
      throws OrtException;

  private static native void setEpContextEmbedMode(
      long apiHandle, long compileApiHandle, long nativeHandle, boolean embedEpContext)
      throws OrtException;

  private static native long setEpContextDataWriteCallback(
      long apiHandle, long compileApiHandle, long nativeHandle, EpContextDataWriteCallback callback)
      throws OrtException;

  private static native void clearEpContextDataWriteCallback(
      long apiHandle, long compileApiHandle, long nativeHandle) throws OrtException;

  private static native void releaseEpContextDataCallback(long callbackHandle);

  private static native void setCompilationFlags(
      long apiHandle, long compileApiHandle, long nativeHandle, int flags) throws OrtException;

  private static native void compileModel(
      long apiHandle, long compileApiHandle, long envHandle, long nativeHandle) throws OrtException;
}
