platform :ios, '13.0'

target 'ios_package_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'ios_package_testUITests' do
    inherit! :search_paths
    pod 'onnxruntime-mobile-c', :podspec  => './onnxruntime-mobile-c.podspec'
  end

end

# This is to prevent the pods to be code signed if enabled
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
  end
end
