platform :ios, '13.0'

target 'ios_package_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_package_test
  pod 'OnnxRuntimeBase', :podspec  => './OnnxRuntimeBase.podspec'

  target 'ios_package_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
