name: Mobile
description: issues related to ONNX Runtime QNN mobile
title: "[Mobile] "
labels: ["platform:mobile"]
body:
  - type: markdown
    attributes:
      value: |
        If your request is a question/idea or otherwise not related to a bug/issue or feature request, please submit to [ONNX Runtime QNN GitHub Discussions](https://github.com/onnxruntime/onnxruntime-qnn/discussions).
        Before submitting your request, please review past submissions to ensure that it is not a duplicate of a known issue.
  - type: textarea
    id: issue-descript
    attributes:
      label: Describe the issue
      placeholder: Include your issue description, expected behavior, and any additional context necessary for your issue to be addressed (e.g., screenshots, GPU model & memory, etc.).
    validations:
      required: true
  - type: textarea
    id: reproducibility
    attributes:
      label: To reproduce
      placeholder: Steps to reproduce the issue. As applicable, please provide code and model(s) if possible.
    validations:
      required: true
  - type: textarea
    id: urgency
    attributes:
      label: Urgency
      placeholder: Is your issue urgent? If important use cases are blocked, there is a regression in ONNX Runtime functionality, or you have a strict project deadline, please elaborate here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # System information
        For each of the following items, provide the information listed to ensure that your request is addressed in a timely manner.
  - type: dropdown
    id: inf-plat
    attributes:
      label: Platform
      options:
        - Android
        - Other / Unknown
    validations:
      required: true
  - type: input
    id: os-dist
    attributes:
      label: OS Version
    validations:
      required: true
  - type: dropdown
    id: ort-installation
    attributes:
      label: ONNX Runtime QNN Installation
      options:
        - Built from Source
        - Released Package
        - Other / Unknown
    validations:
      required: true
  - type: input
    id: compiler-version
    attributes:
      label: Compiler Version (if 'Built from Source')
    validations:
      required: false
  - type: input
    id: ort-version
    attributes:
      label: ONNX Runtime Version or Commit ID
    validations:
      required: true
  - type: dropdown
    id: inf-api
    attributes:
      label: ONNX Runtime API
      options:
        - Python
        - C++
        - C#
        - C
        - Java
        - JavaScript
        - Obj-C
        - WinML
        - Other / Unknown
  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      options:
        - X64
        - X86
        - ARM64
        - Other / Unknown
    validations:
      required: true
  - type: input
    id: ort-qnn-version
    attributes:
      label: ONNX Runtime QNN Version or Commit ID
    validations:
      required: true
  - type: input
    id: qairt-version
    attributes:
      label: QAIRT version
      placeholder: ex. 2.43.0
    validations:
      required: true
