class DeviceArray:
    def __init__(self, ndarray) -> None: ...
    def UpdateHostNumpyArray(self) -> None: ...

class blas_op:
    T: int
    N: int

def is_composable_kernel_available(*args, **kwargs): ...
