Tensor Abs(const Tensor& X);
Tensor Acos(const Tensor& input);
Tensor Acosh(const Tensor& input);
Tensor Adagrad(const Tensor& R, const Tensor& T, const Tensor& inputs, float decay_factor, float epsilon, float norm_coefficient);
Tensor Adam(const Tensor& R, const Tensor& T, const Tensor& inputs, float alpha, float beta, float epsilon, float norm_coefficient, float norm_coefficient_post);
Tensor Add(const Tensor& A, const Tensor& B);
Tensor And(const Tensor& A, const Tensor& B);
Tensor ArgMax(const Tensor& data, int axis, int keepdims, int select_last_index);
Tensor ArgMin(const Tensor& data, int axis, int keepdims, int select_last_index);
Tensor ArrayFeatureExtractor(const Tensor& X, const Tensor& Y);
Tensor Asin(const Tensor& input);
Tensor Asinh(const Tensor& input);
Tensor Atan(const Tensor& input);
Tensor Atanh(const Tensor& input);
Tensor Bernoulli(const Tensor& input, int dtype, float seed);
Tensor Binarizer(const Tensor& X, float threshold);
Tensor Cast(const Tensor& input, int to);
Tensor CastLike(const Tensor& input, const Tensor& target_type);
Tensor Ceil(const Tensor& X);
Tensor Celu(const Tensor& X, float alpha);
Tensor Clip(const Tensor& input, const Tensor& min, const Tensor& max);
Tensor Compress(const Tensor& input, const Tensor& condition, int axis);
Tensor Concat(const Tensor& inputs, int axis);
Tensor ConcatFromSequence(const Tensor& input_sequence, int axis, int new_axis);
Tensor Cos(const Tensor& input);
Tensor Cosh(const Tensor& input);
Tensor CumSum(const Tensor& x, const Tensor& axis, int exclusive, int reverse);
Tensor DequantizeLinear(const Tensor& x, const Tensor& x_scale, const Tensor& x_zero_point, int axis);
Tensor Det(const Tensor& X);
Tensor Div(const Tensor& A, const Tensor& B);
Tensor Elu(const Tensor& X, float alpha);
Tensor Equal(const Tensor& A, const Tensor& B);
Tensor Erf(const Tensor& input);
Tensor Exp(const Tensor& input);
Tensor Expand(const Tensor& input, const Tensor& shape);
Tensor EyeLike(const Tensor& input, int dtype, int k);
Tensor Flatten(const Tensor& input, int axis);
Tensor Floor(const Tensor& X);
Tensor Gather(const Tensor& data, const Tensor& indices, int axis);
Tensor GatherElements(const Tensor& data, const Tensor& indices, int axis);
Tensor GatherND(const Tensor& data, const Tensor& indices, int batch_dims);
Tensor Gemm(const Tensor& A, const Tensor& B, const Tensor& C, float alpha, float beta, int transA, int transB);
Tensor GlobalAveragePool(const Tensor& X);
Tensor GlobalLpPool(const Tensor& X, int p);
Tensor GlobalMaxPool(const Tensor& X);
Tensor Greater(const Tensor& A, const Tensor& B);
Tensor GreaterOrEqual(const Tensor& A, const Tensor& B);
Tensor Hardmax(const Tensor& input, int axis);
Tensor HardSigmoid(const Tensor& X, float alpha, float beta);
Tensor HardSwish(const Tensor& X);
Tensor Identity(const Tensor& input);
Tensor InstanceNormalization(const Tensor& input, const Tensor& scale, const Tensor& B, float epsilon);
Tensor IsInf(const Tensor& X, int detect_negative, int detect_positive);
Tensor IsNaN(const Tensor& X);
Tensor LeakyRelu(const Tensor& X, float alpha);
Tensor Less(const Tensor& A, const Tensor& B);
Tensor LessOrEqual(const Tensor& A, const Tensor& B);
Tensor Log(const Tensor& input);
Tensor LogSoftmax(const Tensor& input, int axis);
Tensor LpNormalization(const Tensor& input, int axis, int p);
Tensor LRN(const Tensor& X, float alpha, float beta, float bias, int size);
Tensor MatMul(const Tensor& A, const Tensor& B);
Tensor MatMulInteger(const Tensor& A, const Tensor& B, const Tensor& a_zero_point, const Tensor& b_zero_point);
Tensor Max(const Tensor& data_0);
Tensor Mean(const Tensor& data_0);
Tensor Min(const Tensor& data_0);
Tensor Mod(const Tensor& A, const Tensor& B, int fmod);
Tensor Mul(const Tensor& A, const Tensor& B);
Tensor Multinomial(const Tensor& input, int dtype, int sample_size, float seed);
Tensor Neg(const Tensor& X);
Tensor NonMaxSuppression(const Tensor& boxes, const Tensor& scores, const Tensor& max_output_boxes_per_class, const Tensor& iou_threshold, const Tensor& score_threshold, int center_point_box);
Tensor NonZero(const Tensor& X);
Tensor Not(const Tensor& X);
Tensor OneHot(const Tensor& indices, const Tensor& depth, const Tensor& values, int axis);
Tensor OptionalGetElement(const Tensor& input);
Tensor OptionalHasElement(const Tensor& input);
Tensor Or(const Tensor& A, const Tensor& B);
Tensor Pow(const Tensor& X, const Tensor& Y);
Tensor PRelu(const Tensor& X, const Tensor& slope);
Tensor QLinearMatMul(const Tensor& a, const Tensor& a_scale, const Tensor& a_zero_point, const Tensor& b, const Tensor& b_scale, const Tensor& b_zero_point, const Tensor& y_scale, const Tensor& y_zero_point);
Tensor QuantizeLinear(const Tensor& x, const Tensor& y_scale, const Tensor& y_zero_point, int axis);
Tensor RandomNormalLike(const Tensor& input, int dtype, float mean, float scale, float seed);
Tensor RandomUniformLike(const Tensor& input, int dtype, float high, float low, float seed);
Tensor Range(const Tensor& start, const Tensor& limit, const Tensor& delta);
Tensor Reciprocal(const Tensor& X);
Tensor ReduceSum(const Tensor& data, const Tensor& axes, int keepdims, int noop_with_empty_axes);
Tensor Relu(const Tensor& X);
Tensor Reshape(const Tensor& data, const Tensor& shape, int allowzero);
Tensor ReverseSequence(const Tensor& input, const Tensor& sequence_lens, int batch_axis, int time_axis);
Tensor Round(const Tensor& X);
Tensor Scatter(const Tensor& data, const Tensor& indices, const Tensor& updates, int axis);
Tensor ScatterElements(const Tensor& data, const Tensor& indices, const Tensor& updates, int axis);
Tensor ScatterND(const Tensor& data, const Tensor& indices, const Tensor& updates);
Tensor Selu(const Tensor& X, float alpha, float gamma);
Tensor SequenceAt(const Tensor& input_sequence, const Tensor& position);
Tensor SequenceConstruct(const Tensor& inputs);
Tensor SequenceErase(const Tensor& input_sequence, const Tensor& position);
Tensor SequenceInsert(const Tensor& input_sequence, const Tensor& tensor, const Tensor& position);
Tensor SequenceLength(const Tensor& input_sequence);
Tensor Shape(const Tensor& data, int end, int start);
Tensor Shrink(const Tensor& input, float bias, float lambd);
Tensor Sigmoid(const Tensor& X);
Tensor Sign(const Tensor& input);
Tensor Sin(const Tensor& input);
Tensor Sinh(const Tensor& input);
Tensor Size(const Tensor& data);
Tensor Slice(const Tensor& data, const Tensor& starts, const Tensor& ends, const Tensor& axes, const Tensor& steps);
Tensor Softmax(const Tensor& input, int axis);
Tensor Softplus(const Tensor& X);
Tensor Softsign(const Tensor& input);
Tensor SpaceToDepth(const Tensor& input, int blocksize);
Tensor Split(const Tensor& input, const Tensor& split, int axis);
Tensor SplitToSequence(const Tensor& input, const Tensor& split, int axis, int keepdims);
Tensor Sqrt(const Tensor& X);
Tensor Squeeze(const Tensor& data, const Tensor& axes);
Tensor Sub(const Tensor& A, const Tensor& B);
Tensor Sum(const Tensor& data_0);
Tensor Tan(const Tensor& input);
Tensor Tanh(const Tensor& input);
Tensor ThresholdedRelu(const Tensor& X, float alpha);
Tensor Tile(const Tensor& input, const Tensor& repeats);
Tensor Trilu(const Tensor& input, const Tensor& k, int upper);
Tensor Unsqueeze(const Tensor& data, const Tensor& axes);
Tensor Where(const Tensor& condition, const Tensor& X, const Tensor& Y);
Tensor Xor(const Tensor& A, const Tensor& B);
