// This file is auto-generated by wgsl-gen. Do not edit manually.

#pragma once
#ifndef INCLUDED_BY_WGSL_GEN_IMPL
#error "This file is expected to be included by wgsl-gen impl. Do not include it directly."
#endif

// Helper functions or macros

#pragma push_macro("MainFunctionStart")
#undef MainFunctionStart
#define MainFunctionStart() { [[maybe_unused]] auto& ss = shader_helper.MainFunctionBody();
#pragma push_macro("MainFunctionEnd")
#undef MainFunctionEnd
#define MainFunctionEnd() }

// Helper templates

namespace wgsl_detail {
template <typename T, typename = std::enable_if_t<std::is_integral_v<T>>>
std::string pass_as_string(T&& v) {
  return std::to_string(std::forward<T>(v));
}
template <typename...>
std::string_view pass_as_string(std::string_view sv) {
  return sv;
}
template <typename T>
std::string pass_as_string(T&& v) {
  return std::forward<T>(v);
}
}  // namespace wgsl_detail

#include "wgsl_template_gen/string_table.h"  // 8a3467da11bdd0f05c6f5b96c3df78064e0eb9f86af37a75c12c1f6aee7039c9

// Include template implementations

#include "wgsl_template_gen/generated/math/subgroup_matrix_gemm_8x16x16.h"  // 4f8008bad05ac6a019e49167bb36c2fee3bf6403bc73a493a4d17b002b334f6a
#include "wgsl_template_gen/generated/math/subgroup_matrix_matmul_8x16x16.h"  // c466fe3e1999d7baa59f1f409e0262db0be5bf0e455219fd542f62573cfcdf55
#include "wgsl_template_gen/generated/nn/im2col_matmul.h"  // 1e13f02816800345904fc11706e7930ed592c7d604b5db8ca61959481c052763
#include "wgsl_template_gen/generated/tensor/oihw_to_ohwi.h"  // 654d3d1ec3538a83cdff712a4a8a8bec690c32f97a733e3ca6eb4dd1098692a3
#include "wgsl_template_gen/generated/tensor/pad.h"  // f76f7b5aa6e6894c504bb1173e7daeb930612d38ae0b316b51791029de613a69

#pragma pop_macro("MainFunctionStart")
#pragma pop_macro("MainFunctionEnd")