require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

def shared

  use_react_native!(:path => '../node_modules/react-native')

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  ort_c_local_pod_path = ENV['ORT_C_LOCAL_POD_PATH']
  if ort_c_local_pod_path != nil
    print 'Using onnxruntime-c pod at ', ort_c_local_pod_path, "\n"
    pod 'onnxruntime-c', :path => ort_c_local_pod_path
  else
    pod 'onnxruntime-c'
  end

  inherit! :search_paths
end

target 'OnnxruntimeModule' do
  shared
end

target 'OnnxruntimeModuleTest' do
  shared
end
