require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

def shared
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  ort_c_local_pod_path = ENV['ORT_C_LOCAL_POD_PATH']
  if ort_c_local_pod_path != nil
    print 'Using onnxruntime-c pod at ', ort_c_local_pod_path, "\n"
    pod 'onnxruntime-c', :path => ort_c_local_pod_path
  else
    pod 'onnxruntime-c'
  end

  inherit! :search_paths
end

target 'OnnxruntimeModule' do
  shared
end

target 'OnnxruntimeModuleTest' do
  shared
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
    end
  end
end