// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "Windows.Foundation.idl";
import "dualapipartitionattribute.idl";
import "Windows.AI.MachineLearning.idl";

#include <sdkddkver.h>

namespace Microsoft.AI.MachineLearning.Experimental {

  [threading(both)]
  [marshaling_behavior(agile)]
  [dualapipartition(1)]
  runtimeclass Dummy {
    Dummy();

    void Test();
  }
}  // namespace Microsoft.AI.MachineLearning.Experimental