#-------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#--------------------------------------------------------------------------

FROM ubuntu:18.04

ARG PYTHON_VERSION=3.6
ARG ONNXRUNTIME_REPO=https://github.com/Microsoft/onnxruntime
ARG ONNXRUNTIME_SERVER_BRANCH=master

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y sudo git bash

ENV PATH="/opt/cmake/bin:${PATH}"
RUN git clone --single-branch --branch ${ONNXRUNTIME_SERVER_BRANCH} --recursive ${ONNXRUNTIME_REPO} onnxruntime
RUN /onnxruntime/tools/ci_build/github/linux/docker/scripts/install_ubuntu.sh -p ${PYTHON_VERSION} && \
    /onnxruntime/tools/ci_build/github/linux/docker/scripts/install_os_deps.sh && \
    /onnxruntime/tools/ci_build/github/linux/docker/scripts/install_python_deps.sh -p ${PYTHON_VERSION}

WORKDIR /

RUN mkdir -p /onnxruntime/build && \
    pip3 install sympy packaging cpufeature jupyter && \
    python3 /onnxruntime/tools/ci_build/build.py --build_dir /onnxruntime/build --update --build --config Release --build_shared_lib --skip_submodule_sync --build_wheel --parallel --use_nuphar && \
    rm -rf /tmp/* && \
    rm -rf /home/root/* && \
    pip3 install /onnxruntime/build/Release/dist/onnxruntime_nuphar-*.whl && \
    rm -rf /onnxruntime
