#!/usr/bin/env python3
"""Kernel-level (CUDA-event) head-vs-base A/B benchmark for microsoft/onnxruntime#31988
(MatMulNBits M=1 cols_per_block occupancy selection), one level deeper than run_ab_sweep.py.

run_ab_sweep.py timed onnxruntime_perf_test.exe's own end-to-end "Latency" (Session::Run(),
including graph/IOBinding overhead); on the A10 CI runner that signal was noise-dominated
(head/base A/B geomean 1.006, statistically indistinguishable from the A/A structural
controls' own run-to-run spread). This script instead times *only* the kernel launch via a
new validation-only hook in matmul_4bits_m1_impl.cuh
(ORT_MATMULNBITS_M1_KERNEL_AB_BENCH=1 + _ARM_A/_ARM_B/_TARGET_SAMPLES), which:
  - alternates cols_per_block between two candidate arms on every single kernel-launch call,
    via a fixed-seed PRNG living inside the CUDA provider module itself (interleaved A/B
    within one onnxruntime_perf_test.exe process -- no second process/build needed to
    interleave), and
  - times each call with a persistent, reused cudaEvent_t pair (elapsed time read back with
    cudaEventElapsedTime; only the launch is inside the timed region, not the rest of
    Session::Run()), and
  - self-reports one MATMULNBITS_M1_KERNEL_AB_RESULT line per (shape, bucket_cols) to stderr
    once ORT_MATMULNBITS_M1_KERNEL_AB_TARGET_SAMPLES timed calls have been collected, entirely
    from inside the CUDA provider module (no build-time link dependency from
    onnxruntime_perf_test.exe onto onnxruntime_providers_cuda is required either way, since
    onnxruntime_providers_cuda is loaded as a runtime plugin).

For each (shape, arm_a, arm_b) triple this script drives onnxruntime_perf_test.exe for enough
repeats to comfortably clear the target sample count, captures stderr, and parses out the
printed HEADER/RESULT lines into a CSV. Includes both genuine narrow-n A/B triples (arm_a=8
baseline vs arm_b=2 or 4, the PR's own selection) and explicit A/A triples at the *same* shape
(arm_a=8, arm_b=8) to characterize the per-shape kernel-launch noise floor, plus wide-n
structural-control triples (arm_a=8, arm_b=8, where ChooseColsPerBlockFromOccupancy's
short-circuit means the "real" selection is also unconditionally 8).

Run on the actual CI GPU runner; not intended to run locally without a CUDA device.
"""
import argparse
import csv
import os
import re
import subprocess
import sys

import numpy as np

HEADER_RE = re.compile(
    r"MATMULNBITS_M1_KERNEL_AB_HEADER n=(\d+) arm_a_requested=(-?\d+) arm_a_effective=(\d+) "
    r"arm_b_requested=(-?\d+) arm_b_effective=(\d+) target_samples=(\d+)"
)
RESULT_RE = re.compile(
    r'MATMULNBITS_M1_KERNEL_AB_RESULT n=(\d+) k=(\d+) block_size=(\d+) sm_count=(\d+) gpu="([^"]*)" '
    r"cc=(\d+)\.(\d+) clock_khz_start=(-?\d+) clock_khz_end=(-?\d+) bucket_cols=(\d+) count=(\d+) "
    r"mean_us=([0-9.]+) p50_us=([0-9.]+) p90_us=([0-9.]+) p95_us=([0-9.]+) min_us=([0-9.]+) max_us=([0-9.]+)"
)

# (triple_label, model_label, arm_a, arm_b, kind)
#   model_label must match one of gen_models.py's SHAPES labels (models already generated by
#   the existing "Generate MatMulNBits M1 perf-validation models" workflow step).
#   kind in {"ab", "aa_narrow", "aa_wide"} -- purely descriptive, carried through to the CSV.
TRIPLES = [
    ("n256_k4096_AB", "narrow_n256_k4096_bs128", 8, 2, "ab"),
    ("n256_k4096_AA", "narrow_n256_k4096_bs128", 8, 8, "aa_narrow"),
    ("n384_k1024_AB", "narrow_n384_k1024_bs128", 8, 4, "ab"),
    ("n384_k1024_AA", "narrow_n384_k1024_bs128", 8, 8, "aa_narrow"),
    ("n576_k1024_boundary_AA", "boundary_n576_k1024_bs128", 8, 8, "aa_wide"),
    ("n4096_k4096_wide_AA", "wide_n4096_k4096_bs128", 8, 8, "aa_wide"),
    ("n11008_k4096_wide_AA", "wide_n11008_k4096_bs128", 8, 8, "aa_wide"),
]


def run_numerics_sanity(python_exe, script_dir, models_dir, workdir):
    """Confirms the *new* ORT_MATMULNBITS_M1_KERNEL_AB_BENCH override path produces bit-
    identical output to the already-validated ORT_MATMULNBITS_M1_PERF_VALIDATION_FORCE_
    COLS_PER_BLOCK path for the same forced cols_per_block value, at both narrow shapes used
    below (n=256 -> cols 8 or 2, n=384 -> cols 8 or 4). The old mechanism's own head-vs-base
    (selected-vs-forced8) numerics were already verified bit-identical for all 12 shapes in
    the prior (session-level) validation pass; this just confirms the new instrumentation
    (which only wraps the existing dispatch with cudaEvent_t timing calls, touching no
    compute) didn't change that.
    """
    script = os.path.join(script_dir, "numerics_check.py")
    checks = [
        ("narrow_n256_k4096_bs128", 8),
        ("narrow_n256_k4096_bs128", 2),
        ("narrow_n384_k1024_bs128", 8),
        ("narrow_n384_k1024_bs128", 4),
    ]
    all_ok = True
    for model_label, cols in checks:
        model_path = os.path.join(models_dir, f"matmulnbits_m1_{model_label}.onnx")
        if not os.path.exists(model_path):
            print(f"!!! numerics sanity: missing model {model_path}", file=sys.stderr)
            all_ok = False
            continue

        old_npy = os.path.join(workdir, f"sanity_old_{model_label}_{cols}.npy")
        new_npy = os.path.join(workdir, f"sanity_new_{model_label}_{cols}.npy")

        env_old = dict(os.environ)
        env_old.pop("ORT_MATMULNBITS_M1_KERNEL_AB_BENCH", None)
        env_old["ORT_MATMULNBITS_M1_PERF_VALIDATION_FORCE_COLS_PER_BLOCK"] = str(cols)
        subprocess.run([python_exe, script, model_path, old_npy], check=True, env=env_old)

        env_new = dict(os.environ)
        env_new.pop("ORT_MATMULNBITS_M1_PERF_VALIDATION_FORCE_COLS_PER_BLOCK", None)
        env_new["ORT_MATMULNBITS_M1_KERNEL_AB_BENCH"] = "1"
        env_new["ORT_MATMULNBITS_M1_KERNEL_AB_ARM_A"] = str(cols)
        env_new["ORT_MATMULNBITS_M1_KERNEL_AB_ARM_B"] = str(cols)
        env_new["ORT_MATMULNBITS_M1_KERNEL_AB_TARGET_SAMPLES"] = "1"
        subprocess.run([python_exe, script, model_path, new_npy], check=True, env=env_new)

        old = np.load(old_npy)
        new = np.load(new_npy)
        bit_identical = np.array_equal(old, new)
        max_abs_diff = float(np.max(np.abs(old.astype(np.float64) - new.astype(np.float64))))
        status = "OK" if bit_identical else "MISMATCH"
        print(f"NUMERICS_SANITY {status} model={model_label} cols={cols} "
              f"bit_identical={bit_identical} max_abs_diff={max_abs_diff:.3e}")
        all_ok = all_ok and bit_identical
    return all_ok


def run_one(perf_test_exe, model_path, workdir, arm_a, arm_b, target_samples, repeats, tag):
    env = dict(os.environ)
    env["ORT_MATMULNBITS_M1_KERNEL_AB_BENCH"] = "1"
    env["ORT_MATMULNBITS_M1_KERNEL_AB_ARM_A"] = str(arm_a)
    env["ORT_MATMULNBITS_M1_KERNEL_AB_ARM_B"] = str(arm_b)
    env["ORT_MATMULNBITS_M1_KERNEL_AB_TARGET_SAMPLES"] = str(target_samples)
    # Make sure the (unrelated) session-level override from run_ab_sweep.py isn't also set.
    env.pop("ORT_MATMULNBITS_M1_PERF_VALIDATION_FORCE_COLS_PER_BLOCK", None)

    result_file = os.path.join(workdir, f"result_{tag}.txt")
    proc = subprocess.run(
        [perf_test_exe, "-e", "cuda", "-I", "-m", "times", "-r", str(repeats), model_path, result_file],
        env=env, capture_output=True, text=True,
    )
    log_path = os.path.join(workdir, f"{tag}.stderr.log")
    with open(log_path, "w") as f:
        f.write(proc.stdout)
        f.write("\n----- stderr -----\n")
        f.write(proc.stderr)
    if proc.returncode != 0:
        print(f"!!! onnxruntime_perf_test exited {proc.returncode} for {tag}; see {log_path}", file=sys.stderr)

    headers = [HEADER_RE.search(line) for line in proc.stderr.splitlines()]
    headers = [m for m in headers if m]
    results = [RESULT_RE.search(line) for line in proc.stderr.splitlines()]
    results = [m for m in results if m]
    return headers, results, log_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--models-dir", required=True)
    ap.add_argument("--build-dir", required=True, help="dir containing onnxruntime_perf_test.exe")
    ap.add_argument("--target-samples", type=int, default=4000)
    ap.add_argument("--repeats", type=int, default=4200, help="Session::Run() repeats (>= target-samples + warmup)")
    ap.add_argument("--out-csv", required=True)
    ap.add_argument("--skip-numerics-sanity", action="store_true")
    args = ap.parse_args()

    perf_test_exe = os.path.join(args.build_dir, "onnxruntime_perf_test.exe")
    if not os.path.exists(perf_test_exe):
        perf_test_exe = os.path.join(args.build_dir, "onnxruntime_perf_test")
    if not os.path.exists(perf_test_exe):
        raise SystemExit(f"onnxruntime_perf_test not found under {args.build_dir}")

    script_dir = os.path.dirname(os.path.abspath(__file__))
    sanity_workdir = os.path.join(args.models_dir, "_kernelbench_numerics_sanity")
    os.makedirs(sanity_workdir, exist_ok=True)
    if not args.skip_numerics_sanity:
        numerics_ok = run_numerics_sanity(sys.executable, script_dir, args.models_dir, sanity_workdir)
        if not numerics_ok:
            raise SystemExit("numerics sanity check failed -- refusing to trust timing; see NUMERICS_SANITY lines above")

    rows = []
    print(
        "triple_label,model_label,kind,n,k,block_size,sm_count,gpu,cc,arm_a_requested,arm_a_effective,"
        "arm_b_requested,arm_b_effective,target_samples,clock_khz_start,clock_khz_end,bucket_cols,count,"
        "mean_us,p50_us,p90_us,p95_us,min_us,max_us"
    )
    any_missing = False
    for triple_label, model_label, arm_a, arm_b, kind in TRIPLES:
        model_path = os.path.join(args.models_dir, f"matmulnbits_m1_{model_label}.onnx")
        workdir = os.path.join(args.models_dir, f"_kernelbench_{triple_label}")
        os.makedirs(workdir, exist_ok=True)
        if not os.path.exists(model_path):
            print(f"!!! missing model {model_path}, skipping {triple_label}", file=sys.stderr)
            any_missing = True
            continue

        headers, results, log_path = run_one(
            perf_test_exe, model_path, workdir, arm_a, arm_b, args.target_samples, args.repeats, triple_label
        )
        if not headers:
            print(f"!!! no HEADER line parsed for {triple_label}; see {log_path}", file=sys.stderr)
        if not results:
            print(f"!!! no RESULT line(s) parsed for {triple_label} (samples never reached target?); "
                  f"see {log_path}", file=sys.stderr)
            any_missing = True
            continue

        h = headers[0]
        h_n, h_arm_a_req, h_arm_a_eff, h_arm_b_req, h_arm_b_eff, h_target = h.groups()
        for m in results:
            (n, k, block_size, sm_count, gpu, cc_major, cc_minor, clock_start, clock_end,
             bucket_cols, count, mean_us, p50_us, p90_us, p95_us, min_us, max_us) = m.groups()
            line = (
                f"{triple_label},{model_label},{kind},{n},{k},{block_size},{sm_count},{gpu},"
                f"{cc_major}.{cc_minor},{h_arm_a_req},{h_arm_a_eff},{h_arm_b_req},{h_arm_b_eff},{h_target},"
                f"{clock_start},{clock_end},{bucket_cols},{count},{mean_us},{p50_us},{p90_us},{p95_us},"
                f"{min_us},{max_us}"
            )
            print(line)
            rows.append(line)

    with open(args.out_csv, "w") as f:
        f.write(
            "triple_label,model_label,kind,n,k,block_size,sm_count,gpu,cc,arm_a_requested,arm_a_effective,"
            "arm_b_requested,arm_b_effective,target_samples,clock_khz_start,clock_khz_end,bucket_cols,count,"
            "mean_us,p50_us,p90_us,p95_us,min_us,max_us\n"
        )
        for r in rows:
            f.write(r + "\n")
    print(f"\nWrote {args.out_csv}")
    if any_missing:
        raise SystemExit("one or more triples produced no usable kernel-level samples; see stderr above")


if __name__ == "__main__":
    main()
