ARG OS_VERSION=27
ARG PYTHON_VERSION=3.6
FROM fedora:${OS_VERSION}
ADD scripts /tmp/scripts
RUN cd /tmp/scripts && /tmp/scripts/install_fedora.sh && /tmp/scripts/install_deps.sh -p $PYTHON_VERSION && rm -rf /tmp/scripts

