FROM quay.io/pypa/manylinux2014_x86_64:latest

ADD scripts /tmp/scripts
RUN cd /tmp/scripts && /tmp/scripts/manylinux/install_centos.sh && /tmp/scripts/manylinux/install_deps.sh && rm -rf /tmp/scripts

# Remove existing symbolic link and python installation.
RUN rm -rf /opt/python/cp37-cp37m && rm -rf /opt/_internal/cpython-3.7.10

# Build Python.
# The --enable-shared option ensures that shared libraries are built for Python.
# Training need use Python embedding, so we need enable it.
RUN cd /usr/src && wget https://www.python.org/ftp/python/3.7.10/Python-3.7.10.tgz && tar xzf Python-3.7.10.tgz && \
    cd Python-3.7.10 && ./configure --enable-optimizations --enable-shared --prefix=/opt/_internal/cpython-3.7.10/ &&\
    make altinstall && cd .. && rm -rf Python-3.7.10

# Create symbolic link pointing to new built python installation.
RUN ln -sf /opt/_internal/cpython-3.7.10 /opt/python/cp37-cp37m && \
    ln -sf /opt/python/cp37-cp37m/bin/python3.7 /opt/python/cp37-cp37m/bin/python3 &&\
    # We do not need the Python test suites
    find ${PREFIX} -depth \( -type d -a -name test -o -name tests \) | xargs rm -rf

ARG BUILD_UID=1001
ARG BUILD_USER=onnxruntimedev
RUN adduser --uid $BUILD_UID $BUILD_USER
WORKDIR /home/$BUILD_USER
USER $BUILD_USER
ENV PATH /usr/local/gradle/bin:/opt/python/cp37-cp37m/bin:$PATH
ENV LD_LIBRARY_PATH /opt/_internal/cpython-3.7.10/lib/:$LD_LIBRARY_PATH
