FROM quay.io/pypa/manylinux1_x86_64@sha256:b5c4a09d232fda6cf60c4c28dd27eae3f845007aea3364cf2f5561d8c8e0ab68

ARG PYTHON_VERSION
ADD scripts /tmp/scripts
RUN cd /tmp/scripts && /tmp/scripts/install_centos.sh && /tmp/scripts/install_deps.sh -p $PYTHON_VERSION && rm -rf /tmp/scripts

ARG BUILD_UID=1000
ARG BUILD_USER=onnxruntimedev
RUN adduser --uid $BUILD_UID $BUILD_USER 
WORKDIR /home/$BUILD_USER
USER $BUILD_USER
