vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO bmehta001/cpp_client_telemetry
    REF 0b7b0cfb63ecc9dcdecad61e60f26957fdb01f61
    SHA512 9ba79b10a5e68f8fa5d3692b22750bc5c0cec12c6d2920bfd63ce193a26b8433923e7dbba2baeb4fd863dd64ed2fba683b0480641f88697302907385bb61f958
    HEAD_REF main
)

set(MATSDK_BUILD_APPLE_HTTP OFF)
if(VCPKG_TARGET_IS_OSX OR VCPKG_TARGET_IS_IOS)
  set(MATSDK_BUILD_APPLE_HTTP ON)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DMATSDK_USE_VCPKG_DEPS=ON
    -DMATSDK_BUILD_HEADERS=ON
    -DMATSDK_BUILD_LIBRARY=ON
    -DMATSDK_BUILD_TEST_TOOL=OFF
    -DMATSDK_BUILD_UNIT_TESTS=OFF
    -DMATSDK_BUILD_FUNC_TESTS=OFF
    -DMATSDK_BUILD_JNI_WRAPPER=OFF
    -DMATSDK_BUILD_OBJC_WRAPPER=OFF
    -DMATSDK_BUILD_SWIFT_WRAPPER=OFF
    -DMATSDK_BUILD_PACKAGE=OFF
        -DBUILD_VERSION=${VERSION}
    -DMATSDK_BUILD_APPLE_HTTP=${MATSDK_BUILD_APPLE_HTTP}
    -DMATSDK_CURL_PROVIDER=SYSTEM
    -DMATSDK_SQLITE_PROVIDER=SYSTEM
    -DMATSDK_ZLIB_PROVIDER=SYSTEM
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(PACKAGE_NAME MSTelemetry CONFIG_PATH lib/cmake/MSTelemetry)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
