#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

"""Generate the Intel subgroup-matrix MatMul tuned-config lookup table.

Input is one or more CSVs produced by the WebGpuSgMatMulTuning.SweepAndEmitCsv
gtest (columns: arch,M,N,K,tile_m,tile_n,split_k,gpu_us,wall_us,baseline_gpu_us,
baseline_wall_us,speedup). Each row is already the fastest config measured for
that (arch, M, N, K) problem; only the arch + config columns are used here (the
timing/baseline/speedup columns are informational and ignored).

Rows are grouped by the `arch` column (e.g. "xe-2lpg", "xe-3lpg") and one tuned
sub-table is emitted per architecture. Pass multiple --csv arguments to combine
sweeps from several machines/arches into a single table. Older CSVs without an
`arch` column are accepted; use --arch to label them.

Output is a C++ include file (subgroup_matrix_matmul_tuned.inc) consumed by
subgroup_matrix_matmul.cc. The kernel's SelectConfig matches the device arch
against this table (when present) before falling back to the built-in heuristic.
Each arch's table is keyed by an index into its own quantization grid, emitted
alongside the entries, so the kernel does not hardcode the grid.

Usage:
  python gen_sgmm_tuned_table.py --csv sgmm_xe2lpg.csv --csv sgmm_xe3lpg.csv \
      --out ../../onnxruntime/core/providers/webgpu/vendor/intel/math/subgroup_matrix_matmul_tuned.inc
"""

import argparse
import csv
import re
import sys
from pathlib import Path


def read_rows(csv_paths, arch_override):
    rows = []
    config_cols = {"M", "N", "K", "tile_m", "tile_n", "split_k"}
    for csv_path in csv_paths:
        with open(csv_path, newline="") as f:
            reader = csv.DictReader(f)
            fieldnames = set(reader.fieldnames or [])
            if not config_cols.issubset(fieldnames):
                missing = config_cols - fieldnames
                sys.exit(f"{csv_path} is missing required columns: {sorted(missing)}")
            has_arch = "arch" in fieldnames
            if not has_arch and not arch_override:
                sys.exit(
                    f"{csv_path} has no 'arch' column; pass --arch to label it "
                    "(e.g. --arch xe-2lpg)."
                )
            for r in reader:
                arch = (r["arch"].strip() if has_arch else "") or arch_override
                if not arch:
                    sys.exit(f"{csv_path} has an empty 'arch' value; pass --arch to override.")
                rows.append(
                    {
                        "arch": arch,
                        "M": int(r["M"]),
                        "N": int(r["N"]),
                        "K": int(r["K"]),
                        "tile_m": int(r["tile_m"]),
                        "tile_n": int(r["tile_n"]),
                        "split_k": int(r["split_k"]),
                    }
                )
    if not rows:
        sys.exit("CSV(s) contained no data rows.")
    return rows


def group_by_arch(rows):
    by_arch = {}
    for r in rows:
        by_arch.setdefault(r["arch"], []).append(r)
    return by_arch


def build_grid(rows):
    # The quantization grid is the sorted union of every sampled dimension. At
    # runtime a problem dimension maps to the smallest grid value >= it.
    values = set()
    for r in rows:
        values.update((r["M"], r["N"], r["K"]))
    return sorted(values)


def sanitize_ident(arch):
    # "xe-2lpg" -> "arch_xe_2lpg" (valid C++ namespace identifier).
    ident = re.sub(r"[^0-9a-zA-Z]+", "_", arch).strip("_").lower()
    return f"arch_{ident}" if ident else "arch_unknown"


def cpp_string_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def assign_arch_idents(by_arch):
    # Map each arch to a unique C++ namespace identifier (deterministic order).
    arch_idents = {}
    used = set()
    for arch in sorted(by_arch):
        ident = sanitize_ident(arch)
        base = ident
        suffix = 1
        while ident in used:
            suffix += 1
            ident = f"{base}_{suffix}"
        used.add(ident)
        arch_idents[arch] = ident
    return arch_idents


def emit(by_arch):
    lines = []
    lines.append("// Auto-generated by tools/python/gen_sgmm_tuned_table.py. Do not edit.")
    lines.append("// Source: offline WebGpuSgMatMulTuning sweeps, one table per GPU architecture.")
    lines.append("")
    lines.append("namespace sgmm_tuned {")
    lines.append("")
    lines.append("struct Entry {")
    lines.append("  uint16_t mi;  // index into the arch grid for M")
    lines.append("  uint16_t ni;  // index into the arch grid for N")
    lines.append("  uint16_t ki;  // index into the arch grid for K")
    lines.append("  uint16_t tile_m;")
    lines.append("  uint16_t tile_n;")
    lines.append("  uint16_t split_k;")
    lines.append("};")
    lines.append("")
    lines.append("struct ArchTable {")
    lines.append("  std::string_view arch;")
    lines.append("  const uint32_t* grid;")
    lines.append("  size_t grid_count;")
    lines.append("  const Entry* entries;")
    lines.append("  size_t entry_count;")
    lines.append("};")
    lines.append("")

    arch_idents = assign_arch_idents(by_arch)

    # Per-arch deduplicated entries and grids, computed once and reused below.
    arch_data = {}
    total_entries = 0
    for arch in sorted(by_arch):
        rows = by_arch[arch]
        grid = build_grid(rows)
        index_of = {v: i for i, v in enumerate(grid)}
        # Deduplicate on (M,N,K); keep the last occurrence (latest tuning wins).
        best = {}
        for r in rows:
            best[(r["M"], r["N"], r["K"])] = r
        arch_data[arch] = (grid, index_of, best)
        total_entries += len(best)

    for arch in sorted(by_arch):
        grid, index_of, best = arch_data[arch]
        ident = arch_idents[arch]
        lines.append(f"namespace {ident} {{  // arch: {arch}")
        grid_str = ", ".join(str(v) for v in grid)
        lines.append(f"constexpr uint32_t kGrid[] = {{{grid_str}}};")
        lines.append("constexpr Entry kEntries[] = {")
        for (m, n, k), r in sorted(best.items()):
            lines.append(
                f"    {{{index_of[m]}, {index_of[n]}, {index_of[k]}, "
                f"{r['tile_m']}, {r['tile_n']}, {r['split_k']}}},"
            )
        lines.append("};")
        lines.append(f"}}  // namespace {ident}")
        lines.append("")

    lines.append("constexpr ArchTable kArchTables[] = {")
    for arch in sorted(by_arch):
        grid, _, best = arch_data[arch]
        ident = arch_idents[arch]
        lines.append(
            f'    {{"{cpp_string_escape(arch)}", {ident}::kGrid, {len(grid)}, '
            f"{ident}::kEntries, {len(best)}}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace sgmm_tuned")
    lines.append("")
    return "\n".join(lines), total_entries


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--csv", required=True, action="append", help="Tuning CSV from the autotuner gtest (repeatable)."
    )
    parser.add_argument(
        "--arch", default=None, help="Architecture label for CSV(s) lacking an 'arch' column (e.g. xe-2lpg)."
    )
    parser.add_argument("--out", required=True, help="Output .inc path.")
    args = parser.parse_args()

    rows = read_rows(args.csv, args.arch)
    by_arch = group_by_arch(rows)
    content, total_entries = emit(by_arch)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    arch_summary = ", ".join(f"{a}={len(by_arch[a])}" for a in sorted(by_arch))
    print(f"Wrote {total_entries} tuned entries across {len(by_arch)} arch(es) [{arch_summary}] to {out_path}")


if __name__ == "__main__":
    main()
