/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_onnxruntime_OrtAllocator */

#ifndef _Included_ai_onnxruntime_OrtAllocator
#define _Included_ai_onnxruntime_OrtAllocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_onnxruntime_OrtAllocator
 * Method:    closeAllocator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_onnxruntime_OrtAllocator_closeAllocator
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
