#
# This file is autogenerated by pip-compile with python 3.9
# To update, run:
#
#    pip-compile --generate-hashes --output-file=docker/build_scripts/requirements-tools/cmake .nox/tools/tmp/cmake.in
#
cmake==3.21.1.post1 \
    --hash=sha256:1cf061e78e9a16f7f40f768f12d806483fe0eee7c1f9eeb4766610cb9122cb73 \
    --hash=sha256:1d637b7153d337c118df79aca9189f8c44d4200f0c99d2aaf021d7696a535f9a \
    --hash=sha256:2fc534f714347c2bfca7b15a0004f224f61164658130f33402341e10a5188658 \
    --hash=sha256:4b8c1810b2defc30b35b8973aec5d8055038fde1e9df984812e09a290d4b65a3 \
    --hash=sha256:9e21f75ba51b04f7fa8cbf6965bfb194db32f4b04eb7757c312a621c0a4dd847 \
    --hash=sha256:a3f32247ef6000616585ab847bcb367787606ad33ab34f64dcfc85d304dafea9 \
    --hash=sha256:aaea4911f6fccaf5a84110b2c9d4b5d99e9792112199ca25408c635bd2fd8584 \
    --hash=sha256:caa81c3f3985b552bc2e38fb339ba84c0c237441d508f4de01d44a2948eddd36 \
    --hash=sha256:e000ef5d4893ceaec852f468d6adc7698ca08ebaecb6df38d81ceed32b4ad9e3
    # via -r .nox/tools/tmp/cmake.in
