require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

target 'OnnxruntimeModuleExample' do
  config = use_native_modules!

  if config["reactNativePath"] != nil
    use_react_native!(:path => config["reactNativePath"])
  else
    use_react_native!(:path => '../node_modules/react-native')
  end

  use_frameworks!

  ort_c_local_pod_path = ENV['ORT_C_LOCAL_POD_PATH']
  if ort_c_local_pod_path != nil
    print 'Using onnxruntime-c pod at ', ort_c_local_pod_path, "\n"
    pod 'onnxruntime-c', :path => ort_c_local_pod_path
  end
  pod 'onnxruntime-react-native', :path => '../node_modules/onnxruntime-react-native'

  inherit! :search_paths
end
