package ml.microsoft.onnxruntime;

public enum ErrorCode {
  OK,
  FAIL,
  INVALID_ARGUMENT,
  NO_SUCHFILE,
  NO_MODEL,
  ENGINE_ERROR,
  RUNTIME_EXCEPTION,
  INVALID_PROTOBUF,
  MODEL_LOADED,
  NOT_IMPLEMENTED,
  INVALID_GRAPH,
  SHAPE_INFERENCE_NOT_REGISTERED,
  REQUIREMENT_NOT_REGISTERED,
}
