#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

"""Build a custom static ONNX Runtime XCFramework for iOS on macOS."""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import shlex
import shutil
import subprocess
import sys
import textwrap

SCRIPT_DIR = pathlib.Path(__file__).parent.resolve()
OFFICIAL_REPO = "https://github.com/microsoft/onnxruntime.git"


def run(
    command: list[str],
    **kwargs,
) -> subprocess.CompletedProcess:
    """Run a command and fail immediately if it returns a non-zero exit code."""

    printable_command = [str(value) for value in command]

    print(f"Running command:\n  {shlex.join(printable_command)}")

    kwargs["check"] = True

    return subprocess.run(
        printable_command,
        **kwargs,
    )  # noqa: PLW1510


def sha256_file(path: pathlib.Path) -> str:
    """Calculate the SHA-256 checksum of a file."""

    digest = hashlib.sha256()

    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)

    return digest.hexdigest()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=textwrap.dedent(
            """
            Builds a custom static ONNX Runtime XCFramework for iOS.

            The build uses ONNX Runtime's build_apple_framework.py helper and
            must run on macOS with Xcode installed.

            Outputs are placed under:

                <working_dir>/output/ios/framework_out

            A distributable ZIP, SHA-256 checksum, build metadata file, and
            Swift Package manifest are generated by default.
            """
        ).strip()
    )

    parser.add_argument(
        "working_dir",
        type=pathlib.Path,
        help="Directory used for source, intermediate build files, and outputs.",
    )

    parser.add_argument(
        "--onnxruntime_branch_or_tag",
        default="main",
        help="ONNX Runtime branch or tag to build. Defaults to main.",
    )

    parser.add_argument(
        "--onnxruntime_repo_url",
        default=OFFICIAL_REPO,
        help="ONNX Runtime Git repository URL.",
    )

    parser.add_argument(
        "--onnxruntime_source_dir",
        type=pathlib.Path,
        help=(
            "Use an existing ONNX Runtime checkout instead of cloning the "
            "repository into the working directory."
        ),
    )

    parser.add_argument(
        "--include_ops_by_config",
        type=pathlib.Path,
        help=(
            "Optional reduced-operator configuration generated during "
            "ONNX-to-ORT model conversion."
        ),
    )

    parser.add_argument(
        "--build_settings",
        type=pathlib.Path,
        required=True,
        help=(
            "JSON configuration passed to ONNX Runtime's "
            "build_apple_framework.py script."
        ),
    )

    parser.add_argument(
        "--config",
        choices=[
            "Debug",
            "MinSizeRel",
            "Release",
            "RelWithDebInfo",
        ],
        default="Release",
        help="Build configuration. Defaults to Release.",
    )

    parser.add_argument(
        "--dynamic_framework",
        action="store_true",
        help=(
            "Build a dynamic framework. Static is the default and is generally "
            "recommended for SDK embedding."
        ),
    )

    parser.add_argument(
        "--path_to_protoc_exe",
        type=pathlib.Path,
        help="Optional path to a host protoc executable.",
    )

    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete the previous iOS build directory before building.",
    )

    parser.add_argument(
        "--skip_archive",
        action="store_true",
        help=(
            "Do not create the XCFramework ZIP, checksum, metadata, or "
            "Package.swift file."
        ),
    )

    parser.add_argument(
        "--package_name",
        default="onnxruntime-ios-custom",
        help="Base name used for the generated package and archive.",
    )

    parser.add_argument(
        "--binary_url",
        help=(
            "Optional public URL for the generated ZIP. When supplied, the "
            "generated Package.swift uses a remote binary target."
        ),
    )

    args = parser.parse_args()

    if sys.platform != "darwin":
        parser.error(
            "The iOS build must run on macOS with Xcode installed."
        )

    if not args.build_settings.is_file():
        parser.error(
            f"--build_settings is not a file: {args.build_settings}"
        )

    if (
        args.include_ops_by_config is not None
        and not args.include_ops_by_config.is_file()
    ):
        parser.error(
            "--include_ops_by_config is not a file: "
            f"{args.include_ops_by_config}"
        )

    if (
        args.path_to_protoc_exe is not None
        and not args.path_to_protoc_exe.is_file()
    ):
        parser.error(
            f"--path_to_protoc_exe is not a file: "
            f"{args.path_to_protoc_exe}"
        )

    if (
        args.onnxruntime_source_dir is not None
        and not args.onnxruntime_source_dir.is_dir()
    ):
        parser.error(
            "--onnxruntime_source_dir is not a directory: "
            f"{args.onnxruntime_source_dir}"
        )

    return args


def validate_build_environment() -> None:
    """Validate the minimum tools required for an Apple framework build."""

    required_tools = [
        "git",
        "xcodebuild",
        "cmake",
    ]

    missing_tools = [
        tool
        for tool in required_tools
        if shutil.which(tool) is None
    ]

    if missing_tools:
        raise RuntimeError(
            "Missing required build tools: "
            + ", ".join(missing_tools)
        )

    run(
        [
            "xcodebuild",
            "-version",
        ]
    )


def resolve_source(
    args: argparse.Namespace,
    working_dir: pathlib.Path,
) -> pathlib.Path:
    """Resolve an existing checkout or clone ONNX Runtime."""

    if args.onnxruntime_source_dir:
        source_dir = args.onnxruntime_source_dir.resolve()

        apple_build_script = (
            source_dir
            / "tools"
            / "ci_build"
            / "github"
            / "apple"
            / "build_apple_framework.py"
        )

        if not apple_build_script.is_file():
            raise RuntimeError(
                f"Not a valid ONNX Runtime checkout: {source_dir}"
            )

        return source_dir

    source_dir = working_dir / "source" / "onnxruntime"

    if source_dir.exists():
        print(
            "Using existing ONNX Runtime checkout at "
            f"'{source_dir}'."
        )

        run(
            [
                "git",
                "fetch",
                "--tags",
                "--prune",
                "origin",
            ],
            cwd=source_dir,
        )

        run(
            [
                "git",
                "checkout",
                "--force",
                args.onnxruntime_branch_or_tag,
            ],
            cwd=source_dir,
        )

        run(
            [
                "git",
                "submodule",
                "sync",
                "--recursive",
            ],
            cwd=source_dir,
        )

        run(
            [
                "git",
                "submodule",
                "update",
                "--init",
                "--recursive",
            ],
            cwd=source_dir,
        )
    else:
        source_dir.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        run(
            [
                "git",
                "clone",
                "--branch",
                args.onnxruntime_branch_or_tag,
                "--recurse-submodules",
                args.onnxruntime_repo_url,
                str(source_dir),
            ]
        )

    return source_dir


def copy_build_inputs(
    args: argparse.Namespace,
    working_dir: pathlib.Path,
) -> tuple[pathlib.Path, pathlib.Path | None]:
    """Copy build configuration files into the isolated working directory."""

    input_dir = working_dir / "input"

    input_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    settings_copy = input_dir / args.build_settings.name

    shutil.copy2(
        args.build_settings.resolve(),
        settings_copy,
    )

    ops_copy: pathlib.Path | None = None

    if args.include_ops_by_config:
        ops_copy = input_dir / args.include_ops_by_config.name

        shutil.copy2(
            args.include_ops_by_config.resolve(),
            ops_copy,
        )

    return settings_copy, ops_copy


def write_package_swift(
    output_dir: pathlib.Path,
    package_name: str,
    checksum: str,
    binary_url: str | None,
) -> None:
    """Generate a Swift Package manifest for the resulting XCFramework."""

    target_name = "onnxruntime"

    if binary_url:
        binary_target = (
            f'.binaryTarget(\n'
            f'            name: "{target_name}",\n'
            f'            url: "{binary_url}",\n'
            f'            checksum: "{checksum}"\n'
            f"        )"
        )
    else:
        binary_target = (
            f'.binaryTarget(\n'
            f'            name: "{target_name}",\n'
            f'            path: '
            f'"framework_out/onnxruntime.xcframework"\n'
            f"        )"
        )

    package_contents = f"""// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "{package_name}",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(
            name: "{target_name}",
            targets: [
                "{target_name}"
            ]
        )
    ],
    targets: [
        {binary_target}
    ]
)
"""

    package_file = output_dir / "Package.swift"

    package_file.write_text(
        package_contents,
        encoding="utf-8",
    )


def archive_outputs(
    output_dir: pathlib.Path,
    framework_out: pathlib.Path,
    package_name: str,
    revision: str,
    config: str,
    binary_url: str | None,
) -> pathlib.Path:
    """Archive the XCFramework and generate package metadata."""

    archive_base = output_dir / package_name

    archive_path = pathlib.Path(
        shutil.make_archive(
            str(archive_base),
            "zip",
            framework_out.parent,
            framework_out.name,
        )
    )

    checksum = sha256_file(archive_path)

    checksum_file = pathlib.Path(
        f"{archive_path}.sha256"
    )

    checksum_file.write_text(
        f"{checksum}  {archive_path.name}\n",
        encoding="utf-8",
    )

    metadata = {
        "package": package_name,
        "platform": "ios",
        "configuration": config,
        "onnxruntime_revision": revision,
        "archive": archive_path.name,
        "sha256": checksum,
        "framework": (
            "framework_out/onnxruntime.xcframework"
        ),
        "binary_url": binary_url,
    }

    metadata_file = output_dir / "build-metadata.json"

    metadata_file.write_text(
        json.dumps(
            metadata,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    write_package_swift(
        output_dir=output_dir,
        package_name=package_name,
        checksum=checksum,
        binary_url=binary_url,
    )

    swift_package_information = output_dir / "SWIFT_PACKAGE_ARCHIVE.txt"

    swift_package_information.write_text(
        (
            f"archive={archive_path.name}\n"
            f"checksum={checksum}\n"
        ),
        encoding="utf-8",
    )

    return archive_path


def build_ios_framework(
    args: argparse.Namespace,
    source_dir: pathlib.Path,
    settings_file: pathlib.Path,
    ops_config_file: pathlib.Path | None,
    build_dir: pathlib.Path,
) -> pathlib.Path:
    """Run ONNX Runtime's Apple XCFramework build helper."""

    build_script = (
        source_dir
        / "tools"
        / "ci_build"
        / "github"
        / "apple"
        / "build_apple_framework.py"
    )

    if not build_script.is_file():
        raise RuntimeError(
            "Unable to locate ONNX Runtime Apple build script at "
            f"'{build_script}'."
        )

    command = [
        sys.executable,
        str(build_script),
        f"--build_dir={build_dir}",
        f"--config={args.config}",
    ]

    if args.dynamic_framework:
        command.append(
            "--build_dynamic_framework"
        )

    if ops_config_file:
        command.append(
            f"--include_ops_by_config={ops_config_file}"
        )

    if args.path_to_protoc_exe:
        command.append(
            "--path_to_protoc_exe="
            f"{args.path_to_protoc_exe.resolve()}"
        )

    command.append(
        str(settings_file)
    )

    run(
        command,
        cwd=source_dir,
    )

    framework_out = build_dir / "framework_out"

    expected_framework = (
        framework_out
        / "onnxruntime.xcframework"
    )

    if not expected_framework.is_dir():
        raise RuntimeError(
            "Expected XCFramework was not produced at "
            f"'{expected_framework}'."
        )

    return framework_out


def main() -> None:
    args = parse_args()

    validate_build_environment()

    working_dir = args.working_dir.resolve()

    working_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    source_dir = resolve_source(
        args,
        working_dir,
    )

    settings_file, ops_config_file = copy_build_inputs(
        args,
        working_dir,
    )

    build_dir = (
        working_dir
        / "build"
        / "ios"
    )

    output_dir = (
        working_dir
        / "output"
        / "ios"
    )

    if args.clean and build_dir.exists():
        print(
            f"Removing existing build directory '{build_dir}'."
        )

        shutil.rmtree(build_dir)

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    built_framework_out = build_ios_framework(
        args=args,
        source_dir=source_dir,
        settings_file=settings_file,
        ops_config_file=ops_config_file,
        build_dir=build_dir,
    )

    destination = output_dir / "framework_out"

    if destination.exists():
        shutil.rmtree(destination)

    shutil.copytree(
        built_framework_out,
        destination,
        symlinks=True,
    )

    revision_result = run(
        [
            "git",
            "rev-parse",
            "HEAD",
        ],
        cwd=source_dir,
        capture_output=True,
        text=True,
    )

    revision = revision_result.stdout.strip()

    resulting_framework = (
        destination
        / "onnxruntime.xcframework"
    )

    print(
        "Finished building iOS XCFramework at "
        f"'{resulting_framework}'."
    )

    if not args.skip_archive:
        archive_path = archive_outputs(
            output_dir=output_dir,
            framework_out=destination,
            package_name=args.package_name,
            revision=revision,
            config=args.config,
            binary_url=args.binary_url,
        )

        print(
            "Created iOS package archive at "
            f"'{archive_path}'."
        )


if __name__ == "__main__":
    main()
