parameters:
  CudaVersion:
    type: object


stages:
- ${{ each cuda_version in parameters.CudaVersion }}:
  - stage: Jar_Packaging_GPU_${{cuda_version.key}}
    dependsOn:
    - Linux_C_API_Packaging_GPU_${{cuda_version.key}}
    - Windows_Packaging_CUDA_${{cuda_version.key}}
    - Windows_Packaging_TensorRT_${{cuda_version.key}}
    jobs:
    - job: Jar_Packaging_GPU
      workspace:
        clean: all
      templateContext:
        inputs:
        - input: pipelineArtifact
          artifactName: drop-onnxruntime-java-win-x64-tensorrt-${{cuda_version.key}}
          targetPath: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64'

        - input: pipelineArtifact
          artifactName: drop-onnxruntime-java-linux-x64-tensorrt-${{cuda_version.key}}
          targetPath: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-linux-x64'

        outputs:
        - output: pipelineArtifact
          targetPath: $(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64
          artifactName: onnxruntime-java-gpu-${{cuda_version.key}}
      pool: 'onnxruntime-Win-CPU-VS2022-Latest'
      dependsOn: []
      condition: succeeded()
      steps:
      - template: ../templates/jar-packaging.yml
        parameters:
          package_type: gpu
