parameters:
- name: machine_pool
  displayName: 'The agent pool to run on (must use onnxruntime-qnn-windows22-arm64 image)'
  type: string
  default: 'onnxruntime-qnn-windows-vs-2022-arm64'

- name: QnnSdk
  displayName: QNN SDK version
  type: string
  default: '2.42.0.251225'

stages:
- stage: Windows_QNN_ARM64_Build_Test
  dependsOn: []
  jobs:
  - job: Build_QNN_EP_ARM64
    pool:
      name: ${{ parameters.machine_pool }}
      os: windows
      hostArchitecture: Arm64
    variables:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      skipComponentGovernanceDetection: true
      buildArch: arm64
      BuildConfig: 'RelWithDebInfo'
      ALLOW_RELEASED_ONNX_OPSET_ONLY: '1'
    timeoutInMinutes: 240
    workspace:
      clean: all
    steps:
    - checkout: self
      clean: true
      submodules: none

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: $(buildArch)

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 6.4.x

    - template: ../templates/jobs/download_win_qnn_sdk.yml
      parameters:
        QnnSDKVersion: ${{ parameters.QnnSdk }}

    - task: PythonScript@0
      displayName: 'Build QNN EP'
      inputs:
        scriptPath: '$(Build.SourcesDirectory)\tools\ci_build\build.py'
        arguments: >-
          --config $(BuildConfig)
          --build_dir $(Build.BinariesDirectory)
          --cmake_generator "Visual Studio 17 2022"
          --build_shared_lib --use_vcpkg --use_vcpkg_ms_internal_asset_cache
          --use_qnn shared_lib
          --qnn_home $(QnnSDKRootDir)
          --update --build --parallel

    - script: |
        python $(Build.SourcesDirectory)\tools\ci_build\build.py ^
          --config $(BuildConfig) ^
          --build_dir $(Build.BinariesDirectory) ^
          --cmake_generator "Visual Studio 17 2022" ^
          --build_shared_lib ^
          --use_qnn shared_lib ^
          --qnn_home $(QnnSDKRootDir) ^
          --test --enable_onnx_tests
      displayName: 'Run unit tests'

    - script: |
       .\$(BuildConfig)\onnx_test_runner -j 1 -v -e qnn -i "backend_path|$(QnnSDKRootDir)\lib\aarch64-windows-msvc\QnnCpu.dll" $(Build.SourcesDirectory)\cmake\external\onnx\onnx\backend\test\data\node
      workingDirectory: '$(Build.BinariesDirectory)\$(BuildConfig)'
      displayName: 'Run ONNX Tests'

    - script: |
       .\$(BuildConfig)\onnx_test_runner -j 1 -v -e qnn -i "backend_path|$(QnnSDKRootDir)\lib\aarch64-windows-msvc\QnnCpu.dll" C:\data\float32_models
      workingDirectory: '$(Build.BinariesDirectory)\$(BuildConfig)'
      displayName: 'Run float32 model tests'
