parameters:
  AgentPool: 'Win-CPU'
  StageSuffix: ''
  PoolDemands: ''
stages:
- stage: Nodejs_Test_${{ parameters.StageSuffix }}
  dependsOn:
  - Setup
  condition: succeeded()
  jobs:
  - job: Nodejs_Test_${{ parameters.StageSuffix }}
    workspace:
      clean: all
    timeoutInMinutes: 120
    pool:
      name: ${{ parameters.AgentPool }}
      ${{ if ne(parameters.PoolDemands, '') }}:
        demands: ${{ parameters.PoolDemands }}
    variables:
    - name: OnnxRuntimeBuildDirectory
      value: '$(Build.BinariesDirectory)'
    steps:
    - template: test.yml
