name: Windows CPU CI Pipeline

on:
  push:
    branches: [main, 'rel-*']
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.sha }}
  cancel-in-progress: true

jobs:
  build_x86_release:
    runs-on: ubuntu-latest

    steps:
      - name: Disabled
        shell: bash
        run: 'echo "This workflow has been disabled. TODO: Fully remove."'
